### ISSUE TITLE
Implement Other HTTP Methods

### ISSUE THREAD

**Issue by JamesMahy** [phpMv/ubiquity#108]
## Summary

Currently the framework only supports Post and Get, it would be easy to implement, Put, Delete and Patch.

## Motivation

Ensures good communication standards instead of bundling everything under GET and POST

**Comment by jcheron** [comment]
> Currently the framework only supports Post and Get, it would be easy to implement, Put, Delete and Patch.

Hi @JamesMahy 
Could you be more specific?

**Comment by JamesMahy** [comment]
Hey! Yeh sure.

So it's mainly about clean, self documenting restful API design, where people will typically use PUT to update a record, PATCH for a partial update and DELETE when deleting a resource.

https://restfulapi.net/http-methods/

PHP has support for these methods but the framework doesn't allow me to specify a router as "PUT", "PATCH" or "DELETE".

I can implement them by manually adding them to ubiquity-dev/src/Ubiquity/annotations/router/ and phpmv/ubiquity/src/Ubiquity/cache/CacheManager.php but seems like something you would expect the framework to incorporate already.

**Comment by jcheron** [comment]
The router already integrates all Http methods:
```php
/**
 * @route("update/", "methods"=> ["put"])
 */
public function update(){...}
```
and you can use `delete`, `patch`, `put`, `post`, `get`, `options`...

It is true that there are specific annotations only for `get` and `post`, because they are more frequently used.

Did you see that Ubiquity already implements a whole [Rest part](https://micro-framework.readthedocs.io/en/latest/rest/index.html), including some APIs (https://jsonapi.org for example)

**Comment by JamesMahy** [comment]
Thanks, that makes sense. It would be nice to keep a consistent approach with the least amount of code to improve readability.

EG

```
/**
 * @route("update/", "methods"=> ["put"])
 */
```
is less readable than
```
/**
 * @put("update/")
 */
```

it also means for consistency I can use @post and @get annotations for those types of routes but for put patch delete etc I would have to use the full annotation.

Minor issue really but can make code more verbose than is necessary

**Comment by jcheron** [comment]
@JamesMahy 
If you wish, and you have the time, you can add these missing annotations.
see https://github.com/phpMv/ubiquity-dev/issues/2

**Comment by JamesMahy** [comment]
Very happy to, I have never contributed to a public repo before so apologies if I do anything wrong initially.

Do I just need to implement the changes and do a pull request?

**Comment by jcheron** [comment]
No problem, I'm not infallible either.

>Do I just need to implement the changes and do a pull request?
Yeah, basically.
- fork the original repo
- clone ton fork
- create a branch on the clone to work
- implement (with regular commit+push)
- do a PR

see [contributing guide](https://micro-framework.readthedocs.io/en/latest/contributing/contributing-shem.html) for more
