### ISSUE TITLE
_rest reliant on setter being triggered to get value

### ISSUE THREAD

**Issue by JamesMahy** [phpMv/ubiquity#109]
The _rest array will only show values where the setter for that instance variable has been called.

Model:
```
namespace models;

/**
 * @table("name"=>"some_table")
 **/
class MyModel
{
	/**
	 * @id
	 * @column("name"=>"id_field")
	 */
	private $idField;
	
	/**
	 * @column("name"=>"value_field")
	 */
	private $valueField;
	
	public function getIdField(){return $this->idField;}
	public function setIdField($id=0){$this->idField = $id;}
	
	public function getValueField(){return $this->valueField;}
	public function setValueField($value){$this->valueField = $value;}	
}
```

Code
```
$item = new MyModel();
DAO::save($item);

print_r($item->_rest);
```

```
	Array
        (
            [id_field] => 1            
        )
```

But if I do this instead
```
$item = DAO::getOne(MyModel::class, 'id_field = ?', false, [1]);
print_r($item->_rest);
```

I get
```
	Array
        (
            [id_field] => 1
            [value_field] =>
        )
```

Alternatively if I do
```
$item = new MyModel();
$item->setValueField('hello');
DAO::save($item);

print_r($item->_rest);
```

I get

```
	Array
        (
            [id_field] => 1
            [value_field] => "hello"
        )
```

Incidentally, I'm using your framework for quite a big project so will probably find little issues like this as I test through. 

I hope you don't mind me raising them and if you need some help - i'm happy to help fix them as long as they're bugs and not intentional and that I'm using the framework incorrectly :)

**Comment by jcheron** [comment]
So you'd like the _rest array to always be complete?

Have you tried adding the `nullable` attribute?

```php
	/**
	 * @column("name"=>"value_field", "nullable"=>true)
	 */
	private $valueField;
```

**Comment by JamesMahy** [comment]
Ah ok, so it looks like it's because the field had a null default value.

Maybe my expectations are wrong, I would expect _rest to be consistent and provide all values for the model even if they're null or empty. 

It should almost be the other way around, I can't imagine many situations where you wouldn't want to know a column exists in the table just because it's null or not.

Be good to know what others think.

**Comment by jcheron** [comment]
Have you tried setting the `nullable` attribute to true?

**Comment by jcheron** [comment]
@JamesMahy Is that okay?
