### ISSUE TITLE
Parse error: syntax error, unexpected '=' in CacheManager.php

### ISSUE THREAD

**Issue by parsfanavar** [phpMv/ubiquity#111]
When I try to open http://localhost/testprj it shows the following error:
`
Parse error: syntax error, unexpected '=' in C:\xampp\htdocs\testprj\vendor\phpmv\ubiquity\src\Ubiquity\cache\CacheManager.php on line 63
`

Fresh install from git
> 	"require" : {
> 		"php" : ">7.0",
> 		"phpmv/ubiquity": "^2.3",
> 		"twig\/twig": "^2.0"
> 	},
> 

php server and version:
> XAMPP Version: 7.2.4

**Comment by jcheron** [comment]
The last Ubiquity `composer.json` is incorrectly configured.
You need `php ^7.4`
Or else you have to go back to an earlier version of Ubiquity (2.3.0).
