### ISSUE TITLE
[RFC] OAuth2 client Ubiquity module

### ISSUE THREAD

**Issue by jcheron** [phpMv/ubiquity#112]
## Summary

Offer the possibility to connect via OAuth2 to an Ubiquity application

## Motivation

It's a necessity, and it's often necessary in an application.
And you don't necessarily want to implement this part yourself.

## Compatibility with Ubiquity's philosophy 

Indicate compatibility or improvements in:
- ease of use
- Essential additional feature

## Expected results

Have the possibility to create to perform all the basic Oauth client operations.

## Additional context

- Creation of an OAuthManager, and/or a basic controller to perform Oauth operations.
- Saving the configuration in app/config (php array file)
- Using HybridAuth 3

**Comment by UlasSAYGINIM** [comment]
very good to see that!
