### ISSUE TITLE
[ORM] non autoinc pk are not affected on insert

### ISSUE THREAD

**Issue by jcheron** [phpMv/ubiquity#114]
### Steps
The model class:
```php
/**
 * @table("name"=>"devices")
 **/
class Device{

	/**
	 * @id
	 */
	private string $id = '';

	public function getId(){return $this->id;}
	public function setId($id){$this->id = $id;}
}
```
Inserting an Instance:
```php
$device = new Device();	
$device->setId('hello');

DAO::save($device);
```

### Actual & expected Results
The database entry for the field `id` is empty, instead of 'hello'

### Versions
Tested against 2.3.3, 2.3.4 and 2.3.5 - it works in 2.3.3 but not the others

@JamesMahy

**Comment by jcheron** [comment]
Fixed in [2.3.6 release](https://github.com/phpMv/ubiquity/releases/tag/2.3.6)

**Comment by JamesMahy** [comment]
Thank you :) Do you have somewhere to buy you a coffee or something?

**Comment by jcheron** [comment]
Thanks for the proposal, James. 😉 
Cheers. ☕ ☕

**Comment by UlasSAYGINIM** [comment]
with cookies maybe? :) or wonderful another snack :)

**Comment by jcheron** [comment]
be welcome, Ulas, especially if you don't come empty-handed.
🍪  🍪

**Comment by UlasSAYGINIM** [comment]
if there is a coffee , i am in it ;) cookies and other delicious stuff will come a lot. you may save it for later.
I cant come with  empty hands, it is our culture. we come with a lots of things :)
