### ISSUE TITLE
[UbiquityMyAdmin] Should be compatible with RoadRunner

### ISSUE THREAD

**Issue by andrei-dascalu** [phpMv/ubiquity#119]
### Steps
I'm opening this, though it was first reported on https://github.com/Lapinskas/roadrunner-ubiquity/issues/24 as it seems that the issue belongs in this repo.

1. `Ubiquity new api-ubiquity -a`
2. `cd api-ubiquity`
3. `Ubiquity serve -t=roadrunner`
4. Open `http://127.0.0.1:8095/`
5. Navigate to Admin

The command #3 doesn't seem to provide PHP logs anymore. However, in a previous manual setup I saw these:

```
WARN[0012] PHP Warning:  Cannot modify header information - headers already sent by (output started at <ubiquity_project_root>/vendor/phpmv/ubiquity-webtools/src/Ubiquity/controllers/admin/UbiquityMyAdminBaseController.php:260) in <ubiquity_project_root>/vendor/lapinskas/roadrunner-ubiquity/src/Request.php on line 97
```

Seems that UbiquityMyAdminBaseController starts manual output by flushing buffers, whereas RoadRunner always expects to receive PSR responses.

### Expected Result
Roadrunner can serve Admin

### Actual Result
Roadrunner responds with "worker error: invalid data found in the buffer (possible echo)"

### Versions
- Ubiquity framework: 2.3.8
- Ubiquity devtools: 1.2.14
- php 7.4.6
- OS: MacOSX

**Comment by jcheron** [comment]
I'll see what we can do on the Ubiquity side...

**Comment by andrei-dascalu** [comment]
Thanks - I also reported it on the integration library but it looks like a very specific issue, not sure where the fix should fall.
