### ISSUE TITLE
[Config] Database Connection Silently Fails

### ISSUE THREAD

**Issue by richardklint** [phpMv/ubiquity#12]
### Steps
Simply setup a project with a database name that doesn't exist.
### Expected Result
An exception be thrown.
### Actual Result
A message gets echo'ed and program continues. (See \Ubiquity\db\Database::connect)
### Versions
- Ubiquity: 2.0.11
- PHP: 7.1.27
- OS: Ubuntu 18.04

**Comment by jcheron** [comment]
Indeed, it is not very professional
A DBException would be more appropriate

**Comment by jcheron** [comment]
I know now why I did that:
The connection to the database is called very early in the `services.php` file.

If I generate an exception for the DB connection, it is no longer possible to access the administration part, which is problematic to correct the error, or to visualize the logs.

I will fix and throw an exception in the `connect` method of `DataBase`.
It will now be necessary to do a `try/catch` on the connection in `services.php`
