### ISSUE TITLE
[Router] Cached responses should preserve content-type

### ISSUE THREAD

**Issue by andrei-dascalu** [phpMv/ubiquity#120]
### Steps
```php
class TestController extends Controller {
    /**
     * @route("json","cache"=>true,"duration"=>3600)
     */
    public function index() {
        Logger::error('TestController', 'Starting');

        UResponse::asJSON();

        echo json_encode([
            'version' => 'v10',
            'hostname' => gethostname(),
            'itemsToShow' => 6000,
        ]);
    }
}
```

### Expected Result
when providing a cached result, the Content-Type should remain application/json

### Actual Result
the cached response is always text/html

### Versions
- Ubiquity framework: 2.3.8
- Ubiquity devtools: 1.2.14
- php 7.4.6
- OS MacOSX

**Comment by jcheron** [comment]
Thanks for reporting @andrei-dascalu 
the `Content-Type` has indeed been forgotten :-(

**Comment by jcheron** [comment]
Fixed in https://github.com/phpMv/ubiquity/commit/debf875ef8162cc67e51cd22d5f3687d629aafd1
