### ISSUE TITLE
[Rest] no violations on insert with ValidatorManager

### ISSUE THREAD

**Issue by Lagrida** [phpMv/ubiquity#122]
### Steps 
Whene i look at `_add` function in `RestBaseController` class : 
```
public function _add() {
		$model = $this->model;
		$instance = new $model ();
		$this->operate_ ( $instance, function ($instance) {
			$datas = $this->getDatas ();
			$this->_setValuesToObject ( $instance, $datas );
			if ($this->_validateInstance ( $instance, $datas )) {
				return $this->AddOperation ( $instance, $datas, true );
			}
			return null;
		}, "inserted", "Unable to insert the instance", [ ] );
}
```
I see this function `_validateInstance ( $instance, $datas )`.
And whene i look at it:
```
public function _validateInstance($instance, $members) {
		if ($this->useValidation) {
			$isValid = true;
			$violations = ValidatorsManager::validate ( $instance );
			foreach ( $violations as $violation ) {
				if (array_search ( $violation->getMember (), $members ) !== false) {
					$this->addViolation ( $violation );
					$isValid = false;
				}
			}
			return $isValid;
		}
		return true;
}
```

### Expected Result
This function must return false if a violation is presente.
### Actual Result
This function **return always true**, evene whene we have violations.
### Versions
- Ubiquity framework 2.3.9
- Ubiquity devtools 1.2.14
- php 7.4.6
- Windows

**Comment by jcheron** [comment]
Thanks for reporting @Lagrida 
I'm going to check it out.

**Comment by jcheron** [comment]
This should be good.
All that was missing was the `array_keys` call, like on the `_update` method.
https://github.com/phpMv/ubiquity/blob/065f3f46a8cfc991651d01413594972e7bc64f73/src/Ubiquity/controllers/rest/RestBaseController.php#L227

**Comment by Lagrida** [comment]
Thank you @jcheron, the email violation works good.
But there is a probleme with `@validator("notEmpty")` didn't work! also `@validator("isBool")`.

**Comment by jcheron** [comment]
I can't replicate your problem on `notEmpty` validator:
With this declaration:
```php
	/**
	 *
	 * @column("name"=>"nom","nullable"=>false,"dbType"=>"varchar(50)")
	 * @validator("length","constraints"=>array("max"=>50))
	 * @validator("notEmpty")
	 */
	private $nom;
```
With an empty value on `$nom`, I have this legitimate exception:
![image](https://user-images.githubusercontent.com/2511052/86303565-75310e00-bc0c-11ea-8311-46642750d8e2.png)

**Comment by jcheron** [comment]
Same thing for isBool validator, it works for me.
The isBool validator accepts `null, 0,1 true` and `false` values

**Comment by Lagrida** [comment]
okey @jcheron, i will use the latest version (2.3.10) and i will check again. Thanks.

**Comment by Lagrida** [comment]
I update Ubiquity version to latest (2.3.10), my model:
![132t1hbrth0tr5](https://user-images.githubusercontent.com/56971899/86351362-12676300-bc5c-11ea-84d6-85bbda142808.png)
I use Postman 
![h98rt40ht](https://user-images.githubusercontent.com/56971899/86351434-2b701400-bc5c-11ea-97ef-c0b25422db1f.png)
The input is inserted in database !

**Comment by jcheron** [comment]
The fix on validation is not on version 2.3.10
but only on dev-master !
You need to update to dev-master, pending 2.3.11
```
composer require phpmv/ubiquity:dev-master
```

**Comment by Lagrida** [comment]
Thanks @jcheron. it's work now :+1: 
I hade an other proposition, it's better to display all errors in an array instead of display one error at the time (if we have violations more than one)

**Comment by Lagrida** [comment]
Last bug : 
![51hgrt](https://user-images.githubusercontent.com/56971899/86353216-d1bd1900-bc5e-11ea-90a9-008619bb6940.png)
If we not send the variable, the framework didn't validate it !

**Comment by jcheron** [comment]
Indeed, the validation is done on the submitted fields, and not on all the members of the object.
It is more a choice than a bug.
For me, it was incoherent to make a validation check on a boolean, an email or something else, if the corresponding fields have not been modified.
But maybe it's a mistake on the insertion, when it's consistent on the update.

**Comment by Lagrida** [comment]
I agree whene it's an update (PATCH REQUEST), but in insertion no, because for example one can register (table user) without e-mail or an important information ..

**Comment by jcheron** [comment]
I agree with you, validation should be complete on the insertion.
We can open up another issue for that.
