### ISSUE TITLE
Parse Error in CacheManager.php

### ISSUE THREAD

**Issue by n0nag0n** [phpMv/ubiquity#125]
### Steps
- Create new project with `composer create-project phpmv/ubiquity-project projects/ubiquity`
- `vendor/bin/Ubiquity serve`
- Navigate to `localhost:8090/Admin`

### Expected Result
The page loads

### Actual Result
Page doesn't load. Gives the following error:
```
[Wed Jul  8 21:26:22 2020] PHP Parse error:  syntax error, unexpected '=' in /path/to/project/root/vendor/phpmv/ubiquity/src/Ubiquity/cache/CacheManager.php on line 63
[Wed Jul  8 21:27:31 2020] PHP Parse error:  syntax error, unexpected '=' in /path/to/project/root/vendor/phpmv/ubiquity/src/Ubiquity/cache/CacheManager.php on line 79
```
If you take out the `=` from the `??=` it will work and load.

Additionally, once the page does load, it all loads well except you can't navigate anywhere because there is a file issue. Possibly related?
```
Error
Message : file_put_contents(/path/to/project/root/.ubiquity/../app//cache//annotations/IndexController.php-387a4539.annotations.php): failed to open stream: No such file or directory
File : /home/acollier/projects/ubiquity/vendor/mindplay/annotations/src/annotations/AnnotationCache.php
Line : 73
```

### Versions
These are what is installed by the ubiquity-project repo.
- Ubiquity framework 2.3.5
- Ubiquity devtools 1.2.13
- php 7.2.24
- OS Linux Mint 19.3

**Comment by jcheron** [comment]
Hi @n0nag0n 
There have been a few versions, where php 7.4 was already required, and where the `composer.json` didn't mention it. **2.3.5** is one of them.
You're in this case https://github.com/phpMv/ubiquity/issues/111

**Comment by n0nag0n** [comment]
Well hot dog.....there it is. https://www.pixelite.co.nz/article/new-features-in-php-7-4/#:~:text=New%20features%20coming%20in%20PHP%207.4%201%20Spread,...%205%20One%20more.%20...%206%20Conclusion.%20

Couldn't find it when I googled earlier. I'm just surprised the framework is all about 7.4 when it's pretty new still. Cool beans though, thanks!
