### ISSUE TITLE
Question: Swoole Implementation

### ISSUE THREAD

**Issue by ljfreelancer88** [phpMv/ubiquity#126]
Hi, I've been looking for a framework that implemented the Swoole. My questions are:

1. Does ORM and DAO uses Swoole coroutine automatically or do i need to enable through configuration?
2. Does the database optionally support connection pool and read-write separation?
3. How can i "serve" Ubiguity using Swoole with custom port? Because what I have in mind is each microservice has different port serve by Swoole.

I think it should be added in the documentation.

Thanks in advance.

**Comment by jcheron** [comment]
some quick answers, I'll go into more detail later:
>Does ORM and DAO uses Swoole coroutine automatically or do i need to enable through configuration?

No, you have to create a DB connection with Swoole Db wrapper:
In **app/config.php**
```php
return ["database"=>['default' => [
			"wrapper" => "\\Ubiquity\\db\\providers\\swoole\SwooleWrapper",
			"type" => "mysql",
			"dbName" => "myDB",
			"serverName" => "127.0.0.1"
			"port" => 3306,
			"user" => "dbUser",
			"password" => "dbPassword",
			"options" => [],
			"cache" => false
		]
        ]
]
```

>Does the database optionally support connection pool and read-write separation?

Yes, for pooling, no for the read-write separation
see [Ubiquity tests](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/ubiquity/app/controllers/SwooleDbAsync.php) on Techempower benchmarks for an example of implementation.

>How can i "serve" Ubiguity using Swoole with custom port? Because what I have in mind is each microservice has different port serve by Swoole.

```bash
./Ubiquity serve -t=swoole -p=8999
```

>I think it should be added in the documentation.

It already is, but not in a Swoole section.

**Comment by jcheron** [comment]
see [documentation](https://micro-framework.readthedocs.io/en/latest/extra/async.html)
