### ISSUE TITLE
[Annotation] @column name not working

### ISSUE THREAD

**Issue by Lagrida** [phpMv/ubiquity#127]
### Steps
Consider this model :
![ik14uyti178k](https://user-images.githubusercontent.com/56971899/87287475-0d26d580-c4f2-11ea-8bb5-7e91593021e9.png)
### Expected Result
The attribute `$paymentid` must use `payment_id` in database.
### Actual Result
The name of `$paymentid` attribute used in database is not setted by the value in the annotation.
![ge8r40ge89r](https://user-images.githubusercontent.com/56971899/87287971-a48c2880-c4f2-11ea-9048-5ddc299e5f67.png)
### Versions
- Ubiquity framework 2.3.9
- Ubiquity devtools 1.2.14
- php 7.4.6
- all

**Comment by jcheron** [comment]
I believe it's already been mentioned here https://github.com/phpMv/ubiquity/issues/116
And that it's resolved
Try it with Ubiquity 2.3.10
and devtools 1.2.15
