### ISSUE TITLE
[PostgreSQL pdo]  has problem with PostgreSQL reserved Word as TableName and Webtools Errors with it.

### ISSUE THREAD

**Issue by UlasSAYGINIM** [phpMv/ubiquity#128]
### Steps
When I want to use table name User or user, PDO driver gives error.
In order to fix this, I need to edit PgsqlDriverMetas.php, Line 46 , 

	"SELECT a.attname, format_type(a.atttypid, a.atttypmod) AS data_type FROM   pg_index i JOIN   pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey) WHERE i.indrelid = '{$tableName}'::regclass AND    i.indisprimary;" 

this line into this,

	"SELECT a.attname, format_type(a.atttypid, a.atttypmod) AS data_type FROM   pg_index i JOIN   pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey) WHERE i.indrelid = '\\"{$tableName}\\"'::regclass AND    i.indisprimary;" 

Then i can create model of User via webtools.

after that, everything goes planned. but when i want to list of records for User Model. It gives another error on web admin.

In this case, i need to change another file PDOWrapper.php  , Line 19

	private static $quotes = [ 'mysql' => '`','sqlite' => '"','pgsql' => '' ];

into  this

	private static $quotes = [ 'mysql' => '`','sqlite' => '"','pgsql' => '"' ];

after that , when i want to list the records of User model, it gives error like this :

Error

    Message : Uncaught ReflectionException: Property models\User::$0 does not exist in C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\orm\traits\OrmUtilsFieldsTrait.php:91 Stack trace: #0 C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\orm\traits\OrmUtilsFieldsTrait.php(91): ReflectionProperty->__construct('models\\User', '0') #1 C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\orm\traits\DAOCoreTrait.php(127): Ubiquity\orm\OrmUtils::getPropKeys('models\\User') #2 C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\orm\DAO.php(67): Ubiquity\orm\DAO::_getAll(Object(Ubiquity\db\Database), 'models\\User', Object(Ubiquity\orm\parser\ConditionParser), false, NULL) #3 C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity-webtools\src\Ubiquity\controllers\admin\traits\ModelsTrait.php(153): Ubiquity\orm\DAO::getAll('models\\User', '', false) #4 C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity-webtools\src\Ubiquity\controllers\admin\traits\ModelsTrait.php(134): Ubiqui
    File : C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\orm\traits\OrmUtilsFieldsTrait.php
    Line : 91

### Expected Result
We can create User model for postgresql and get working.
### Reason to report

I couldnt find way to fix this, because unfortunately, i cant debug the framework properly.

### Versions
- Ubiquity framework "dev-master"
- Ubiquity devtools ^1.2
- Ubiquity-webtools "dev-master",
- php 7.x
- OS Windows 10

**Comment by UlasSAYGINIM** [comment]
I want to test the PDO driver and I created two tables and created foreign key between user and account tables.
one thing is making me curious about model creation because as you can see i didnt add autoincrement.
but web admin creates model id as autoincrement, the another point that i saw. the model is below.

> CREATE TABLE public."User"
> (
>     id bigint NOT NULL,
>     name character varying(45) COLLATE pg_catalog."default" NOT NULL,
>     email character varying(255) COLLATE pg_catalog."default" NOT NULL,
>     password character varying(45) COLLATE pg_catalog."default" NOT NULL,
>     account_id bigint,
>     CONSTRAINT "User_pkey" PRIMARY KEY (id),
>     CONSTRAINT account_id_key FOREIGN KEY (id)
>         REFERENCES public.account (id) MATCH SIMPLE
>         ON UPDATE NO ACTION
>         ON DELETE NO ACTION
> )
> WITH (
>     OIDS = FALSE
> )
> TABLESPACE pg_default;

> 
> CREATE TABLE public.account
> (
>     id bigint NOT NULL,
>     name character varying(50) COLLATE pg_catalog."default" NOT NULL,
>     CONSTRAINT account_pkey PRIMARY KEY (id)
> )
> WITH (
>     OIDS = FALSE
> )
> TABLESPACE pg_default;

> < ? php
> namespace models;
> class User{
> 	/**
> 	 * @id
> 	 * @column("name"=>"id","nullable"=>true,"dbType"=>"bigint")
> 	 * @validator("id","constraints"=>array("autoinc"=>true))
> 	**/
> 	private $id;
> 
> 	/**
> 	 * @column("name"=>"name","nullable"=>true,"dbType"=>"character varying(45)")
> 	 * @validator("length","constraints"=>array("max"=>45))
> 	**/
> 	private $name;
> 
> 	/**
> 	 * @column("name"=>"email","nullable"=>true,"dbType"=>"character varying(255)")
> 	 * @validator("email")
> 	 * @validator("length","constraints"=>array("max"=>255))
> 	**/
> 	private $email;
> 
> 	/**
> 	 * @column("name"=>"password","nullable"=>true,"dbType"=>"character varying(45)")
> 	 * @validator("length","constraints"=>array("max"=>45))
> 	 * @transformer("name"=>"password")
> 	**/
> 	private $password;
> 
> 	/**
> 	 * @column("name"=>"account_id","nullable"=>false,"dbType"=>"bigint")
> 	 * @validator("notNull")
> 	**/
> 	private $account_id;
> 
> 	/**
> 	 * @manyToOne
> 	 * @joinColumn("className"=>"models\\Account","name"=>"id","nullable"=>false)
> 	**/
> 	private $account;
> 
> 	 public function getId(){
> 		return $this->id;
> 	}
> 
> 	 public function setId($id){
> 		$this->id=$id;
> 	}
> 
> 	 public function getName(){
> 		return $this->name;
> 	}
> 
> 	 public function setName($name){
> 		$this->name=$name;
> 	}
> 
> 	 public function getEmail(){
> 		return $this->email;
> 	}
> 
> 	 public function setEmail($email){
> 		$this->email=$email;
> 	}
> 
> 	 public function getPassword(){
> 		return $this->password;
> 	}
> 
> 	 public function setPassword($password){
> 		$this->password=$password;
> 	}
> 
> 	 public function getAccount_id(){
> 		return $this->account_id;
> 	}
> 
> 	 public function setAccount_id($account_id){
> 		$this->account_id=$account_id;
> 	}
> 
> 	 public function getAccount(){
> 		return $this->account;
> 	}
> 
> 	 public function setAccount($account){
> 		$this->account=$account;
> 	}
> 
> 	 public function __toString(){
> 		return ($this->account_id??'no value').'';
> 	}
> 
> }

**Comment by jcheron** [comment]
The `dev-master` branch is not stable, and the quote has been removed for testing on postgresql.
It was the problem with reserved words and the difference between upper and lower case letters.
For the exception encountered, it is also a problem of stability on dev-master.

A `composer update`should be enough to eliminate these bugs.

For the classes generation, the autoinc on the Validator is applied on the primary integer keys.A database search on autoinc would be more appropriate (to be improved).
In the meantime, you can set the autoinc to false if you are using the validators.

**Comment by UlasSAYGINIM** [comment]
I used dev-master because of annotation bugs. it seems worked. this is why i want to try dev-master to see any latest fix.

i saw you commited something about pgsql. thanks it is removed the webtools listing models records screen but when i want to re-create models it gives error like this, dont you get this error?

Error

    Message : Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 HATA: "user" nesnesi mevcut değil LINE 1: ...d AND a.attnum = ANY(i.indkey) WHERE i.indrelid = 'User'::re... ^ in C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\drivers\PgsqlDriverMetas.php:46 Stack trace: #0 C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\drivers\PgsqlDriverMetas.php(46): PDO->query('SELECT a.attnam...') #1 C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\PDOWrapper.php(181): Ubiquity\db\providers\pdo\drivers\PgsqlDriverMetas->getPrimaryKeys('User') #2 C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\db\traits\DatabaseMetadatas.php(23): Ubiquity\db\providers\pdo\PDOWrapper->getPrimaryKeys('User') #3 C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity-dev\src\Ubiquity\orm\creator\database\DbModelsCreator.php(44): Ubiquity\db\Database->getPrimaryKeys('User')
    File : C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\drivers\PgsqlDriverMetas.php
    Line : 46


because  it needs update like this , '\"{$tableName}\"' against reserved words as i told at first message.

>  For the classes generation, the autoinc on the Validator is applied on the primary integer keys.A database search on autoinc would be more appropriate (to be improved).
> In the meantime, you can set the autoinc to false if you are using the validators.

thank you for information. this is what i thought.

**Comment by UlasSAYGINIM** [comment]
it must be like this, '\\"{$tableName}\\"'. sorry for github correction.

**Comment by UlasSAYGINIM** [comment]
meanwhile, you are adding redis, well done!

**Comment by UlasSAYGINIM** [comment]
Another problem,
I changed model annotation like 
"autoinc"=>false

then i want to add new record on account like id : 1 , name : test account 1
it is adding new record but gives error.

`class Account{
	/**
	 * @id
	 * @column("name"=>"id","nullable"=>true,"dbType"=>"bigint")
	 * @validator("id","constraints"=>array("autoinc"=>false))
	**/
	private $id;
`

`class User{
	/**
	 * @id
	 * @column("name"=>"id","nullable"=>true,"dbType"=>"bigint")
	 * @validator("id","constraints"=>array("autoinc"=>false))
	**/
	private $id;`

The Error on web tool. it seems still looking increment sequence on db.
i tried model cache re-create but i couldnt achive to get rid of the error.

Error

    Message : Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 HATA: "account_id_seq" nesnesi mevcut değil in C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\PDOWrapper.php:57 Stack trace: #0 C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\PDOWrapper.php(57): PDO->lastInsertId('account_id_seq') #1 C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\db\traits\DatabaseOperationsTrait.php(168): Ubiquity\db\providers\pdo\PDOWrapper->lastInsertId('account_id_seq') #2 C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\orm\traits\DAOUpdatesTrait.php(147): Ubiquity\db\Database->lastInserId('account_id_seq') #3 C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\controllers\crud\CRUDHelper.php(88): Ubiquity\orm\DAO::insert(Object(models\Account)) #4 C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity-webtools\src\Ubiquity\controllers\admin\traits\ModelsTrait.php(236): Ubiquity\controllers\crud\CRUDHelper::update(O
    File : C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\PDOWrapper.php
    Line : 57

**Comment by UlasSAYGINIM** [comment]
Hi, another thing on web tool.

if i click nothing to display on any model which does not have any record. it gives this error below.
 
```
Error

    Message : Uncaught ArgumentCountError: Too few arguments to function Ubiquity\controllers\admin\UbiquityMyAdminBaseController::_showModelDetails(), 0 passed in C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\controllers\Startup.php on line 148 and exactly 1 expected in C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity-webtools\src\Ubiquity\controllers\admin\traits\ModelsTrait.php:359 Stack trace: #0 C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\controllers\Startup.php(148): Ubiquity\controllers\admin\UbiquityMyAdminBaseController->_showModelDetails() #1 C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\controllers\Startup.php(109): Ubiquity\controllers\Startup::runAction(Array, true, true) #2 C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\controllers\Startup.php(69): Ubiquity\controllers\Startup::forward('Admin/_showMode...') #3 C:\Php_Examples\default_nginx\.ubiquity\_index.php(18): Ubiquity\controllers\Startup::run(Array) #4 C:\Php_Examples\defaul
    File : C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity-webtools\src\Ubiquity\controllers\admin\traits\ModelsTrait.php
    Line : 359
```

**Comment by UlasSAYGINIM** [comment]
Another thing on webtool,
when i added new record on model. it does not change model record count on left black box.
in order to correct that , i went to cache section and click see datas button.
I also uncheck model cache on cache section on web tool before that.

**Comment by jcheron** [comment]
Effectively, line 46 in the `PgsqlDriverMetas` class, it's the cast with regclass that causes the need to use quotes

**Comment by jcheron** [comment]
autoinc pb on insert shifted to https://github.com/phpMv/ubiquity/issues/129

**Comment by jcheron** [comment]
Click on `Nothing to display` pb shifted to https://github.com/phpMv/ubiquity/issues/130

**Comment by jcheron** [comment]
`Record count` pb on insert shifted to https://github.com/phpMv/ubiquity/issues/131

**Comment by UlasSAYGINIM** [comment]
thank you for you incredible work. we have new bugs :)
