### ISSUE TITLE
[Rest] CORS with localhost Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by Lagrida** [phpMv/ubiquity#135]
### Steps
Consider this Rest Controller:
![image](https://user-images.githubusercontent.com/56971899/88341285-41419800-cd35-11ea-8d3c-3374c2b225fa.png)

### Expected Result
The expected result is that `Access-Control-Allow-Origin` allow the website `http://localhost:8080` to get,post,... (methods allowed in `Access-Control-Allow-Methods`).
### Actual Result
![image](https://user-images.githubusercontent.com/56971899/88341711-02601200-cd36-11ea-80e8-381b5a521aa4.png)
### Versions
- Ubiquity framework 2.3.10
- Ubiquity devtools 1.2.14
- php 7.4.6
- all

**Comment by jcheron** [comment]
It would be preferable to use the local server via `http://127.0.0.1:8080` and not `localhost`, which often causes problems.
And if you use Chrome, I don't think **cors** will ever go through with **localhost**.

see https://stackoverflow.com/questions/10883211/deadly-cors-when-http-localhost-is-the-origin

**Comment by Lagrida** [comment]
Thank you @jcheron , nothing of solutions works for me, can you please set `Access-Control-Allow-Origin : *` in developpement mode ? because only get work, `POST, PUT,..` need an origine.

**Comment by Lagrida** [comment]
I create a simple php script to test, if i set `Access-Control-Allow-Origin : http://localhost:8080` for a raison i don't know didn't work!
![image](https://user-images.githubusercontent.com/56971899/88377440-16882b80-cd97-11ea-8b5c-ed3569c1d414.png)
But Like this the script work very well:
![image](https://user-images.githubusercontent.com/56971899/88377482-328bcd00-cd97-11ea-8bc5-a691d94febc3.png)
I suggest to add an attribute in `config/config.php` called `devMode` and if it's `true` allow `Access-Control-Allow-Origin : *` for all methods.

**Comment by jcheron** [comment]
You should say a little more about the conditions under which you make this request (tool, browser...)
For my part, I have no problem with the address `http://127.0.0.1:8080`.
The `Access-Control-Allow-Origin` header is set to * by default.
![image](https://user-images.githubusercontent.com/2511052/88377889-45ef6600-cda0-11ea-8893-ac6c5072d4cf.png)

**Comment by Lagrida** [comment]
@jcheron, i create this method : 
![image](https://user-images.githubusercontent.com/56971899/88378461-f48fa880-cd98-11ea-9b65-37812a418a16.png)
This method work very well in `postman` : 
![rt6581h4r8t4hrt](https://user-images.githubusercontent.com/56971899/88378537-1e48cf80-cd99-11ea-9c27-91a4bcd51dcc.png)
But i have problem whene i use vue with axios to post (cross origin problem mentionned above).
I haven't this problem with the simple php script that i created whene i set `Access-Control-Allow-Origin : * ` for all methods.

**Comment by Lagrida** [comment]
I create this php script and work very well with vueJs, axios in all browsers :
![image](https://user-images.githubusercontent.com/56971899/88380053-be075d00-cd9b-11ea-88c8-5af56ac150ea.png)

**Comment by jcheron** [comment]
I implemented exactly the same method as you, without changing the default Rest server:
```php
class RestUsers extends \Ubiquity\controllers\rest\RestController {

	public function connect() {
		if (URequest::isPost()) {
			$user = URequest::post('user');
			if (isset($user)) {
				$tokenInfos = $this->server->connect();
				USession::set($tokenInfos['access_token'], $user);
				$tokenInfos['user'] = $user;
				echo $this->_format($tokenInfos);
				return;
			}
		}
		throw new RestException('Unauthorized', 401);
	}
}
```
I didn't test with Axios, I tested with jQuery, and I couldn't reproduce your problem:
#### Request headers
![image](https://user-images.githubusercontent.com/2511052/88380572-14c56480-cda5-11ea-92d0-6572f4881173.png)
#### Response headers
![image](https://user-images.githubusercontent.com/2511052/88380616-273f9e00-cda5-11ea-9327-91281a91837f.png)

I'd have to compare the headers between your request and mine.

**Comment by Lagrida** [comment]
Request:
![image](https://user-images.githubusercontent.com/56971899/88382235-f741cc00-cd9f-11ea-99c3-e3d375ebff91.png)
Response:
![image](https://user-images.githubusercontent.com/56971899/88382303-12acd700-cda0-11ea-9e4d-f121d12a28c8.png)
Console:
![image](https://user-images.githubusercontent.com/56971899/88382356-32dc9600-cda0-11ea-8b47-e021e2327660.png)

**Comment by Lagrida** [comment]
The same problem with `http://127.0.0.1:8080`.

**Comment by Lagrida** [comment]
@jcheron `GET` method only works!
Response:
```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE, PATCH, HEAD
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 86400
Cache-Control: no-store, no-cache, must-revalidate
Connection: Keep-Alive
Content-Length: 379
Content-Type: application/json; charset=utf8
Date: Fri, 24 Jul 2020 10:50:46 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive: timeout=5, max=100
Pragma: no-cache
Server: Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.4.6
Set-Cookie: yassine=57hle7l03a6p75qj29kn6k8jqg; path=/
Set-Cookie: c1X_5SRWK2mUDskHVNB0hlYfvJvmtxqkxprXefCR8Cc=a41MYzWheboj-N_n7uZ6GQUzQrteQ6rDFF-5dMHTHXU; path=/
Vary: Accept
X-Powered-By: PHP/7.4.6
```
Request:
```
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Host: localhost
Origin: http://localhost:8080
Referer: http://localhost:8080/admin/payments
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 OPR/69.0.3686.77
```

**Comment by jcheron** [comment]
It's strange, I don't see what you're doing different.
You're missing all the Access-Control headers in your response.
Can you put the full code of your controllers (the Rest and the one that makes the Axios request), and not screenshots?

**Comment by Lagrida** [comment]
PaymentController :
``` lang-php
<?php
namespace controllers;

use Ubiquity\utils\http\URequest;
use Ubiquity\utils\http\USession;

/**
 * Rest Controller PaymentController
 * @route("/payment","inherited"=>true,"automated"=>true)
 * @rest("resource"=>"models\Payment")
 */
class PaymentController extends \Ubiquity\controllers\rest\RestController {
    /**
    * This method simulate a connection.
    * Send a <b>user</b> variable with <b>POST</b> method to retreive a valid access token
    * @route("methods"=>["post"])
    */
    public function connect(){
        //if(!URequest::isCrossSite()){
            if(URequest::isPost()){
                $user=URequest::post("user");
                if(isset($user)){
                $tokenInfos=$this->server->connect ();
                USession::set($tokenInfos['access_token'], $user);
                $tokenInfos['user']=$user;
                    echo $this->_format($tokenInfos);
                    return;
                }
            }
        //}
        throw new \Exception('Unauthorized',401);
    }
}
```
The template to post :
``` lang-html
<template>
  <div class="container">
    <div class="row">
        <div class="col text-left">
            <div class="wrapper">
                <AdminSideBar />
                <!-- Content -->
                <div id="content">
                    <form @submit="formSubmit" class="form-inline">
                        <input v-model="user" type="text" class="form-control mr-2" placeholder="Enter username" />
                        <button type="submit" class="btn btn-danger">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
  </div>
</template>
<script>
import axios from "axios";
import AdminSideBar from "@/components/AdminSideBar.vue";
export default {
  name: "Connect",
  components: {
    AdminSideBar
  },
  data() {
      return {
          user:''
      }
  },
  methods: {
      formSubmit(e) {
          e.preventDefault();
          axios.post('http://localhost/yassine/payment/connect', {
              user: this.user
          })
          .then(response => {
          console.log(response.data);
        })
        .catch(error => {
          console.log("l'erreur : " + error);
        })
        .finally(() => console.log(this.user));
      }
  }
};
</script>
```

**Comment by Lagrida** [comment]
And this is the code for `GET` Resquest, work good :
```
  mounted(){
      axios.get('http://localhost/yassine/payment/get')
      .then(response =>{
          this.datas = response.data;
      })
      .catch(e => {
        this.errored = true;
        if(e.response){
            this.error = e.response.data;
        }else{
            this.error.title = e;
            this.error.detail = '';
        }
        
      })
      .finally(() => {
        this.loading = false;
      });
  }
```

**Comment by jcheron** [comment]
no problem with your VueJS code, except that you don't post with `application/x-www-form-urlencoded`:
You should use to post:
```java
new URLSearchParams();
params.append('user', this.user);
axios.post('http://127.0.0.1:8090/rest/users/connect', params);
```
can you try without this **localhost**, and with the built-in Ubiquity server?
```php
Ubiquity serve
```

**Comment by Lagrida** [comment]
Many thanks to you @jcheron Your code works, the problem as you say come from `application/x-www-form-urlencoded`.
Thanks

**Comment by Lagrida** [comment]
Last question, how can we send Bearer token with `post, update, delete` requests after using the connect post (and retrieve the Bearer token)

**Comment by jcheron** [comment]
To retrieve the token from your rest controller:
```php
$token=$this->_getHeaderToken();
```
You can then pass it to **axios**, to return it in the header of the next query:
```javascript
const config = {
    headers: { Authorization: 'Bearer <?=$token?>' }
};
new URLSearchParams();
params.append('foo', 'bar');
axios.post('http://127.0.0.1:8090/restUrl', params, config);
```

**Comment by Lagrida** [comment]
Okey, thanks.

**Comment by Lagrida** [comment]
@jcheron , using `$token = $this->server->_getHeaderToken();` i found this error:
![image](https://user-images.githubusercontent.com/56971899/88457818-71964d00-ce81-11ea-9ba7-4c0d0310eafe.png)
This function not adding `Authorization: Bearer --token--` in header of all pages :
```
    public function connect(){
        //if(!URequest::isCrossSite()){
            if(URequest::isPost()){
                $user=URequest::post("user");
                if(isset($user)){
                $tokenInfos=$this->server->connect ();
                USession::set($tokenInfos['access_token'], $user);
                USession::set('myToken', $tokenInfos['access_token']);
                $tokenInfos['user']=$user;
                    echo $this->_format($tokenInfos);
                    return;
                }
            }
        //}
        throw new \Exception('Unauthorized',401);
    }
```
We should to add the given token to a session, but whene i display `USession::getAll();` in a get function, i can't see `myToken` in session array!
```
Array
(
    [X-XSRF-TOKEN] => Ubiquity\utils\http\session\protection\CsrfToken Object
        (
            [name:Ubiquity\utils\http\session\protection\CsrfToken:private] => d7Qyt6Rw7KT9Lp-jQx0A3TlqkALmBDZT61dzA1J_WJU
            [value:Ubiquity\utils\http\session\protection\CsrfToken:private] => kviX5fx5zr1tuh2mHs20YnFloxnt7Jhw-8eKOjuS_l4
        )
)
```

**Comment by jcheron** [comment]
This method raises an exception if the token does not exist, this is normal.
you can handle it with a try/catch.
```php
try{
    $token = $this->server->_getHeaderToken();
}catch(RestException $re){
    //no token created
}
```
Otherwise, I don't see what you want to do with the session.
Logically, the client is supposed to return the authorization token with each request.

If you lose the session, it's because your axios requests don't send back the session cookie.

**Comment by Lagrida** [comment]
Thank you @jcheron , i found a way to stock the bearer token and use it in differente requests (https://developer.mozilla.org/fr/docs/Web/API/Window/sessionStorage)

**Comment by Lagrida** [comment]
@jcheron the only methods works up to now are `GET, POST`, but whene i use `PUT, PATCH, DELETE` there is no headers in the response and the request failed. Also all methods `GET, POST, PUT,..` not working if i use `@authorization` annotation in function in the RestControllers and making `withCredentials: true` with `headers:{ 'Authorization','Bearer 55d....'` in axios.
To test please make a differente url for the back-end

**Comment by jcheron** [comment]
For other users, who would also be looking for answers in the future, I do not think it is appropriate to submit different problems in the same issue.
This is a new problem, isn't it?

**Comment by Lagrida** [comment]
okey i will open another issue.
