### ISSUE TITLE
[Rest] Problem with XMLHttpRequest (Ajax) and Cross origin request (CORS)

### ISSUE THREAD

**Issue by Lagrida** [phpMv/ubiquity#136]
### Steps
URL back-end : `http://localhost/yassine/`
Consider this RestController:
```
/**
 * Rest Controller PaymentController
 * @route("/payments","inherited"=>true,"automated"=>true)
 * @rest("resource"=>"models\Payment")
 */
class PaymentController extends \Ubiquity\controllers\rest\RestController {
    /**
    * @route("/addPayment", "methods"=>["post"])
    */
    public function addPayment(){
        echo "Post done";
    }
    /**
    * @route("/putPayment", "methods"=>["put"])
    */
    public function putPayment(){
        echo "Put done";
    }
    /**
    * @route("/patchPayment", "methods"=>["patch"])
    */
    public function patchPayment(){
        echo "Patch done";
    }
}
```
URL front-end : `http://localhost:8080/`
I use VUE CLI with axios.
Consiser this code : 
```
<div class="py-3">
       <button type="button" @click="addPayment" class="btn btn-danger">Post</button> &nbsp;
       <button type="button" @click="putPayment" class="btn btn-info">Put</button> &nbsp;
       <button type="button" @click="patchPayment" class="btn btn-success">Patch</button> &nbsp;
</div>
```
```
  methods: {
    addPayment: function(){
        const params = new URLSearchParams();
        axios.post(this.paymentService + 'payments/addPayment' , params).then(response => {
            console.log(response.data);
        }).catch(error => {
            console.log(error);
        });
    },
    putPayment: function(){
        const params = new URLSearchParams();
        axios.put(this.paymentService + 'payments/putPayment' , params).then(response => {
            console.log(response.data);
        }).catch(error => {
            console.log(error);
        });
    },
    patchPayment: function(){
        const params = new URLSearchParams();
        axios.patch(this.paymentService + 'payments/patchPayment' , params).then(response => {
            console.log(response.data);
        }).catch(error => {
            console.log(error);
        });
    }
 }
```
![image](https://user-images.githubusercontent.com/56971899/88485861-51de5200-cf71-11ea-947d-360692c06594.png)

### Expected Result
If i click in Post button above (red button) i will see `Post done` in console.
If i click in Put button above (blue button) i will see `Put done` in console.
If i click in Patch button above (green button) i will see `Patch done` in console.
### Actual Result
Only Post Button work ! if i click in Put or Patch button an error happened, and no headers are avaible!
If i click in post button, **Headers** (work) :
![image](https://user-images.githubusercontent.com/56971899/88485908-e779e180-cf71-11ea-9107-ed3b216a5bc4.png)
If i click in put button, **Console** (not working)
![image](https://user-images.githubusercontent.com/56971899/88485896-b3062580-cf71-11ea-9810-39311238158b.png)
**Put Headers** (not working)
![image](https://user-images.githubusercontent.com/56971899/88485948-1ee88e00-cf72-11ea-8fe1-6ce50a169a07.png)

### Versions
- Ubiquity framework 2.3.10
- Ubiquity devtools 1.2.14
- php 7.4.8
- all

**Comment by jcheron** [comment]
Your routes should be defined in the following way, defining the method, but without changing the URL:
```php
	/**
	 *
	 * @patch
	 */
	public function patchPayment() {
		echo "Patch done";
	}
```

**Comment by Lagrida** [comment]
After making changes and init-cache, the same messages :
**console**
![er4g125e](https://user-images.githubusercontent.com/56971899/88486872-c36dce80-cf78-11ea-946e-20a216833c88.png)
**Response Headers**
![ht952ythrt](https://user-images.githubusercontent.com/56971899/88486878-d1235400-cf78-11ea-9c36-0b7bb113235c.png)

**Comment by jcheron** [comment]
With Cors (for the `PATCH`, `PUT`, `DELETE` methods), a preliminary request (`OPTIONS` method) is made to the same url as the requested one, a request which must return the `Access-Control-Allow-Origin` header.

In your case, you set different URLs for each of your actions, so the controller must answer OPTIONS requests to the same URLs.
Usually, on a controller, the same URL is always used, and only the HTTP method changes for each action.

However, you can make your controller respond to all OPTIONS requests, regardless of the URL, by adding this route :
```php
	/**
	 * @options("/{url}")
	 */
	public function options($url) {}
```

**Comment by Lagrida** [comment]
Thank you @jcheron ,
The code not work, but this works:
```
    /**
    * @options("/putPayment")
    * @route("/putPayment", "methods"=>["put"])
    */
    public function putPayment(){
        echo "Put done";
    }
```
I suggest adding examples of annotations in the documentation : https://micro-framework.readthedocs.io/en/latest/devtools.html

**Comment by jcheron** [comment]
I agree with you about the documentation, especially since CORS is never obvious.
On the other hand, I would like to know what is wrong with my proposal?
It works for me (it's tested), and it's a more general solution

**Comment by Lagrida** [comment]
Thank you, your code worke fine, i think i forgot to init cache.
