### ISSUE TITLE
[Rest] Preventing adding/modifying some attributs in Model

### ISSUE THREAD

**Issue by Lagrida** [phpMv/ubiquity#137]
## Summary

I suggest to add a procedure to prevent some attributs in Model from adding/modifying.
**Example:** consider this model:
``` php
<?php
namespace models;
/**
 * @table("name"=>"users")
 **/
class User{
    /**
     * @id
     * column("name" => "id", "nullable" => false, "dbType" => "int(11)")
     **/
    private $id;
    /**
     * column("name" => "username", "nullable" => false, "dbType" => "varchar(100)")
     **/
    private $username;
    /**
     * column("name" => "level", "nullable" => false, "dbType" => "int(2)")
     **/
    private $level;
?>
```
If we have `level=1` then this user is normal , and if `level=2` this user is **admin**.

My suggestion is to add a procedure in the existing methods `_add, _update` in class `RestBaseController` to prevent normal users from adding or updating the attribut `$level`.

## Motivation

This is intersting to secure our application from exceeding permissions.

## Compatibility with Ubiquity's philosophy 

- a secure application
- easy of use

## Expected results

The expected result is not exceeding permissions of use.

**Comment by jcheron** [comment]
Thank you for this contribution.
It's an interesting idea for the Rest part. It would strengthen the control on the client side, in the application, and therefore the security.

Technically, I think it's enough to add a possible control of the data sent by Http methods (POST, PATCH and PUT).

**Comment by Lagrida** [comment]
Thank you, Technically i suggest to add functions in `RestBaseController` called `_addWithout([list of attributs])` and `_updateWithout([list of attributs])`.
Adding also `_addWith([list of attributs])` and `_updateWith([list of attributs])`

**Comment by jcheron** [comment]
Your `_addWithout` and `_addWith` methods may conflict if the values are wrong.
What about adding a `beforeAdd(array $datas)` and a `beforeUpdate(array $datas)` methods to which you would pass the submitted data, allowing you to modify them?

**Comment by Lagrida** [comment]
Good idea @jcheron

**Comment by jcheron** [comment]
There would also be the solution to create dedicated Events, and go through the `EventManager` for that:
```php
EventsManager::addListener('rest.before.update', function (RestController $resource, array $datas) {
	// do something with $datas for $resource
});
```

**Comment by jcheron** [comment]
See in the [doc](https://micro-framework.readthedocs.io/en/latest/rest/index.html#modification-of-sent-data)
