### ISSUE TITLE
[annotation] Problem in insertion with @column dbType datetime

### ISSUE THREAD

**Issue by Lagrida** [phpMv/ubiquity#138]
### Steps
Consider this Model
``` php
<?php
namespace models;
/**
 * @table("name"=>"gift_cards_admin")
 **/
class GiftCardAdmin{
    /**
     * @id
     * column("name" => "giftcardid", "nullable" => false, "dbType" => "int(11)")
     * @validator("id","constraints"=>array("autoinc"=>true))
     **/
    private $giftcardid;
    /**
     * column("name" => "ladate", "nullable" => true, "dbType" => "datetime")
     **/
    private $ladate;
?>
```
### Expected Result
Whene i do insertion in controller the instance should be added in database.
### Actual Result
The instatnce not inserted and i have this error:
![image](https://user-images.githubusercontent.com/56971899/88918042-b4c93500-d260-11ea-8992-a18e042c78f5.png)
And whene i remove the attribute `$ladate` insertion work.
### Versions
- Ubiquity framework 2.3.11
- Ubiquity devtools 1.2.14
- php 7.4.8
- all

**Comment by jcheron** [comment]
This works by default if your date has the format 
`Y-m-d H:i:s` => 2020-07-30 15:03
If not, you can use a **Transformer** on the date field.
