### ISSUE TITLE
Namespaces usage

### ISSUE THREAD

**Issue by Lagrida** [phpMv/ubiquity#140]
### Steps
consider this code 
``` php
$giftCard = DAO::getOne(models\GiftCardAdmin::class, ['code'=>'jrthry2475fg']);
```
I tried also :
``` php
$giftCard = DAO::getOne(models\GiftCardAdmin::class, 'code= ?',false,['jrthry2475fg']);
```
Model:
``` php
<?php
namespace models;
/**
 * @table("name"=>"gift_card_admin")
 **/
class GiftCardAdmin{
    /**
     * @id
     * column("name" => "giftcardid", "nullable" => false, "dbType" => "int(11)")
     * @validator("id","constraints"=>array("autoinc"=>true))
     **/
    private $giftcardid;
    /**
     * column("name" => "code", "nullable" => false, "dbType" => "varchar(100)")
     * @validator("notEmpty")
     **/
    private $code;
    // getters and setters
}
?>
```
### Expected Result
get the object with code = jrthry2475fg if exists.
### Actual Result
![image](https://user-images.githubusercontent.com/56971899/89533603-924c9400-d7eb-11ea-9603-9458605e5609.png)
I think that this problem is related to cache
### Versions
- Ubiquity framework 2.3.11
- Ubiquity devtools 1.2.14
- php 7.4.8
- all

**Comment by jcheron** [comment]
The reference to the `GiftCardAdmin` class is not correct.
You have to do:
```php
$giftCard = DAO::getOne(\models\GiftCardAdmin::class, 'code= ?',false,['jrthry2475fg']);
```
or
```php
use models\GiftCardAdmin;
...
$giftCard = DAO::getOne(GiftCardAdmin::class, 'code= ?',false,['jrthry2475fg']);
```
Without the initial slash, php will fetch the class from the current namespace:
```controllers\models\GiftCardAdmin```

**Comment by Lagrida** [comment]
Thank you @jcheron

**Comment by Lagrida** [comment]
I suggest to modify this in documentation : https://micro-framework.readthedocs.io/en/latest/model/dao.html
