### ISSUE TITLE
[ORM] Problem in insertion with associations

### ISSUE THREAD

**Issue by Lagrida** [phpMv/ubiquity#141]
### Steps
I am trying to work with Associations in documentation [here](https://micro-framework.readthedocs.io/en/latest/model/models.html)
I do the example in documentation: 
```php
class User{
    /**
     * @id
     * column("name" => "id", "nullable" => false, "dbType" => "int(11)")
     * @validator("id","constraints"=>array("autoinc"=>true))
     **/
    private $id;
    /**
     * column("name" => "firstname", "nullable" => false, "dbType" => "varchar(255)")
     **/
    private $firstname;
    /**
     * @manyToOne
     * @joinColumn("className"=>"models\\Organization","name"=>"id_organization","nullable"=>false)
     **/
    private $organization;
    public function __construct(){}
    // getters and setters
}
?>
```
```php
class Organization{
    /**
     * @id
     * column("name" => "id", "nullable" => false, "dbType" => "int(11)")
     * @validator("id","constraints"=>array("autoinc"=>true))
     **/
    private $id;
    /**
     * column("name" => "name", "nullable" => false, "dbType" => "varchar(255)")
     **/
    private $name;
    /**
     * @oneToMany("mappedBy"=>"organization","className"=>"models\\User")
     **/
    private $users;
    public function __construct(){}
    // getters and setters
}
?>
```
**Tables in database :**
table users:
![image](https://user-images.githubusercontent.com/56971899/89719885-bc0ce300-d9c4-11ea-9531-0deb8fe7688e.png)
table organizations:
![image](https://user-images.githubusercontent.com/56971899/89719903-f70f1680-d9c4-11ea-9b5c-d10dbfd2e048.png)
I added organizations in database.
And i try this code to add a user:
```php
class RestUsersController extends \Ubiquity\controllers\rest\RestController {
    /**
     * @route("/simulate", "methods"=>["get"])
     */
    public function simulate(){
        $org = DAO::getById(\models\Organization::class,2);
        $user = new \models\User();
        $user->setFirstname("Albert");
        $user->setOrganization($org);
        $result = DAO::save($user);
        if($result){
            echo $this->_getResponseFormatter()->getOne($user);
        }else{
            echo"Not inserted!";
        }
    }
}
```

### Expected Result
Insert a user in database
### Actual Result
user is not inserted!
### Versions
- Ubiquity framework 2.3.11
- Ubiquity devtools 1.2.14
- php 7.4.8
- all

**Comment by jcheron** [comment]
I can't reproduce this bug.
On my side, no problem whith the insertion using this code.

**Comment by Lagrida** [comment]
@jcheron , it's an error from me in setter, i fixed and now i can insert, but there is a problem in `@manyToOne`.
If the name of row in database equals to the field he's not displayed, example:
we take the same example above but with : 
```php
class User{
    /**
     * @id
     * column("name" => "id", "nullable" => false, "dbType" => "int(11)")
     * @validator("id","constraints"=>array("autoinc"=>true))
     **/
    private $id;
    /**
     * column("name" => "firstname", "nullable" => false, "dbType" => "varchar(255)")
     **/
    private $firstname;
    /**
     * @manyToOne
     * @joinColumn("className"=>"models\\Organization","name"=>"id_organization","nullable"=>false)
     **/
    private $id_organization;

    public function __construct(){}
    // getters & setters
}
?>
```
And consider : 
```php
    /**
     * @route("/getAll", "methods"=>["get"])
     */
    public function getAll(){
        parent::get("1=1", true);
    }
```
The function don't display organization field.

**Comment by jcheron** [comment]
The name of the foreign key field (`id_organization`) must be different from the name of the corresponding object member (`myOrga` for example).

```php
    /**
     * @manyToOne
     * @joinColumn("className"=>"models\\Organization","name"=>"id_organization","nullable"=>false)
     **/
    private $myOrga;
```;

**Comment by Lagrida** [comment]
Thank you @jcheron ,  I wonder about how we can get `count` (the number of lines in database) without getting the whole lines (`get()`)

**Comment by jcheron** [comment]
you have a dedicated `count` method:
```php
$allCount=DAO::count(User::class);
$notSuspendedCount=DAO::count(User::class, 'suspended = ?', [false]);
```
Or `ucount` if you want to set conditions on linked objects:
Number of users belonging to the **ONU** named organization.
```php
$count=DAO::uCount(User::class,'organization.name= ?',['ONU']);
```

**Comment by Lagrida** [comment]
Thank you @jcheron , i suggest to add those informations in documentation.

**Comment by Lagrida** [comment]
@jcheron , how to use mysql transaction ?

**Comment by jcheron** [comment]
Thank you for asking questions @Lagrida , but they should not be stacked in the same issue, otherwise it is impossible for users with the same questions to find answers.

**Comment by Lagrida** [comment]
@jcheron i open a new issue ? because it's not a bug or new feature.
