### ISSUE TITLE
[DAO] sql transaction

### ISSUE THREAD

**Issue by Lagrida** [phpMv/ubiquity#143]
### Steps
I wander about how Ubiquity handle mysql transactions ?
I search in documentation [here](https://micro-framework.readthedocs.io/en/latest/devtools.html) and i don't found transactions.
### Versions
- Ubiquity framework 2.3.11
- Ubiquity devtools 1.2.14
- php 7.4.8
- OS

**Comment by jcheron** [comment]
the same here: https://github.com/phpMv/ubiquity/issues/142
