### ISSUE TITLE
[ORM] OneToOne and OneToMany anotations

### ISSUE THREAD

**Issue by Lagrida** [phpMv/ubiquity#144]
### Steps
I have 2 questions :

1.  why there is not `@OneToOne` anotation ?
2. How display `@oneToMany` in rest (i do exactely the example in documentation [here](https://micro-framework.readthedocs.io/en/latest/model/models.html) but nothing is displayed)

### Versions
- Ubiquity framework 2.3.11
- php 7.4.*
- all

**Comment by jcheron** [comment]
> 1. why there is not `@OneToOne` anotation ?

It is a choice, the `oneToOne` has only semantic value.
You can put a `manyToOne` on each side, which amounts to the same thing.

> 2. How display `@oneToMany` in rest (i do exactely the example in documentation [here](https://micro-framework.readthedocs.io/en/latest/model/models.html) but nothing is displayed)

This is a bug on the last version (2.3.11), see https://github.com/phpMv/ubiquity/issues/145
