### ISSUE TITLE
[Router] Router should return 404 pages for missing routes

### ISSUE THREAD

**Issue by ryanlath** [phpMv/ubiquity#149]
Router should return 404 pages for missing routes.  I've tried looking the through the docs, but couldn't find anything.

### Steps
Go to a route that doesn't exist. 
 e.g. https://mysite/pagethatdoesntexist or https://ubiquity.kobject.net/dsfgadsf

### Expected Result
404 page, ideally one that calls a view so the developer can override/integrate with site design

### Actual Result
blank page

### Versions
- Ubiquity framework 2.3.5
- php 7.2
- Linux

**Comment by jcheron** [comment]
If you use routing (via annotations), you can handle error 404 this way:
```php
class FooController extends ControllerBase {
    ...

    /**
     * @route("{url}","priority"=>-1000)
     */
    public function route404($url) {
        UResponse::setResponseCode(404);
        echo "Page {$url} not found!";
    }
}
```
and if you still want to preserve some controllers (the Admin part for example), you must add the requirements attribute, which allows to specify a regex:
```
   /**
     * @route("{url}","priority"=>-1000,"requirements"=>["url"=>"(?!(a|A)dmin).*?"])
     */
```
Be careful, this route disables the default routing (controller+action)


On the other hand, if you don't use the routes, and you use the controller+action system (default routing)
the current implementation is unsatisfactory and needs to be redesigned (an unfound route generates a debug mode exception, and just logs without the debug)

I am thinking of adding in the configuration the possibility to define the action to be performed in case of 404, valid whatever the routing system used.

**Comment by jcheron** [comment]
see update in [doc](https://micro-framework.readthedocs.io/en/latest/controller/router.html#error-management)
