### ISSUE TITLE
Ubiquity action DefaultController.sayHello -p=name -r=to/{name}/ create incomplete route

### ISSUE THREAD

**Issue by pars0097** [phpMv/ubiquity#150]
Ubiquity action DefaultController.sayHello -p=name -r=to/{name}/
output:
```
	/**
	 *@route("to/") **=>based on documantion  it should be @route("to/{name}")**
	 */
	public function sayHello($name){
	}
```

**Comment by jcheron** [comment]
I can' t see this problem with the following versions:
 - PHP 7.4.4
 - Ubiquity devtools (1.2.17)
 - Ubiquity webtools (2.3.12)
 - Ubiquity 2.3.12

The command:
```bash
Ubiquity action DefaultController.sayHello -p=name -r=to/{name}/
```
generates a `/to/{name}/` route:
```php
	/**
	 *@route("to/{name}/")
	 */
	public function sayHello($name){
		
	}
```
this could happen if there was an extra space in the route entered in the command: ` -r=to/ {name}/`

Why not use the [bug report template](https://github.com/phpMv/ubiquity/issues/new?assignees=jcheron&labels=&template=bug_report.md&title=%5Bpart%5D+Element+should+do+X) provided for this purpose, which allows you to report an issue correctly, specifying the versions used?

**Comment by jcheron** [comment]
Hi @pars0097 ,
is it ok now?
