### ISSUE TITLE
[ORM] OrmUtils->isNotNullOrNullAccepted() should return true if the value is set to empty string.

### ISSUE THREAD

**Issue by churow** [phpMv/ubiquity#153]
### Steps
1. Set a model's property not nullable:
```
/**
 * @column("name"=>"emp_password","nullable"=>false,"dbType"=>"char(41)")
 * @validator("length","constraints"=>array("max"=>41,"notNull"=>true))
**/
private $emp_password;
```

2. Set an instance property to empty string.
```
$emp = new Emp();
$emp->setEmp_password('');
DAO::save($emp);
```

3. Got an error.
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'emp_password' doesn't have a default value in .../vendor/phpmv/ubiquity/src/Ubiquity/orm/traits/DAOUpdatesTrait.php: 146

### Expected Result
OrmUtils->isNotNullOrNullAccepted() returns true.
It would be enough to check isset($v) only like:
`$notNull = isset ( $v );`
Empty string is not null.

### Actual Result
OrmUtils->isNotNullOrNullAccepted() returns false.
It current checks like:
`$notNull = (isset ( $v ) && NULL !== $v && '' !== $v);`

### Versions
- Ubiquity framework 2.3.12
- Ubiquity devtools 1.2.17
- php 7.4.11
- OS Debian 10.6 (as Docker image php:7.4-fpm)

**Comment by jcheron** [comment]
Hi @churow ,
Validation is not integrated into the **DAO** `save` method, you have to do it explicitly:
```php
	$emp = new Emp();
	$emp->setEmp_password('');
	$violations = ValidatorsManager::validate($emp);
	if (\count($violations) == 0) {
		DAO::save($user);
	} else {
		var_dump($violations);
	}
```
The array of **violations** should contain at least this **ConstraintViolation**:

```
    object(Ubiquity\contents\validation\validators\ConstraintViolation)[53]
      protected 'message' => string 'This value should not be null' (length=29)
      protected 'value' => ''
      protected 'member' => string 'em_password' (length=11)
      protected 'validatorType' => string 'Ubiquity\contents\validation\validators\multiples\LengthValidator' (length=65)
      protected 'severity' => null
```

But it might be advisable to add a **validateAndSave** method in the **DAO** class...

**Comment by churow** [comment]
Hi @jcheron ,
Thank you for kind explanation of validation.

What I wanted to ask was not about validation before save, but the save (and the validation) itself.

The DB column which is defined "NOT NULL" can have empty string.
But the save (and the validation) refuses empty string, regarding it as null.

How can I make a DB column which is "NOT NULL" to have empty string?

**Comment by jcheron** [comment]
For me, if you accept an empty string, you have to accept the null value.
When entering in a form, how do you distinguish a null value from an empty string? In both cases, the user has not entered anything.

So the declaration of your password should be:
```php
/**
 * @column("name"=>"emp_password","nullable"=>true,"dbType"=>"char(41)")
 * @validator("length","constraints"=>array("max"=>41))
**/
private $emp_password;
```

**Comment by churow** [comment]
I guess I have to alter the column type for Ubiquity.

However, these two cases are different:
```
INSERT INTO emp (emp_name, emp_email, emp_password) VALUES ('Name', 'id@email.com', '');
// ... $emp->setEmp_password(''); DAO::save($emp);
```
```
INSERT INTO emp (emp_name, emp_email) VALUES ('Name', 'id@email.com');
// ... DAO::save($emp);
```
DB will accept the first case, but will refuse the second one, if emp_password is NOT NULL.

**Comment by jcheron** [comment]
Why not set a default value for the password field to an empty string in this case (in the DB)?

**Comment by churow** [comment]
Yes, I must do that too.

**Comment by jcheron** [comment]
So to sum up:

- Either you accept null values on the framework side.
- Either you reject them, but in this case you have to set a default value for the field in the database.

Do you think there's an inconsistency somewhere?

**Comment by churow** [comment]
As for DB design, it can be summed up like this:
|            | NOT NULL | NULLable |
| ---------- | -------- | ---------|
| Default    | OK       | OK       |
| No default | Not OK   | OK       |
It is necessary to define a default value for NOT NULL columns, if it is not inteded.

As for the framework, it would be better to inform developers of the fact that if they set a NOT NULL column to empty string, the column will be omitted from the query, which is the same as omitting the setter statement in the first place.
