### ISSUE TITLE
Disable Admin Panel on Deploying : question

### ISSUE THREAD

**Issue by teachtocode** [phpMv/ubiquity#154]
Hi , I am very happy with your framework , my doubt is how can i disable Admin panel ui(web tools) , i needed the admin panel in  my local development but how can i disable when i am going to deploy it.

**Comment by jcheron** [comment]
Hi @teachtocode 
There are several ways to secure the admin part:
### Disabling for all non-local URLs
By over-defining the `isValid` method of the `Admin` controller:
```php
class Admin extends UbiquityMyAdminBaseController {

	public function isValid($action) {
		return \in_array($_SERVER['REMOTE_ADDR'], [
			'127.0.0.1',
			':1'
		]);
	}
}
```
### Disabling the default routing system
In this case, the default routing system (controller+action) is disabled and only explicitly defined routes are accessible;
```php
	/**
	 * @route("{url}","priority"=>-1000)
	 */
	public function p404($url) {
		echo "The page `$url` you are loocking for doesn't exist!";
	}
```
### Deleting app/controllers/Admin.php
Remove the Admin controller, which is just a controller inheriting from `UbiquityMyAdminBaseController`

**Comment by teachtocode** [comment]
thank you very much bro for the support , you guys are awesome , hope to see new features coming in the future vresions.

Thank you great work.
