### ISSUE TITLE
[Annotations] PHP8 with mindplay annotations

### ISSUE THREAD

**Issue by brunobl** [phpMv/ubiquity#162]
### Steps
- Using web-admin
- setting up database
- clicking on creating models

### Expected Result
http://127.0.0.1:8090/Admin shouldn't result in exception

### Actual Result
Message : Uncaught mindplay\annotations\AnnotationException: The class 'Ubiquity\annotations\TableAnnotation' must have exactly one UsageAnnotation in /Users/bruno/ubi/firstProject/vendor/mindplay/annotations/src/annotations/AnnotationManager.php:467 Stack trace: #0 /Users/bruno/ubi/firstProject/vendor/mindplay/annotations/src/annotations/AnnotationManager.php(388): mindplay\annotations\AnnotationManager->getUsage('Ubiquity\\annota...') #1 /Users/bruno/ubi/firstProject/vendor/mindplay/annotations/src/annotations/AnnotationManager.php(343): mindplay\annotations\AnnotationManager->applyConstraints(Array, 'class') #2 /Users/bruno/ubi/firstProject/vendor/mindplay/annotations/src/annotations/AnnotationManager.php(515): mindplay\annotations\AnnotationManager->getAnnotations('models\\Country') #3 /Users/bruno/ubi/firstProject/vendor/mindplay/annotations/src/annotations/Annotations.php(70): mindplay\annotations\AnnotationManager->getClassAnnotations('models\\Country', '@database') #4 /Users/bruno/ubi/firstProject/vendor/phpmv/ubiquity/src/Ubiquity/orm/parser/Reflexion.php(77): mindplay\annotations\Annotations::ofClass('models\\Country', '@database') #5 /Users/bruno/ubi/firstProject/vendor/phpmv/ubiquity/src/Ubiquity/cache/traits/ModelsCacheTrait.php(130): Ubiquity\orm\parser\Reflexion::getAnnotationClass('models\\Country', '@database') #6 /Users/bruno/ubi/firstProject/vendor/phpmv/ubiquity-webtools/src/Ubiquity/controllers/admin/traits/CheckTrait.php(144): Ubiquity\cache\CacheManager::getModels(Array, true, 'default') #7 /Users/bruno/ubi/firstProject/vendor/phpmv/ubiquity-webtools/src/Ubiquity/controllers/admin/traits/CheckTrait.php(99): Ubiquity\controllers\admin\UbiquityMyAdminBaseController->checkModels(Array) #8 /Users/bruno/ubi/firstProject/vendor/phpmv/ubiquity-webtools/src/Ubiquity/controllers/admin/traits/CheckTrait.php(74): Ubiquity\controllers\admin\UbiquityMyAdminBaseController->_modelCheckOneNiveau('Models') #9 /Users/bruno/ubi/firstProject/vendor/phpmv/ubiquity-webtools/src/Ubiquity/controllers/admin/traits/ModelsConfigTrait.php(93): Ubiquity\controllers\admin\UbiquityMyAdminBaseController->_checkStep() #10 /Users/bruno/ubi/firstProject/vendor/phpmv/ubiquity-webtools/src/Ubiquity/controllers/admin/traits/ModelsTrait.php(324): Ubiquity\controllers\admin\UbiquityMyAdminBaseController->_getModelsStepper() #11 /Users/bruno/ubi/firstProject/vendor/phpmv/ubiquity-webtools/src/Ubiquity/controllers/admin/UbiquityMyAdminBaseController.php(516): Ubiquity\controllers\admin\UbiquityMyAdminBaseController->_modelDatabase(true, false, 'default') #12 /Users/bruno/ubi/firstProject/vendor/phpmv/ubiquity-webtools/src/Ubiquity/controllers/admin/traits/CheckTrait.php(63): Ubiquity\controllers\admin\UbiquityMyAdminBaseController->models(true) #13 /Users/bruno/ubi/firstProject/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php(145): Ubiquity\controllers\admin\UbiquityMyAdminBaseController->_createModels() #14 /Users/bruno/ubi/firstProject/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php(106): Ubiquity\controllers\Startup::runAction(Array, true, true) #15 /Users/bruno/ubi/firstProject/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php(66): Ubiquity\controllers\Startup::forward('Admin/_createMo...') #16 /Users/bruno/ubi/firstProject/.ubiquity/_index.php(18): Ubiquity\controllers\Startup::run(Array) #17 /Users/bruno/ubi/firstProject/.ubiquity/.htrouter.php(5): include_once('/Users/bruno/ub...') #18 {main} thrown

### Versions
- Ubiquity framework: dev-master
- php 8.0
- MacOS

**Comment by jcheron** [comment]
This is a problem of compatibility of mindplay annotations with php8. I did a [PR solving this problem](https://github.com/php-annotations/php-annotations/pull/132) a fortnight ago, waiting for @mindplay-dk 's approval.

The next version of Ubiquity (2.3.14 currently on the php8-annotations branch) will propose php8 attributes by default if php8 is present.

In the meantime, with the 2.3.13,
you can add this fix to your composer.json file:
```json
	"repositories": [
		{
			"type": "vcs",
			"url": "https://github.com/phpMv/php-annotations"
		}
	],
	"require-dev" : {
		...
		"mindplay/annotations": "dev-php8-fix as 1.3.2",
	},
```

**Comment by brunobl** [comment]
I had to create a new project from scratch to solve the issue, as it seems my original test project was somewhat corrupted because of this mindplay/annotation issue. But the fix works. Thanks a lot.

**Comment by jcheron** [comment]
In this case, the contents of the `app/cache` folder must be deleted.

**Comment by jcheron** [comment]
see https://github.com/php-annotations/php-annotations/pull/132
