### ISSUE TITLE
Bulk flush needs to empty bulks array

### ISSUE THREAD

**Issue by churow** [phpMv/ubiquity#166]
Bulk flush like flushUpdates() flushes each bulk, but leaves the bulks array without any more handling.
```
// from Ubiquity\orm\traits\DAOBulkUpdatesTrait
public static function flushUpdates(): void {
	$bulks = self::$bulks ['update'];
	foreach ( $bulks as $bulk ) {
		$bulk->flush ();
	}
}
```
When bulk queries happen again, the still remaining previous bulks cause errors.
It would be nice if the array is immediately emptied after flush or if there is some method to empty the bulks array.

**Comment by jcheron** [comment]
Hi @churow 
Thank you for this report.

There is indeed a problem, but not quite where you indicate.
The Bulks are well emptied, and remain instantiated (for possible re-use).
But the flush method doesn't check that there are no instances to flush, which causes a bug for a next call.

Note that in case of an exception in an update, the instances are not removed from the bulk.

So I will also add to the first problem resolution, the possibility to explicitly empty a bulk, as you said.
