### ISSUE TITLE
[DAO] Element should do not fail with error when foreign keys are NULL in postgresql

### ISSUE THREAD

**Issue by andrewvh619** [phpMv/ubiquity#171]
Hello, 
Having forced

 FK is not something that will work in every real-world case. 

$acs=DAO::getAll("models\Test"); 

### Steps
Create a table in POSTGRESQL with a nullable FK

CREATE TABLE test_group (
    id SERIAL PRIMARY KEY,
    name text
);

CREATE TABLE test (
    id SERIAL PRIMARY KEY,
    name text,
    test_group_id integer REFERENCES test_group(id)
);

Add one or more rows to test table. 

Then run:

$acs=DAO::getAll("models\Test");

### Expected Result

Empty FK result [] rather in the RS rather than an error?

### Actual Result
         
PHP Fatal error:  Uncaught PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type integer: ""

### Versions
I upgrade trying to resolve this, so I am running 

"php": ">=7.4",
"twig\/twig": "^3.0",
"phpmv\/ubiquity": "^2.4.3",
"phpmv\/php-mv-ui": "2.4.x-dev",
"phpmv/ubiquity-workerman": "^0.0.2"

https://www.loom.com/share/aa9ce4e4359e41c68118c9153c83f242?from_recorder=1

**Comment by jcheron** [comment]
Thanks @andrewvonhoesslin , it's quite strange... 
I'm going to watch this.

**Comment by jcheron** [comment]
@andrewvonhoesslin 
I think it's okay
This rather delicate postgreSQL behavior has highlighted an inconsistency: no need to search for the parent record when the foreign key is null ;-)

**Comment by andrewvh619** [comment]
Thank you
