### ISSUE TITLE
Crud controller admin with fk causes error with PostgreSQL

### ISSUE THREAD

**Issue by andrewvh619** [phpMv/ubiquity#172]
### Steps
If you generate a controller via the CRUD admin in POSTGRESQL with foreign keys the type is declared as an integer VS text relationship. 

To fix this I have added ::integer on the right join =_tmp._id attribute. 

E.g. =_tmp._id:::integer 

vendor/phpmv/ubiquity/src/Ubiquity/orm/parse/ConditionParser.php
vendor/phpmv/ubiquity/src/Ubiquity/orm/parse/ManyToManyParser.php

![Screenshot at Mar 13 12-47-59](https://user-images.githubusercontent.com/58555916/111024872-6422d880-83fa-11eb-80f4-3158f7b48983.png)
![Screenshot at Mar 13 12-47-47](https://user-images.githubusercontent.com/58555916/111024875-67b65f80-83fa-11eb-9d41-3e0b77cb6ca7.png)

https://www.loom.com/share/0e6822860c2548f2b71fee201ac12ca6

### Versions
- MAC OS
- Docker
- php 7.4 

"phpmv/ubiquity": "dev-master"

**Comment by jcheron** [comment]
The `CAST(_tmp._id as integer)` fix looks more normalized and less PostgreSQL specific than `_tmp._id::integer`

**Comment by andrewvh619** [comment]
Yes, it does and is, thanks.
