### ISSUE TITLE
Pagination does not work, conflicting class

### ISSUE THREAD

**Issue by andrewvh619** [phpMv/ubiquity#173]
**ISSUE**

The crud controller is causing errors on pagination as there are conflicting name space issue in CRUDController.

Error
Uncaught Error: Class 'Ubiquity\controllers\rest\ResponseFormatter' not found in /app/vendor/phpmv/ubiquity/src/Ubiquity/controllers/crud/CRUDController.php:109

Should be Ubiquity\controllers\rest\formatters\ResponseFormatter

https://www.loom.com/share/b2622ef6df6947b5b0ed420704c72975

![Screenshot at Mar 13 12-56-21](https://user-images.githubusercontent.com/58555916/111025141-d21bcf80-83fb-11eb-94ac-9f55f4025ce0.png)

**Using:** 
master-dev 
docker 
mac
postgresql

**Comment by jcheron** [comment]
Hi @andrewvh619 ,
Thank you for this report.
You know you can submit a PR, especially if you have found the problem and identified the solution to solve it.
Increasing the number of contributors is also a way to improve the credibility of a framework.

**Comment by jcheron** [comment]
In this case, there is not only an import problem.
The dependency between the CRUD part and the Rest part must also be removed.

**Comment by andrewvh619** [comment]
Thank you, this is the first project that I will be contributing to so excuse my ignorance, what is a PR?
I am very excited about this project.

**Comment by jcheron** [comment]
A PR is a github Pull Request, which is what allows you to make a proposal for a code correction.

To summarize, if you have a correction to make or if you want to propose an improvement :
You:
- fork the project on your github account
- clone the fork to work on it locally.
- create a new branch correctly named
- work on the code to modify or improve
- commit and push your work
- do a Pull Request (PR)

Your PR is then reviewed, possibly accepted as is, or you are asked to fix it.

see https://github.com/phpMv/ubiquity/blob/master/CONTRIBUTING.md

**Comment by andrewvh619** [comment]
I will contribute in this manner. Thank you very much.
