### ISSUE TITLE
Saving Booleans Not Working when false in PostGresql

### ISSUE THREAD

**Issue by andrewvh619** [phpMv/ubiquity#174]
Hi Again,

Saving booleans are not saving if sent to false on the CRUD or using the DOA. 

I have not been able to fix this so I have not submitted a PR.

Example for simplicity:

CREATE TABLE company_test (
    id SERIAL PRIMARY KEY,
    name character varying NOT NULL,
    code character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    active boolean DEFAULT true
    );

The following does not work:

$company_test = new Company_test();
$company_test->setCode("ABCDFEG") ;
$company_test->setName("Test 1") ;
$company_test->setActive(false) ;
var_dump(DAO::save($company_test))  ;

With error:

[Sun Mar 14 03:47:02 2021] PHP Fatal error:  Uncaught PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type boolean: "" in /app/app1/vendor/phpmv/ubiquity/src/Ubiquity/orm/traits/DAOUpdatesTrait.php:146
Stack trace:

On the CRUD the status is actually saved incorrectly, when the submission is succeeding.

![Screenshot at Mar 14 07-50-17](https://user-images.githubusercontent.com/58555916/111056662-460cb500-849a-11eb-8cb8-edc6a48bde5c.png)

https://www.loom.com/share/dacc5f196ab1492b955dcdcef746e2a1

Issues
1. On CRUD system, setting Boolean field to true in postgresql, saves as false in the db, if you set the field to false the object will not save
2. On DOA, saving an object errors if one sets a boolean field to false.  
  
### Versions
"phpmv/ubiquity": "dev-master",
"phpmv/php-mv-ui": "dev-master",
- php 7.4
- MAC
- Postgresql

**Comment by andrewvh619** [comment]
Just an update with the logs, the data looks correct here:

{"message":"INSERT INTO \"company_test\" (\"name\",\"code\",\"active\") VALUES(:name,:code,:active)","context":{"context":"DAOUpdates","part":"insert","extra":null},"level":200,"level_name":"INFO","channel":"s604c920891e78","datetime":"2021-03-14T04:36:51.562339+00:00","extra":{}}
{"message":"{\"name\":\"Test 11\",\"code\":\"ABC\",\"active\":false}","context":{"context":"DAOUpdates","part":"Key and values","extra":null},"level":200,"level_name":"INFO","channel":"s604c920891e78","datetime":"2021-03-14T04:36:51.563319+00:00","extra":{}}
{"message":"SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type boolean: \"\"","context":{"context":"DAOUpdates","part":"insert","extra":null},"level":300,"level_name":"WARNING","channel":"s604c920891e78","datetime":"2021-03-14T04:36:51.566114+00:00","extra":{}}

**Comment by jcheron** [comment]
With the DAO class, for the false, you have to use the integer 0 or the string "false", it's inconsistent I agree, but the problem does not come from Ubiquity.
```php
$company_test = new Company_test();
$company_test->setCode("ABCDFEG") ;
$company_test->setName("Test 1") ;
$company_test->setActive(0) ;// or $company_test->setActive('false') ;
var_dump(DAO::save($company_test)) ;
```

No problem with the true.


For the Crud part, there is indeed a Bug, the boolean type is only tested for Mysql, we have to change that, and refer to more general types (PHP types)

https://github.com/phpMv/ubiquity/blob/04c5754468f0fb971aa3dd4b4a50302f7533aad6/src/Ubiquity/controllers/crud/CRUDHelper.php#L72

**Comment by andrewvh619** [comment]
$company_test->setActive(0), this is workable and type casting in the model works, so great.

Also, fixing if (in_array($type, ["tinyint(1)", "boolean"] )) {  works perfectly too. I will do the PR. 

I have done something similar to URequest::setPostValuesToObject($object) before, and really like this methoed, I will see what I can do here too but this is an odd one as the checkbox value is not being posted as expected for the FE.

**Comment by andrewvh619** [comment]
URequest::setPostValuesToObject($object) is easily fixable and not a Ubiquity issue.

The following resolves it:
$_POST['active'] = (!isset($_POST['active'])) ? 0 : 1;
URequest::setPostValuesToObject($company);
