### ISSUE TITLE
[RFC] DateTime fields be DateTime objects

### ISSUE THREAD

**Issue by gildonei** [phpMv/ubiquity#18]
## Summary

All the database fields mapped as Date / DateTime / Timestamp be converted to PHP DateTime object and all *set* also require this fields to be a DateTime object

## Motivation

This will take advantage of Localizations, native PHP functions and padronize the variables

## Compatibility with Ubiquity's philosophy 

Indicate compatibility or improvements in:
- performances
- ease of use
- standards and padronization

## Expected results

A clear and precise use of datetime database fields.

**Comment by jcheron** [comment]
The dates are indeed difficult to manage, between those which come from the database, those which must be displayed, and those which must be persistent...

But I doubt that the use of the DateTime class of php facilitates these tasks ...
Systematic conversion of dates will have a cost on performance.

These basic operations should be performed to test:
- Database dateTime -> DateTime object
- DateTime object -> Html5 input (datetime-local)
- DateTime object -> Database Time

To see if they can apply to all situations.

**Comment by gildonei** [comment]
I think that use of php DateTime class could be used because It will standartize the Date/DateTime params, like Declared arrays or object parameters, so always we got a Date property or param, users will know they can use all php DateTime functions, to format output, add, sub, diff, etc.

In the Form helper that generates datetime-local input you used a default value date('Y-m-d\TH:i:s', strtotime($var)), to output ISO Date, when could be a simple $obj->format output. 

Plus, DateTime gives support for Timezone operations that could be used with Html datetime-local fields

**Comment by lesichkovm** [comment]
DateTime fields should not be "magically" converted to object.

If anyone needs it specifically it too easy to be set using the getter and setter methods.

Overall performance should not be sacrificed, because of someone's "perceived ease of use".

**Comment by jcheron** [comment]
There are intermediate solutions that could already be satisfactory:
Use DAO events to change dates when loading objects:
```php
EventsManager::addListener(DAOEvents::GET_ONE, function($instance,$classname){
	if($classname==\models\User::class){
		$instance->setDateCo(new \DateTime($instance->getDateCo()));
	}
});
```
or

Use a Normalizer to change dates to PHP DateTime:

**Creation:**
```php
class UserNormalizer implements NormalizerInterface{
	public function supportsNormalization($data) {
		return $data instanceof User;
	}

	public function normalize($object) {
		return['name'=>$object->getName(),'url'=>$object->getUrl(),'dateCo'=>(new \DateTime($object->getDateCo()))->format('Y-m-d\TH:i:s')];
	}
}
```

**Registering UserNormalizer** in `app/config/services.php`
```php
NormalizersManager::registerClass(User::class, UserNormalizer::class);
```

**Using UserNormalizer** in an action:
```php
	public function displayUsers(){
		$users=DAO::getAll(User::class);
		print_r(NormalizersManager::normalizeArray_($users));
	}
```
All these operations have a cost, but are the user's choice

**Comment by gildonei** [comment]
> perceived ease of use

It is not about easy of use, It is about standatize variable types. 
In my opinion, if you are work with Date variables you must use Date objects. You can't work with dates as string in Javascript, Java or other well typed language, you must use properly variable type.
It's not because PHP allows you to "work" with dates as string you should do that, but it is only my opinion.

All major frameworks, are adopting or starting to adopt this patter, so, I think Ubiquity should do this to.

All the recent literature about Design Patterns and code standards highly recommend this.

**Comment by gildonei** [comment]
I understand the relation Performance X Really needed functionality, but I still think It should be considered to be implemented as a default behavior. I think this is valid lost of performance in exchange of a better framework Design.

So, it is up to you @jcheron to decide, implement or not. I gave all my "pov" why Ubiquity should do that. Maybe it could be an item to be setted at config file like "use date as object (y/n)" so Ubiquity could use your DAO Listener suggestion to convert in objects and developers could easily choose wich one use.

**Comment by lesichkovm** [comment]
"All major frameworks" are a big disappointment. Besides there is no common understanding what a DateTime object should be. Laravel for instace has gone with Carbon and its a terrible decission, as now there is a further dependency on Carbon.

I personally prefer to get back exacty what I have placed in the database - timestamp, date/time/datetime string.

**Comment by gildonei** [comment]
@lesichkovm I agree with you about use of Carbon or any other external lib. I think the frameworks should be more PHP native as possible. You don't need to re-write a DateTime object with external libs when PHP native DateTime can do almost all you need

**Comment by lesichkovm** [comment]
Probably the best would be to add a separate section in the documentation advising users how they can do this as @jcheron had described above, if they want it. But also advising them what would be the ramifications in terms of affecting speed.

**Comment by jcheron** [comment]
I implemented the DateTime functionality to do some benchmarking, doing it in 2 different ways:
- Added an event on setters calling + transformation to DateTime => version **Ubiquity-2.1.0-evt-dt**
- Direct transformation into DateTime => version **Ubiquity-2.1.0-datetime**

The **Ubiquity-2.1.0-event** version allows to measure the impact of only adding the event on setters.

Here are the results in terms of throughput (more is better):

![throughput ](https://static.kobject.net/ubiquity/images/github/tmp/throughput.png)

In terms of execution time (less is better):
![throughput ](https://static.kobject.net/ubiquity/images/github/tmp/speed.png)

I still perform these tests on a reference database described [here](https://orm-benchmarks.kobject.net/) (loading 6000 objects)
The call of the setters is the most repeated operation. The addition of the slightest piece of code has a considerable impact here.
The transformation of text into DateTime is not annodine:
- it is necessary to check if the value is a non- null datetime
- and then possibly instantiate a PHP DateTime object

The DateTime php class has a major drawback:
It does not have a **__toString** method, so additional processing should be provided for its use. This lack is a problem in the case of a REST service, where we would prefer to have an unchanged datetime, to allow formatting to be done on the client side.

In general, I think that any systematic transformation of data after it has been loaded from the database is a bad thing, which should not be introduced in the framework.

Nor will I leave the user the choice to do it himself, leaving the event triggered on the call of the setters, which was introduced for the tests.

**Comment by gildonei** [comment]
OK, sounds good to me let it pre-configured in a way that users can decide to use or not without have to write code.

**Comment by jcheron** [comment]
I have found a solution that does not degrade performance too much: with [transformers](https://micro-framework.readthedocs.io/en/latest/contents/transformers.html), available in the next release.

### The principle:
- we can use the `@transformer` annotation on the members of an entity.

```php
class User{
    /**
     * @transformer("datetime")
     */
    private $creationDate;

    //getters and setters
}
```
We start the module in `app/config/services.php':
```php
\Ubiquity\contents\transformation\TransformersManager::startProd();
```
On loading, creationDate is converted to a php DateTime object:
```php
$user=DAO::getOne(User::class,1);
echo $user->getDateCreation()->format('Y-m-d H:i:s');
```
It can also be used to be displayed in a view:
```php
DAO::$transformerOp='toView';
$user=DAO::getOne(User::class,1);
```
or in a form (to be used with datetime input):
```php
DAO::$transformerOp='toForm';
$user=DAO::getOne(User::class,1);
```
For performance, `DateTime` instantiation is always expensive, but acceptable if it is not systematic.
This is the `ubiquity-2.1-transf` serie on the graph:

![image](https://user-images.githubusercontent.com/2511052/55857377-4218df80-5b6d-11e9-9654-726c83b16787.png)

**Comment by gildonei** [comment]
Great news @jcheron preparing all this benchmarks and upgrading the framework. I Believe now we have an acceptable solution. Easy of use and low performance cost.

**Comment by Sinevia** [comment]
@jcheron @gildonei The way I see it this single feature causes the framework to be 3-4 times slower. This is of massive impact.
Otherwise very creative soution @jcheron . Well done

**Comment by jcheron** [comment]
the graphic representation is misleading....
- `Ubiquity-2.1.0` -> loading in 380 ms
- `Ubiquity-2.1.0-transf` (dateTime transformer) -> loading in 448 ms

That is a difference of 68 ms (18% more) for the instantiation of 2100 dateTime objects, and the loading of 6000 instances.
It's really not much, and it's the user who chooses.

With the first version (`Ubiquity-2.1.0-datetime`), we went to 716 ms, and that was indeed unacceptable.

**Comment by jcheron** [comment]
`@transformer` added in [`Ubiquity 2.1.1`](https://github.com/phpMv/ubiquity/releases/tag/v2.1.1)
