### ISSUE TITLE
[REST] Class 'controllers\\Exception' not found on rest connect

### ISSUE THREAD

**Issue by Alt0car** [phpMv/ubiquity#181]
### Steps
Create empty project with rest enabled
Create simple User entity and create basic rest controller for this one

Renaming default route connect `/rest/users/connect` to `/rest/users/auth`

My connect method is like your example :
```
    /**
     * This method simulate a connection.
     *
     * @route("/auth","methods"=>["post"],"priority"=>3000)
     * @throws DAOException
     */
    public function connect()
    {
        if (!URequest::isCrossSite() && URequest::isPost()) {
                $userEmail = URequest::post("email");
                $user      = DAO::getOne(User::class, 'email= ?', false, [$userEmail]);
                if (null !== $user) {
                    $tokenInfos = $this->server->connect();
                    USession::set($tokenInfos['access_token'], $user);
                    $tokenInfos['user'] = $user;
                    echo $this->_format($tokenInfos);

                    return;
                }
        }
        throw new Exception('Unauthorized', 401);
    }
```

My postman resquest was : 
```
POST /rest/users/auth HTTP/1.1
Host: ubiquity.local
Content-Type: application/x-www-form-urlencoded
Cookie: ...WoAMCftYKuDQ_fc; factoryUbiquity=...18956ada0072c8e9
Content-Length: 17

email=test%40test
```
![postman](https://user-images.githubusercontent.com/5878657/119258331-7e7eec80-bbc9-11eb-91a9-2e29ec75b5cb.PNG)

### Actual Result
On webtools, this request perform well
But when i'm triying to reproduce this one into postman, all time response was `Class 'controllers\\Exception' not found`

### Expected Result
same as here
![Screenshot_2021-05-23 Administration](https://user-images.githubusercontent.com/5878657/119258363-90608f80-bbc9-11eb-9150-5ed61857674b.png)

### Versions
- Ubiquity framework 2.4.4
- Ubiquity devtools 1.2.28
- php 7.4
- OS docker debian based image

**Comment by jcheron** [comment]
Can you try ?
```php
        throw new \Exception('Unauthorized', 401);
```
the back-slash should allow php not to look for Exception in the active namespace.

**Comment by Alt0car** [comment]
I don't think that was the problem because on top of my file i declare : `use Exception;` so qualifier is not necessary.

I've found the problem, actually 401 was return into response but not into http_response_code ( was 200 ).
I focused to http_response_code but the real problem was into Postman, i didn't defined the Referer and this line `!URequest::isCrossSite()` blocked me.

So if i need more verbose error like _method not allowed_ when i'm trying to GET on POST route against `The controller controllers\rest doesn't exist!` and set the correct http_response_code i have to do my own Exception class I guess or Ubiquity provide this possiblity already ?

**Comment by jcheron** [comment]
The way the router works, it can just answer in a binary way that the route exists, or that it does not exist.
Optimization choices have determined this functioning.
So you can't get a more verbose error like _method not allowed_, since the only thing the router knows is that the route doesn't exist.
You could get around this by using the `@route` annotation (which authorizes all Http methods), and then test the method yourself. But I don't think this is a good choice.

**Comment by jcheron** [comment]
I made an experiment to modify the router.

You can get a more accurate response code with `Router::getStatusCode()` which returns 200, 404 or 405 (Method not allowed).

With a Rest controller, you can use this by overriding the `errorHandler` method:

```php
	public function _errorHandler($e) {
		$this->_setResponseCode ( Router::getRouterStatus() );
		echo $this->_getResponseFormatter ()->formatException ( $e );
	}
```

To try by doing :
```
composer require phpmv/ubiquity:dev-master
```

**Comment by Alt0car** [comment]
Hmm i see 
btw i'm doing override more like this 
```php
$this->_setResponseCode ( $e->getCode() );
```
but actually the router can't respond 405 i think, because in file `routes.rest.cache.php` ,routes generated was only created matched the annotation's array methods, and don't check if the route exist with another method.

_This reflection comes out of the initial ticket for once. Tell me if you would like me to split the request._

**Comment by jcheron** [comment]
The router update on dev-master still uses the same, unmodified cache system.
So the `Router::getStatusCode()` should return the right value...

> This reflection comes out of the initial ticket for once. Tell me if you would like me to split the request.

we started out weird, so there's no need
