### ISSUE TITLE
Rest Controller with no route

### ISSUE THREAD

**Issue by ashokkumar88** [phpMv/ubiquity#184]
### Steps
I created a Rest controller with a Resource. The path was "/rest/audios". But it is showing error `controller rest not found` when i navigate to "http://127.0.0.1:8090/rest/audios"
### Versions
- Ubiquity framework 2.4.6
- Ubiquity devtools 1.3.3
- php 8.0.10
- OS - WINDOWS

**Comment by jcheron** [comment]
Hi @ashokkumar88 ,
Did you modify the `app/config/services.php` file
to modify the line:
```php
Router::startAll();
```

**Comment by ashokkumar88** [comment]
Yes @jcheron. I had modified that also.

**Comment by ashokkumar88** [comment]
![Capture](https://user-images.githubusercontent.com/11060139/132546732-5f93c9a2-2ce8-4276-b2db-c199eaf347a8.PNG)
Here is the screenshot of the error.

**Comment by jcheron** [comment]
Has the cache been reset?
```bash
Ubiquity init-cache
```

**Comment by ashokkumar88** [comment]
Yes.

**Comment by jcheron** [comment]
What does this command display?
```bash
Ubiquity info:routes -t=rest
```

**Comment by ashokkumar88** [comment]
![ubi](https://user-images.githubusercontent.com/11060139/132549642-7fa31744-580c-4f9b-bd19-c14dacb6bc7f.PNG)

**Comment by ashokkumar88** [comment]
I created a fresh project and this time I used only `console-tools` and now no more "controller not exists error". Navigating to the route "/rest/audios/468" showing JSON data. But there are some unwanted data at the beginning of the JSON.  Pasted below.

```
<script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] +
				':35729/livereload.js?snipver=1"></' + 'script>')</script>
```

**Comment by jcheron** [comment]
Ok, the Rest routes are well included.
Can you show me the `app/config/services.php` file ?

**Comment by jcheron** [comment]
> I created a fresh project and this time I used only `console-tools` and now no more "controller not exists error". Navigating to the route "/rest/audios/468" showing JSON data. But there are some unwanted data at the beginning of the JSON. Pasted below.
> 
> ```
> <script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] +
> 				':35729/livereload.js?snipver=1"></' + 'script>')</script>
> ```

you can disable livereload in the `.ubiquity/_index.php` file:
```php
if (\Ubiquity\debug\LiveReload::hasLiveReload()) {
    //echo \Ubiquity\debug\LiveReload::start();
}
```
```

**Comment by ashokkumar88** [comment]
It is working fine now. Thanks @jcheron

**Comment by ashokkumar88** [comment]
`app/config/services.php`

![services](https://user-images.githubusercontent.com/11060139/132551970-ec7f21c2-4925-4d04-8520-06f0850f744d.PNG)

`composer.json`
```
{
	"name" : "phpmv/ubiquity-project",
	"description" : "Ubiquity-framework new project",
	"type" : "framework",
	"keywords" : [
		"php",
		"framework",
		"mvc",
		"orm"
	],
	"require" : {
		"php" : ">=7.4",
		"phpmv/ubiquity": "^2.3",
		"twig\/twig": "^3.0"
	},
	"license" : "Apache-2.0",
	"authors" : [{
			"name" : "Jean-Christophe HERON",
			"email" : "myaddressmail@gmail.com",
			"role" : "Lead developer"
		}
	],
	"autoload" : {
		"psr-4" : {
			"": "app/"
		}
	},
	"extra" : {
		"branch-alias" : {
			"dev-master" : "2.4.x-dev"
		}
	},
	"require-dev" : {
		"phpmv/ubiquity-devtools": "^1.3",
		"phpmv/ubiquity-webtools": "^2.4",
		"phpmv/ubiquity-codeception": "^1.0",
		"phpmv/php-mv-ui": "^2.2",
		"phpmv/ubiquity-dev": "^0.1",
		"phpmv/ubiquity-commands": "^0.0",
		"phpmv/ubiquity-debug": "^0.0",
		"phpmv/ubiquity-attributes": "^0.0.9"		
	},
	"minimum-stability": "dev",
	"prefer-stable": true,
	"scripts": {
		"post-create-project-cmd": [
			"@php vendor/phpmv/ubiquity-devtools/src/Ubiquity composer-create-project",
			"@php vendor/phpmv/ubiquity-devtools/src/Ubiquity init-cache"
		]
	}
}

```

**Comment by jcheron** [comment]
Thanks, I don't see anything strange...
Can you do a `composer update`
to know if the dependencies are up to date?

**Comment by ashokkumar88** [comment]
Seems the issue is with `web-tools`. With `console-tools` it is working fine. I will use console-tools to create the rest resources. Thanks.

**Comment by jcheron** [comment]
Have you seen a difference between the controller generated with webtools and the one generated with devtools?
Logically, it is exactly the same controller...

**Comment by ashokkumar88** [comment]
Yes the controller generated with webtools does not have any routes
included.

**Comment by jcheron** [comment]
Maybe you didn't choose the right base class then
![image](https://user-images.githubusercontent.com/2511052/132559814-2257d37e-2bfd-42e6-a673-170712fbae58.png)

**Comment by ashokkumar88** [comment]
Yes. I had selected `RestBaseController`

**Comment by jcheron** [comment]
ok, so no bug in the webtools,
but the base controller selected by default can mislead the user
