### ISSUE TITLE
Themes - AssetManager::image

### ISSUE THREAD

**Issue by gildonei** [phpMv/ubiquity#188]
## Summary
Create a method to render images using AssetManager or similar

## Motivation
Images can be inside a theme, so, should be easy render an image using the AssetManager that would resolve the correct path instead of use full path for each image

## Compatibility with Ubiquity's philosophy 
- ease of use

## Expected results
Be able to render images for specific themes.

**Comment by jcheron** [comment]
### Usage with twig for an image:
#### in `public/assets/img`
```
{{ img('img/img_name.png') }}
{{ img('@activeTheme/img/img_name.png') }}
```
#### in `public/assets/theme_name/img`
if there's an active theme:
```
{{ img('@activeTheme/img/img_name.png') }}
```

#### With some attributes
```
{{ img('@activeTheme/img/img_name.png', {alt: 'This is an alternate text', title: 'Some title in tooltip'}) }}
```
