### ISSUE TITLE
Empty DateTime in Admin -> Model -> Data -> Edit

### ISSUE THREAD

**Issue by gildonei** [phpMv/ubiquity#19]
### Steps
Access /Admin/showModel/model.ModelName -> edit a record and all DateTime fields are empty, when it should be field with it's values

### Expected Result
DateTime fields to be restored with values

### Actual Result
DateTime fields are empty

### Versions
- Ubiquity framework 
- Ubiquity devtools 1.1.7
- php 7.1.9
- OS Win10

**Comment by jcheron** [comment]
Can you put the SQL script for creating the table concerned.

**Comment by gildonei** [comment]
CREATE TABLE `pessoas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ds_nome` varchar(100) NOT NULL,
  `fl_ativo` tinyint(1) unsigned NOT NULL,
  `dh_criado` datetime NOT NULL,
  `dh_modificado` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ds_nome_idx` (`ds_nome`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

![image](https://user-images.githubusercontent.com/1370979/54692509-e4601d00-4b03-11e9-82f1-a2b1996eb4c6.png)

**Comment by jcheron** [comment]
Yes, this is a problem between the SQL DateTime and the HTML5 datetime input element.
It should be possible to act before editing to format the value and make it compatible.

**Comment by gildonei** [comment]
So, any sugestions? A callback after Find data to transform MySQL DateTime fields into Iso date times including the "T" in the date using format YYYY-mm-ddThh:ii:ss

**Comment by jcheron** [comment]
You can try with this fix https://github.com/phpMv/ubiquity/commit/37f628709db71ee1f7a160dbcdea44578484a07f
but it's not very clean

**Comment by jcheron** [comment]
Otherwise, the EventManager should be used:
```
EventsManager::addListener(DAOEvents::GET_ONE, function($object,$model){
	if($model===Connection::class){
		$v=$object->getDateCo();
		$object->setDateCo(date("Y-m-d\TH:i:s", strtotime($v)));
	}
});
```
but that's not good for performance,
this trick would be executed with each object load

**Comment by gildonei** [comment]
> You can try with this fix [37f6287](https://github.com/phpMv/ubiquity/commit/37f628709db71ee1f7a160dbcdea44578484a07f)
> but it's not very clean

`Message : Uncaught ArgumentCountError: Too few arguments to function Ubiquity\controllers\admin\viewers\ModelViewer::onGenerateFormField(), 2 passed and exactly 3 expected in C:\wamp64\www\ubiquity\themes\vendor\phpmv\ubiquity\src\Ubiquity\controllers\admin\viewers\ModelViewer.php:365 Stack trace: #0 [internal function]: Ubiquity\controllers\admin\viewers\ModelViewer->onGenerateFormField(Object(Ajax\semantic\html\collections\HtmlMessage), 0) #1 C:\wamp64\www\ubiquity\themes\vendor\phpmv\php-mv-ui\Ajax\common\html\traits\BaseHooksTrait.php(44): call_user_func_array(Array, Array) #2 C:\wamp64\www\ubiquity\themes\vendor\phpmv\php-mv-ui\Ajax\semantic\widgets\dataform\DataForm.php(95): Ajax\common\Widget->execHook('onGenerateField...', Object(Ajax\semantic\html\collections\HtmlMessage), 0) #3 C:\wamp64\www\ubiquity\themes\vendor\phpmv\php-mv-ui\Ajax\semantic\widgets\dataform\DataForm.php(64): Ajax\semantic\widgets\dataform\DataForm->_generateFields(Object(Ajax\semantic\html\collections\form\HtmlForm), Array, Array, -1, Arra
File : C:\wamp64\www\ubiquity\themes\vendor\phpmv\ubiquity\src\Ubiquity\controllers\admin\viewers\ModelViewer.php
Line : 365`

**Comment by jcheron** [comment]
oups: https://github.com/phpMv/ubiquity/commit/ee4fed53f1bb7825b949cbc3a333cbfa1a48a144

This fix is better than adding a listener with the EventsManager,
since we are in the administration part,
and we do not make any changes to make everything work properly.

**Comment by gildonei** [comment]
Updated with composer and everything works fine. Thanks! All DateTime fields were properly populated
