### ISSUE TITLE
Laravel valet error

### ISSUE THREAD

**Issue by n-osennij** [phpMv/ubiquity#192]
MacOS 12, composer latest, laravel valet with php 8.1

```
Ubiquity version

    · PHP 8.1.1
    · Ubiquity devtools (1.3.8)
    · OS: Darwin Nikitas-MacBook-Air.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64
```

create new project in my valet projects folder

`Ubiquity new quick-start`

try to open in chrome http://quick-start.test/

Warning: Undefined array key "c" in /Users/n.osennij/PhpstormProjects/quick-start/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php on line 76

`Fatal error: Uncaught TypeError: Ubiquity\controllers\Startup::forward(): Argument #1 ($url) must be of type string, null given, called in /Users/n.osennij/PhpstormProjects/quick-start/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php on line 76 and defined in /Users/n.osennij/PhpstormProjects/quick-start/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php:102 Stack trace: #0 /Users/n.osennij/PhpstormProjects/quick-start/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php(76): Ubiquity\controllers\Startup::forward(NULL) #1 /Users/n.osennij/PhpstormProjects/quick-start/public/index.php(7): Ubiquity\controllers\Startup::run(Array) #2 /Users/n.osennij/.composer/vendor/laravel/valet/server.php(234): require('/Users/n.osenni...') #3 {main} thrown in /Users/n.osennij/PhpstormProjects/quick-start/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php on line 102`

How to run it with laravel valet?

**Comment by jcheron** [comment]
See also https://github.com/phpMv/ubiquity/issues/13
