### ISSUE TITLE
[Framework::diSemantic(] undefined method Ubiquity\core\Framework::diSemantic() on config/config.php:22

### ISSUE THREAD

**Issue by gracite** [phpMv/ubiquity#196]
### Steps
Created new project
I used "Ubiquity new quick-start" 
"Ubiquity serve"

Refresh page http://127.0.0.1:8090/

### Expected Result
Initial page Ubiquity

### Actual Result
Browser: 
HTTP ERROR 500

CLI: 
PHP Fatal error:  Uncaught Error: Call to undefined method Ubiquity\core\Framework::diSemantic() in /home/..../quick-start/app/config/config.php:22
Stack trace:
#0 /home/..../quick-start/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php(241): {closure}()
#1 /home/..../quick-start/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php(39): Ubiquity\controllers\Startup::injectDependences()
#2 /home/..../quick-start/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php(161): Ubiquity\controllers\Startup::_getControllerInstance()
#3 /home/..../quick-start/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php(107): Ubiquity\controllers\Startup::runAction()
#4 /home/..../quick-start/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php(76): Ubiquity\controllers\Startup::forward()
#5 /home/jplm/Nextbox/code/learn/ubiquity/0 in /home/..../quick-start/app/config/config.php on line 22
### Versions
- Ubiquity framework 2.4.12
- Ubiquity devtools 1.2.13
- php 7.4.29
- OS Linux Mint 19.3

**Comment by jcheron** [comment]
This is an old version of devtools, the current version is `1.3.10`
And this old version created a project using a method removed in the last Ubiquity version (which was marked as deprecated for several versions)

Updating devtools and recreating a project should be enough:
```bash
composer global update
```


Otherwise, you can also use the composer `create-project` command, instead of using the `Ubiquity new` command for a project creation:

```bash
composer create-project phpmv/ubiquity-project myProject
```

**Comment by gracite** [comment]
Thanks.
By composer it worked OK.

Congratulations on the quick response.
________________________________
De: J-C HERON ***@***.***>
Enviado: quarta-feira, 27 de abril de 2022 19:54
Para: phpMv/ubiquity ***@***.***>
Cc: Jhow Gracite ***@***.***>; Author ***@***.***>
Assunto: Re: [phpMv/ubiquity] [Framework::diSemantic(] undefined method Ubiquity\core\Framework::diSemantic() on config/config.php:22 (Issue #196)


This is an old version of devtools, the current version is 1.3.10
And this old version created a project using a method removed in the last Ubiquity version (which was marked as deprecated for several versions)

Updating devtools and recreating a project should be enough:

composer global update

Otherwise, you can also use the composer create-project command, instead of using the Ubiquity new command for a project creation:

composer create-project phpmv/ubiquity-project myProject
