### ISSUE TITLE
DAO::getAll() return last element of objects

### ISSUE THREAD

**Issue by devmboehm** [phpMv/ubiquity#200]
Hi, 
If I try to fetch all elements of the table like here
`DAO::getAll(User::class) `
the result is the one/last element of the table. 

my analysis shows me that issue is in this code:
```
		$propsKeys = OrmUtils::getPropKeys ( $className );
		foreach ( $query as $row ) {
			$object = self::_loadObjectFromRow ( $db, $row, $className, $invertedJoinColumns, $manyToOneQueries, $oneToManyFields, $manyToManyFields, $oneToManyQueries, $manyToManyParsers, $metaDatas ['#memberNames'] ?? null, $metaDatas ['#accessors'], $transformers );
			$objects [OrmUtils::getPropKeyValues ( $object, $propsKeys )] = $object;
		}
```
$propsKeys is always the empty string.
Could you fix it? 
Thanks. 

### Versions
    · PHP 8.1.10
    · Ubiquity devtools (1.3.11)
    · OS: Windows NT DESKTOP-6ASMFEG 10.0 build 19044 (Windows 10) AMD64

**Comment by jcheron** [comment]
Hi @devmboehm ,
The most important thing is to give the information to reproduce the bug. In this case, it is missing :
- The version of Ubiquity used: you can get it with `Ubiquity version` in the project root folder
- The code of your model (Entity)
- The code that calls the `DAO::getAll` method

**Comment by devmboehm** [comment]
Hi @jcheron 
here are my missing data:
* version
```
    · PHP 8.1.10
    · Ubiquity devtools (1.3.11)
    · Ubiquity webtools (2.4.16)
    · Ubiquity 2.4.12
```
* model
```
<?php
namespace models;

use Ubiquity\attributes\items\Column;
use Ubiquity\attributes\items\Id;
use Ubiquity\attributes\items\Table;

#[Table('protected_videos')]
class ProtectedVideoModel {

    #[Id]
    #[Column('video_id', false)]
    public $video_id;

    #[Id]
    #[Column('playlist_id', false)]
    public $playlist_id;
}
```
code
```
<?php
namespace controllers;

use Ubiquity\attributes\items\router\Get;
use Ubiquity\attributes\items\router\Route;
use Ubiquity\attributes\items\rest\Rest;

#[Rest(resource: "models\\ProtectedVideoModel")]
#[Route(path: "/rest/abcd")]
class MyTest extends \Ubiquity\controllers\rest\RestResourceController {

	/**
	* Returns a list of objects from the server
	* @get("/")
	*/
	#[Get('/', priority: 0)]
	public function all() {
		$this->_getAll ();
	}
}
```
my database have two entries:
![image](https://user-images.githubusercontent.com/40965147/205111050-ded9df1f-6d8e-495d-b4a5-9b1cdb321180.png)
the response contains only last elements always
![image](https://user-images.githubusercontent.com/40965147/205111474-f4bfe270-067c-41ac-9446-88a47cd11c83.png)

I hope this information helps you to fix this problem or maybe I'm doing something wrong and you can explain what I need to do to fix an error on my side.

**Comment by jcheron** [comment]
The `protected_video` table looks like an association table, with no data.
In this case, there should be no `Protected_video` class, but a `ManyToMany` association in the `Video` class that contains `Protecteds`, and the same in `Protected`, that contains `videos`.

**Comment by devmboehm** [comment]
maybe the title of the table is confusing but I have only one table and want to get all values from this table. Can't reproduce the problem on your site?

**Comment by jcheron** [comment]
The ORM does not handle composite keys, except on association tables with additional fields.
So you have to add a primary key (in auto_inc), and define (by hand since there is no `#Index` attribute) a unique index in the database on your two fields (video_id, playlist_id).

```php
#[Table(name: "protected_videos")]
class Protected_videos{
	
	#[Id()]
	#[Column(name: "id",dbType: "int(30)")]
	#[Validator(type: "id",constraints: ["autoinc"=>true])]
	private $id;

	
	#[Column(name: "video_id",dbType: "int(11)")]
	#[Validator(type: "notNull",constraints: [])]
	private $video_id;

	
	#[Column(name: "playlist_id",dbType: "int(11)")]
	#[Validator(type: "notNull",constraints: [])]
	private $playlist_id;
}
```

**Comment by devmboehm** [comment]
Hi @jcheron ,
Thank you very much for your help and support. With a splitting of id, this works as it should.
