### ISSUE TITLE
webtools Manages composer dependencies does not work

### ISSUE THREAD

**Issue by alnux** [phpMv/ubiquity#203]
The extensions can not be installed from webtools, everything seems to be fine as shown in the [screenshot](https://prnt.sc/w1DIif6lc2iT) in this example phpmv/ubiquity-security, but the folder inside the vendor is not created [screenshot](https://prnt.sc/ZgEwxVtjChyV)

but with terminal composer works without problems

### Versions
    · The project folder is /Volumes/ALLEN-FILES/UBIQUITY/PROYECTS/firstProject

    · PHP 8.1.12
    · Ubiquity devtools (1.4.0)
    · Ubiquity webtools (2.5.0)
    · Ubiquity 2.5.0
    · OS: Darwin imac-de-stream 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64

**Comment by jcheron** [comment]
Composer display:
> Nothing to modify in Lock file

So you can try to run first:
```bash
composer update
```
or delete the `composer.lock` file before adding `Ubiquity-security`

**Comment by alnux** [comment]
hi there,

i did the suggestions but still does not work by webtools, by the way is normal that create composer.json and composer.lock into public directory??? [screenshot](https://prnt.sc/56-140FZbCHO)

**Comment by jcheron** [comment]
indeed, the composer configuration files have nothing to do in the public folder!
I have the impression that your project confuses the `public` folder with the root of your project, which would also explain the problems with `.htaccess` file.

**Comment by alnux** [comment]
yeap you are right but this happing when i use apache server but with `Ubiquity serve` works perfect. what do you suggest? in development work with `Ubiquity serve` and in production with apache or nginx?

**Comment by jcheron** [comment]
the integrated server is indeed reserved for the dev.
And Apache or nginx to the prod.

But you can use Apache for dev.
In this case you will have to create a specific virtualhost
```
<VirtualHost *:80>
    DocumentRoot "C:/xampp8.1.1/htdocs/myProject/public
    ServerName my-project.local
	DirectoryIndex /index.php

	<Directory C:/xampp8.1.1/htdocs/myProject/public>
	# enable the .htaccess rewrites
	AllowOverride All
	Require all granted
	</Directory>
</VirtualHost>
```
and add a local name `my-project.local` in the hosts file.

and update the `.htaccess` file in public folder:
```
AddDefaultCharset UTF-8

<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteBase /
	
	RewriteCond %{REQUEST_FILENAME} !-f  
	RewriteCond %{HTTP_ACCEPT} !(.*images.*)
	RewriteRule ^(.*)$ index.php?c=$1 [L,QSA]
</IfModule>
```

And the siteUrl` `inconfig/config.php` file :
```php
"siteUrl"=>"http://my-project.local/",
```
And re-init config cache:

```bash
Ubiquity init-cache -t=config
```
