### ISSUE TITLE
[RFC] Nette latte templates compatibility

### ISSUE THREAD

**Issue by alnux** [phpMv/ubiquity#204]
what problems could there be if instead of twig I use the latte template system [https://latte.nette.org](https://latte.nette.org) 

Thanks

PD. Could implement the support of this template system because it is very good.

**Comment by jcheron** [comment]
At first glance, it seems feasible.
We need to create a class for the Nette engine inheriting from `TemplateEngine`.

**But you have to think :**

- the webtools, which will continue to use Twig => force the webtools to stay with Twig
- The Scaffolding part (for the Authentication and CRUD part), which uses the generation of Twig views from template files => it must be possible to generate Nette or Twig views

**Comment by jcheron** [comment]
Hi @alnux 

You can test the integration of Latte in ubiquity by updating your devtools:
```bash
composer global require phpmv/ubiquity-devtools:dev-add-template-engine-choice
```
Then by creating a new project:
```bash
Ubiquity new test-latte -v=latte -a
```

**Comment by alnux** [comment]
Hi @jcheron I really busy with job, I will do as soon as I can, wow you are great

**Comment by jcheron** [comment]
Since the Ubiquity 2.5.2 release, it is enough to do:
```bash
composer global update
Ubiquity new test-latte -v=latte -a
```

**Comment by alnux** [comment]
hi there @jcheron i found a error with latte and themes 

1 after use Ubiquity new test-latte -v=latte -a and change dir into test-latte in this case, i serve localhost with Ubiquity serve command and then show the next error

https://prnt.sc/Ncqa_yQ6nKBX

i have to refresh to load index or welcome ubiquity page

there is problem too when i change the theme with bootstrap

Ubiquity install-theme bootstrap

it show the same error of the screenshot that i paste here https://prnt.sc/Ncqa_yQ6nKBX but broken all becouse i try to comment "activeTheme"=>"bootstrap" directive but the error is still there, i refresh de cache or delete it but the error is still. with other template engine(twig) works without any problem, i can remove the theme and still working, but with latte broken all if i install themes.
