### ISSUE TITLE
theme cant be installed from webtools

### ISSUE THREAD

**Issue by alnux** [phpMv/ubiquity#205]
Im trying to install theme from webtools but this show the next error Im using `Ubiquity serve`

```
Theme installation...
echo n | Ubiquity install-theme foundation
sh: Ubiquity: command not found
```
but with on command line works without problem

```
stream@imac-de-stream firstProject % Ubiquity install-theme foundation

    · The project folder is /Volumes/ALLEN-FILES/UBIQUITY/PROYECTS/firstProject
     ╭───────────────────────────────────────────╮
     │      ■ Info : Adding theme foundation     │
     │      · Files copy...                      │
     ╰───────────────────────────────────────────╯
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^6.7 for zurb/foundation
./composer.json has been updated
Running composer update zurb/foundation
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking zurb/foundation (v6.7.5)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing zurb/foundation (v6.7.5): Extracting archive
Generating autoload files
9 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found
Would-you like to define foundation as the active theme ? (y/n)
n

```

· The project folder is /Volumes/ALLEN-FILES/UBIQUITY/PROYECTS/firstProject

    · PHP 8.1.12
    · Ubiquity devtools (1.4.0)
    · Ubiquity webtools (2.5.0)
    · Ubiquity 2.5.0
    · OS: Darwin imac-de-stream 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64

**Comment by jcheron** [comment]
The Ubiquity command is probably defined in your user `PATH`, and not in your system PATH (bin folder of composer).
This explains why the apache user cannot find the command.

**Comment by alnux** [comment]
Im using `Ubiquity serve`

**Comment by jcheron** [comment]
No, you didn't understand me.
You have to add the composer `bin` folder in your `PATH` environment variable for all users.

see https://www.cyberciti.biz/faq/appleosx-bash-unix-change-set-path-environment-variable/
