### ISSUE TITLE
Call for graphic designers and good ideas

### ISSUE THREAD

**Issue by jcheron** [phpMv/ubiquity#28]
Developers are not graphic designers, at least not me.
And design is important too.

The current graphic charter is limited to the use of 3 colours:
- `#4DA0B0`
- `#D39D38`
- `#333333`

The **Ubiquity** title uses the font family `Righteous`:
![image](https://user-images.githubusercontent.com/2511052/56584249-b1fe7f80-65db-11e9-99ab-6ef0067baa69.png)
The subtitle: `Poiret One`
![image](https://user-images.githubusercontent.com/2511052/56584366-ebcf8600-65db-11e9-8029-792d6e6901c3.png)

However, Ubiquity does not have a logo,
other than this simple U found on the Internet, which acts as a favicon:
![image](https://user-images.githubusercontent.com/2511052/56583244-6c40b780-65d9-11e9-9398-453e84d925f1.png)

This U should invoke the fundamentals of the framework, performance and ease of use, or simply be esthetic and identifiable.

I therefore appeal to all those of good will who feel like the soul of a graphic designer, to those who have the skills, and to all those who have ideas.
This current `U` is pathetic!

**Comment by richardbmx** [comment]
@jcheron Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by jcheron** [comment]
Hi Richard,
super reactivity!
I'd be very interested to see your proposals.

**Comment by richardbmx** [comment]
Perfect I will work on a model and I will present it to you shortly

**Comment by richardbmx** [comment]
@jcheron 
I present this proposal focused on the color palettes that you indicate and giving a modern and minimalist style to the letter U, using the symbols in a corner to give a relationship with the programming language php, as you can see the design adapts very well in different colors and backgrounds and in the favicon and icon version it looks excellent I hope you like it, if you want some change you just have to ask for it and with pleasure I will do it

![logo132](https://user-images.githubusercontent.com/35604837/56591184-43f39180-65b6-11e9-9e84-dfa17263ebd6.png)

**Comment by jcheron** [comment]
Good job!
It's very nice.
The symbol in the corner is a good idea.

I'm a little less convinced by my color choices when you use them as a plain background.
These colours are usually used in a gradient, or on small elements.

they can perhaps be varied when used over a larger area, while remaining in the same hue.

**Comment by richardbmx** [comment]
The plain background was to give an idea of ​​how the whole design looks in a single white color however using the gradient design it looks very good

![fodno2](https://user-images.githubusercontent.com/35604837/56600843-ad2fd080-65c7-11e9-83c5-eaa605c08581.png)


![fodno](https://user-images.githubusercontent.com/35604837/56600766-7f4a8c00-65c7-11e9-9ec1-965b058e52d5.png)

**Comment by richardbmx** [comment]
if you want I can make a PR incorporating the design to your project

**Comment by jcheron** [comment]
Superb, it's very beautiful!
I've already tried the [favicon](https://ubiquity.kobject.net).
You will tell me how I should mention your signature

**Comment by richardbmx** [comment]
You can mention me as a collaborator in the readme, however it is not obligatory to do it

**Comment by richardbmx** [comment]
All the editable files in the google folder together with a file that makes delivery to the copyright for its free use.. Thank you very much for allowing me to work on your project, I am available for future projects if you wish

[Google Drive](https://drive.google.com/open?id=1puZwMrER7gHYZVL8ggBpT_-SOay4_Wu_)

**Comment by jcheron** [comment]
It will be with pleasure for future projects Richard
