### ISSUE TITLE
warning notice on 2.5.2

### ISSUE THREAD

**Issue by alnux** [phpMv/ubiquity#317]
hi, i just installed the framework but there is a warning notice that stops, below a screenshot. it happen with 

Ubiquity new firstProject -a

https://prnt.sc/PQDIyT90oiDB

but composer (composer create-project phpmv/ubiquity-project firstProject) create project works without problem

### Versions
- Ubiquity framework 2.5.2
- php 8.1.6
- Mac OS 10.13.6

**Comment by jcheron** [comment]
Maybe the devtools aren't up to date...
```bash
composer global update
```
