### ISSUE TITLE
[devtools] Ubiquity command unavailable after installation

### ISSUE THREAD

**Issue by dysback** [phpMv/ubiquity#32]
### Steps

installed Ubiquity as stated in guide:
**composer global require phpmv/ubiquity-devtools**

### Expected Result

Expected that command Ubiquity will be globally available

### Actual Result

Ubiquity installed to location:
**$HOME/.composer/vendor/phpmv/ubiquity-devtools/src/**
but it is not added to $PATH so it is not available as in guide.

When specifying full path everything works fine.

### Versions
- Ubiquity framework 2.1.2
- Ubiquity devtools 1.2.3
- php x7.3.4-1
- OS ubuntu19.04.1

**Comment by jcheron** [comment]
The guide is not precise enough on this (very important) subject.
I think we should add the procedures to make `Ubiquity` accessible for each of the systems.

**Comment by dysback** [comment]
I tried installation on Windows too and Ubiquity is available globally. (As I expected)
