### ISSUE TITLE
[webtools][models] no file found in app/models folder

### ISSUE THREAD

**Issue by trk** [phpMv/ubiquity#33]
### Steps
I am getting error on Ubiquity Admin, `Admin/Model` section

<img width="1152" alt="Ekran Resmi 2019-04-28 00 39 41" src="https://user-images.githubusercontent.com/455983/56855335-26c01980-694e-11e9-956a-38065e14e8d2.png">

but i have this folder

<img width="146" alt="Ekran Resmi 2019-04-28 00 40 15" src="https://user-images.githubusercontent.com/455983/56855346-3b041680-694e-11e9-9b76-6e641f91e27b.png">

Maybe need to separate paths, `ROOT` with `APP_ROOT` inside `index.php` file

`ROOT` must be document root
`APP_ROOT` must be application root

### Expected Result

Must find it

### Actual Result

Couldn't find it

### Versions
- Ubiquity framework 2.1.2
- Ubiquity devtools 1.2.3
- php 7.3.4
- Macos 10.14.4

**Comment by jcheron** [comment]
with Ubiquity, `ROOT` constant refers to `app` folder

**Comment by trk** [comment]
Ok, why going back from `.ubiquity` folder to `app` folder, i don't know is this reason for getting this error.

But i want to know, how to resolve this problem ?

**Comment by jcheron** [comment]
which server do you use in this case?

**Comment by trk** [comment]
Using `Ubiquity serve` method

```console
Ubiquity serve
```

**Comment by jcheron** [comment]
When you use
```Ubiquity serve```
the index file used is `/.ubiquity/_index.php`, and not `/index.php`

**Comment by jcheron** [comment]
The question is:
did you generate the models?

**Comment by trk** [comment]
Ok, will close this issue, i think, like you mentioned : need to generate a model and need to create a database table for this model.

Sorry about waste your time, i am trying the framework :(
