### ISSUE TITLE
[travis] trojan detected HEUR:Trojan.Script.Miner.gen

### ISSUE THREAD

**Issue by powvex** [phpMv/ubiquity#331]
(https://github.com/phpMv/ubiquity/raw/master/src/tests/files/travis/.travis.yml)

detected by some trojan scanners as trojan installer:
Name: HEUR:Trojan.Script.Miner.gen
Threat level: High
Object name: .travis.yml 

after further investigation, found that travis.yml try installing "https://scrutinizer-ci.com/ocular.phar" on client pc, that it uses some suspicious activities to use some routines inside sub folder "Guzzle" that is similar to client mining script.

please investigate yourself to see if this is used as suggested.

**Comment by jcheron** [comment]
Hi @powvex 
`travis.yml` is used by continuous integration, by Travis-ci, not on the client workstation.
It also contains no malicious scripts.
I think it's a false positive, your antimalware is being overzealous.
