### ISSUE TITLE
[init-cache] error by execution of init-cache

### ISSUE THREAD

**Issue by devmboehm** [phpMv/ubiquity#332]
Hi, 
I have some issues with the initialization of the cache via CLI. 

### Steps
* command: `Ubiquity init-cache` throws this error:
> Message: Undefined constant "controllers\PERM_EXT_NAME"
   File:  .../vendor/phpmv/ubiquity-attributes/src/Ubiquity/attributes/AttributesEngine.php   
   Line: 39 

### Expected Result
no errors

### Actual Result
* cache is not complete and the application does not work properly
* workaround: use cache initialization via UI

### Versions
   * PHP 8.2.15
   * Ubiquity devtools (1.4.8)
   * Ubiquity webtools (2.5.4)
   * Ubiquity 2.5.2

**Comment by devmboehm** [comment]
sorry... I think this is a problem on my side...

**Comment by jcheron** [comment]
It's good that you solved it
