### ISSUE TITLE
[Views][Theme] The ThemesManager write config.php without validation

### ISSUE THREAD

**Issue by jyyan** [phpMv/ubiquity#38]
### Steps

in the Ubiquity quick-start project, [`Index` Controller `ct` action](https://github.com/phpMv/ubiquity-demos/blob/23115a5303e3590338b281f8b0a526d4d4c3317d/auth-project/app/controllers/IndexController.php#L25)

I found the `ThemesManager::saveActiveTheme` method will write $activeTheme into `config.php` directly, without any filter and check the theme is exist or not.

it will cause error when I send request as `http://127.0.0.1:8000/IndexController/ct/bootstrap"` or `http://127.0.0.1:8000/IndexController/ct/bootstrap'` or `http://127.0.0.1:8000/IndexController/ct/SomeErrorString`

### Expected Result

`ThemesManager::saveActiveTheme` maybe have to filtered the invalid ThemeName string before write into `config.php`

### Actual Result
the `config.php` got wrong value of `activeTheme` such like :

``` php
	"templateEngineOptions"=>array(
			"cache"=>false,
			"activeTheme"=>"bootstrap""
			),
```
or 
``` php
	"templateEngineOptions"=>array(
			"cache"=>false,
			"activeTheme"=>"bootstrap'"
			),
```
```
PHP Parse error:  syntax error, unexpected '"' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /app/config/config.php on line 21
```
or

``` php
	"templateEngineOptions"=>array(
			"cache"=>false,
			"activeTheme"=>"SomeErrorString"
			),
``` 
```
Tue May  7 07:56:28 2019] PHP Fatal error:  Uncaught Exception: View @activeTheme/main/vHeader.html not found! in /vendor/phpmv/ubiquity/src/Ubiquity/views/View.php:75
Stack trace:
#0 /vendor/phpmv/ubiquity/src/Ubiquity/controllers/Controller.php(67): Ubiquity\views\View->render('@activeTheme/ma...', false)
#1 /app/controllers/ControllerBase.php(16): Ubiquity\controllers\Controller->loadView('@activeTheme/ma...')
#2 /vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php(143): controllers\ControllerBase->initialize()
#3 /vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php(30): Ubiquity\controllers\Startup::runAction(Array, true, true)
#4 /vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php(98): Ubiquity\control in /vendor/phpmv/ubiquity/src/Ubiquity/views/View.php on line 75

```
### Versions
· PHP 7.1.27-1+ubuntu18.04.1+deb.sury.org+1
· Ubiquity devtools (1.2.3)
· Ubiquity 2.1.2

**Comment by jcheron** [comment]
Thanks for reporting @jyyan

**Comment by jcheron** [comment]
The **IndexController** file is generated with devtools, when the ``new`` command is used.
So this issue is fixed in devtools repository, for future projects.
