### ISSUE TITLE
Dependency injection in controller

### ISSUE THREAD

**Issue by mashmars** [phpMv/ubiquity#41]
follow this step by  https://micro-framework.readthedocs.io/en/latest/controller/di/index.html#service-injection, but in controller var_dump($this->serviceToInit) is null, so what mistake i make?

yes it's a very good framework, i like it and symfony!

**Comment by mashmars** [comment]
`/**
	 * @injected
	 */
	private $serviceToInit;

	/**
	 * @route("/service/two/test")
	 */
	public function index()
	{
		var_dump($this->serviceToInit);exit;
		$this->serviceToInit->do();
	}`
`/**
	 * @param mixed $serviceToInit
	 */
	public function setServiceToInit($serviceToInit) {		
		$this->serviceToInit = $serviceToInit;		
	}`

app config
`"di"=>[
				"@exec"=>["jquery"=>function($controller){
						return \Ubiquity\core\Framework::diSemantic($controller);
					}],
				
				"DefaultController.serviceToInit" => function() {
					$service = new \services\ServiceWithInit();
					$service->init();
				}
				
			],`

**Comment by jcheron** [comment]
Hi @mashmars ,
There is indeed an error in the documentation.
The injected callback forgets the return

In **config.php**, you must add ```return $service```:
```php
		"di"=>["@exec"=>["jquery"=>function($controller){
						return \Ubiquity\core\Framework::diSemantic($controller);
					}],
				"IndexController.serviceToInit"=>function(){
					$service=new \services\ServiceWithInit();
					$service->init();
					return $service;
				}
		],
```
and reset the cache:
```
Ubiquity init-cache -t=controllers
```

**Comment by mashmars** [comment]
oop, thank you!

**Comment by jcheron** [comment]
Thanks for reporting @mashmars
