### ISSUE TITLE
DevTools - Error creating new project

### ISSUE THREAD

**Issue by gildonei** [phpMv/ubiquity#44]
Got error when creating a new project with semantic theme only

### Step 1
`C:\wamp64\www\ubiquity>Ubiquity new html -a -themes=semantic -b=dsv_ubiquity -s=192.168.0.70 -u=ubiquity -w=ubiquity
The html folder already exists !
Would you like to continue ? (y/n)
y
Files copy...
Config files creation...
command line arguments :
siteUrl='http://127.0.0.1/html/', projectName='html', injections='', cssFiles='', jsFiles='', dbName='dsv_ubiquity', dbType='1', serverName='192.168.0.70', port='3306', user='ubiquity', password='ubiquity', all-models='1', phpmv='', admin='1'`

### Warning 1
` ■ warning : Themes installation
      · The theme 1 does not exists!  `

### Error 1
`Error!: could not find driver<br/>     
      ■ error                                                                                                                 
      · Message : Call to a member function query() on null                                                                   
      · File : C:\wamp64\www\ubiquity\html\vendor\phpmv\ubiquity\src\Ubiquity\orm\creator\database\DbModelsCreator.php       · Line : 34 `

### Expected Result
Creation of new project with semantic theme only

### Actual Result
Fatal error

### Versions
- Ubiquity devtools 1.2.5
- php 7.1.9
- Windows

**Comment by jcheron** [comment]
Hi @gildonei ,
you have to put two -- for long options
```
Ubiquity new fooProject -a --themes=semantic -b=fooBase
```
and only one for short ones:
```
Ubiquity new fooProject -a -h=semantic -b=fooBase
```

And in that case, I don't have any errors.

**Comment by gildonei** [comment]
Perfect! 
Sorry my mistake.
