### ISSUE TITLE
DevTools - new parameter for project creation

### ISSUE THREAD

**Issue by gildonei** [phpMv/ubiquity#45]
## Summary
I would like to suggest the inclusion of new parameters for project creation that will allow to specify **siteUrl** in _config.php_ and **RewriteBase** in .htaccess

## Motivation
I always use apache vHosts for all projects, this way I can simulate the real host/domain and rewrite rules properly.

## Compatibility with Ubiquity's philosophy 

Indicate compatibility or improvements in:
- ease of use

## Expected results

Inclusion of new project creation parâmeters

**Comment by jcheron** [comment]
It's more of a request for the [devtools project](https://github.com/phpMv/ubiquity-devtools)
but if not, it's a good idea.

And if you don't want to have to modify the `siteUrl`, you can use the internal server, from the project's folder:
```
Ubiquity serve
```
or the new server version with ReactPhp (for more performance)
```
Ubiquity serve -t=react
```

**Comment by gildonei** [comment]
So, should we close this issue here and re-open on [devtools project?](https://github.com/phpMv/ubiquity-devtools)

**Comment by jcheron** [comment]
No, not this time.

have you tried React?
It's much faster (5 to 10 times depending on the requests)

**Comment by gildonei** [comment]
Not yet.
Are there any sample how to deploy a PHPReact in a production server? Should I have to use sudo or root access to configure PHPReact as a service?

**Comment by jcheron** [comment]
No, the documentation to use React in production is not done. In fact, Ubiquity-react is still in beta version.
I think it will be wise to use it coupled with NGinx as a loadbalancer.
In this configuration, the performances are the best.
You need some admin rights to configure this.
