### ISSUE TITLE
Ubiquity and code standards - PSRs

### ISSUE THREAD

**Issue by jcheron** [phpMv/ubiquity#47]
PHP has long suffered from the lack of standardization and shared standards. [PHP-Fig](https://www.php-fig.org) has fixed this, it's a chance!

But the PHP community now tends to move towards the opposite excess, probably traumatized by the previous period.
Any project that does not comply with the PSRs is poorly considered and must be corrected accordingly.
I think that the standards are a guide (a bit like the code for pirates?), providing more flexibility to developers using a project, but that it is allowed, in certain particular cases, not to respect them, under conditions:
- be able to justify this non-compliance, and explain the reasons for it
- possibly adapt and implement another standard

What is dangerous is not the choice not to meet a specific standard, but to have none.
A development team working on a project, whether private or even public, always has the right to adopt its own standards!
Ubiquity does not comply with all standards, so it is important to explain the reasons:

## PSR-1 & PSR-2:
see [PSR-1: Basic Coding Standard](https://www.php-fig.org/psr/psr-1/) and [PSR-2: Coding Style Guide](https://www.php-fig.org/psr/psr-2/)
Ubiquity makes two exceptions to PSR-2:
1. Opening braces for classes, methods and functions MUST go on **the same line**, and closing braces MUST go on the next line after the body.
>This choice is not decisive, and it depends on the habits of each one. But it is always possible to visualize the beginning of a class or a method, without seeing the opening brace.
2. Code MUST use **tabs** for indenting, not spaces.
>It's easy to put an unnecessary space and not realize it. It's harder not to see a tab.
>Tabs allows each developer to adjust the size of the indentation on his workbench.

It is important to remember that compliance with PSR-2 does not make the quality of the code.

## PSR-3:
see [PSR-3: Logger Interface](https://www.php-fig.org/psr/psr-3/)
Ubiquity does not respect the implementation of `LoggerInterface`.
This defect will have to be fixed in the future, to allow third party libraries to use the application's Log system.

## PSR-4:
see [PSR-4: Autoloading](https://www.php-fig.org/psr/psr-4/)
Ubiquity complies with PSR-4 specifications for class autoloading:
- For the framework sources, the `Ubiquity` namespace corresponds to the `src/Ubiquity` folder
- For a project, the root of the namespaces corresponds to the folder `app/`

## PSR-6:
see [PSR-6: Caching Interface](https://www.php-fig.org/psr/psr-6/)
Ubiquity does not comply with the specifications related to the cache system. This deficiency will probably have to be fixed in the future.
Given the nature and role of the cache system, its compliance with PSR-6 would be discontinued if it had a negative impact on performances.

## PSR-7:
see [PSR-7: Http messages](https://www.php-fig.org/psr/psr-7/)
This is not a non-compliance with the specifications related to HTTP messages interfaces.
It's more of a design choice.
PHP does not have native HTTP Response and Request objects but gives access to the super global `$_POST`, `$_GET`, `$_SERVER`, `$_FILES`...
Ubiquity keeps this simplification of PHP, and simply allows easier handling of super globals via `URequest`, `UResponse`, `UCookie`, `USession` utility classes.
These classes do not represent Request, Response objects...and only have static methods.
PSR-7 does not have to apply in this case.

Ubiquity derives part of its performance from this compliance with PHP.
If the evolution of PHP led it to provide such objects, Ubiquity would certainly follow it in this direction.

## 
Ubiquity does not have the maturity of other frameworks and there is still a lot to do.
All choices can be discussed, 
all contributions are always welcome!

**Comment by gildonei** [comment]
In PSR-2 I agree with use of tabs, but I really prefer opening braces below class name and methods signature.

All others PSR I am OK with Ubiquity development.

**Comment by Tiippex** [comment]
Hello,

Is there a chance that you work according the PSR 12 Coding Style?
Would like to use the php7 features like the return type declarations and the scalar type declarations.

Whats about using these 'my string' insteat of these "my string" --> '' ""
There is no reason why php should look for variable in simple strings like this here: $deflang = "en"

If you would like to change one of these styles I would definitely help you!

Tiippex

**Comment by jcheron** [comment]
Hi @Tiippex 
I am also in favour of typing, the introduction of the strict standard declaration is a good thing.

These are the main advances of `PSR-12`, the rest being more or less formatting choices to which I do not totally agree, I would still have the same 2 reservations as on PSR2.

And I still think that when it comes to code formatting, each team can make its own choices. The quality of the code is based on other criteria than the formatting choices surprisingly made by php-fig....

For the use of `"strings"` instead of `'string'`, I try to be careful, but I tend to keep my java reflexes `"` for the strings,`'` for the chars

I would be happy to accept your help with the (partial) transition to PSR-12 and the corrections to be made to the current code. :-)

**Comment by Tiippex** [comment]
Hi,

thanks for the fast reply!

---
> These are the main advances of `PSR-12`, the rest being more or less formatting choices to which I do not totally agree, I would still have the same 2 reservations as on PSR2.

-> when using the strict standard would you still prefer the opening braces to be in the same line then the method head? e.g.:
```
public function test(): string
{

public function test(): string {
```
I prefer the first variant. But I'm happy with the second one as well.

---
> For the use of `"strings"` instead of `'string'`, I try to be careful, but I tend to keep my java reflexes `"` for the strings,`'` for the chars

-> so its okay when I change them when I see them? (I know the performance difference is tiny, but it is a difference ;D)

---
> In PSR-2 I agree with use of tabs,

-> I guess you will stick to the tabs instead of spaces? Looking forward to psr12. Im thinking of using vim/nano when I have to edit files directly on a server. They don't like tabs so much.


Tiippex

**Comment by gildonei** [comment]
Hi @jcheron and @Tiippex my opinion.

A) oppening braces: I prefer below method signature
B) " or ' : no preferences
C) Tabs / Spaces: I prefer tabs

**Comment by Tiippex** [comment]
@gildonei 
is there a reason why you would like to stick to psr2 (spaces/tabs)?

> It's easy to put an unnecessary space and not realize it. It's harder not to see a tab.

-> the first point is not a real point for me. I think phpmd, phpstan and such stuff should check the code before you can commit it. 


> Tabs allows each developer to adjust the size of the indentation on his workbench.

-> okay, fair point, but how many devs are changing the indentation size?

**Comment by jcheron** [comment]
Cake's core team also had [some concerns about PSR-2](https://groups.google.com/forum/#!topic/cakephp-core/QnTBtN6K9AQ/discussion) a few years ago...

Formatting must satisfy team members and remain consistent within a project, but it has nothing to do with quality and even less with interoperability.
None of the PSR-2 or PSR-12 formatting rules should use the keyword `"MUST"`.

PHP-Fig and PSR-12 would have been more consistent if they had not mixed:
- simple formatting (spaces, identation...) which is just a coding style guide that can be followed
- with coding standards which have real consequences on code quality (type declarations...)

**Comment by gildonei** [comment]
@Tiippex About Tabs vs Spaces - I believe that tabs are proper for indentation and you can "easily" advance or go back with keyboard cursor (It is 3 times faster). Using tabs, you also save some "bits" of your final document size, 1tab vs 4 spaces. 

I think is easy  to use tab and if need to go back when typing just press back arrow instead of ctrl+back arrow to have the same result

**Comment by Tiippex** [comment]
Good morning,

@jcheron don't get me wrong. Just tried to see the advantages in tabs from a different perspective.
Whats about the my opening braces example above and can I change these " to these ' when I see them? Would like to know that before I start working on it ;)

@gildonei I will try it.

**Comment by jcheron** [comment]
Hi @Tiippex ,
It'ok for the opening braces revision (" -> ') 👍 

It is just necessary to preserve the use of `"` for the concatenation of strings with variables.
Chain parsing is always faster than expicite concatenation, as this php 7.3 benchmarks below show:

![image](https://user-images.githubusercontent.com/2511052/64421930-114cc000-d0a3-11e9-8c2f-ccfa05b05240.png)

![image](https://user-images.githubusercontent.com/2511052/64421963-2b869e00-d0a3-11e9-8faa-994fc80a2f72.png)

**Comment by Tiippex** [comment]
I agree. Which benchmark site is that?

**Comment by gildonei** [comment]
@jcheron nice work with those benchs

**Comment by jcheron** [comment]
It is a website that I have set up for my own benchmarks, and that you can use to make your own :)
See [phpMyBenchmarks](https://phpmybenchmarks.kobject.net)

**Comment by Tiippex** [comment]
Its a very nice tool! Tested it a bit.

> It is just necessary to preserve the use of `"` for the concatenation of strings with variables.

That depends on the string length I think. Your benchmark is a bit limited with the string length but anyway, I think in 99% of the hole project strings are quite short :D

**Comment by jcheron** [comment]
You just highlighted a bug, by putting a `'` in a test case title.
I've temporarily changed your title `long string / var / \'`
It was probably only partially working.
