### ISSUE TITLE
[RFC] Maintenance Mode - suggestion

### ISSUE THREAD

**Issue by gildonei** [phpMv/ubiquity#49]
## Summary

I think would be nice if Ubiquity have a native maintenance mode, that could be activated in config through webadmin or devtools, and when in maitenance, it only allows backend access interface, and in front a page with a maintenance message or similar

## Motivation

All major CMS (WordPress, Joomla, Drupal) have a similar functionality, that allows properly config system without break the front, keeping a maintenance page and maybe an http respose

## Compatibility with Ubiquity's philosophy 

Indicate compatibility or improvements in:
- ease of use

## Expected results

Visitors of website developed with Ubiquity will see a maintenance page instead of the site while It is setted to be down.

**Comment by jcheron** [comment]
Ubiquity is not a CMS, but it's a good idea...
So we disable all URLs except the Admin access URLs, and we refer to a customizable maintenance page?

**Comment by gildonei** [comment]
Yes (not a CMS, is a framework), and yes disable Url except admin routes.
I think should be a config item for a maintenance title and message, so, when in a maintenance mode is set to On, /index only shows the title and message, and allows admin route.
Rest Services should be disabled to, with a default response

**Comment by jcheron** [comment]
The **maintenance mode** can be tested before its integration in version **2.1.5** (`composer require phpmv/ubiquity:dev-master` in a new project).

For the principle (in the background), the maintenance mode works by adding a route to a maintenance controller, excluding for example administration (Urls starting with `admin` or `Admin`).

I will add by default a **comingSoon** mode (for the example).

**Maintenance** is accessible in the webtools in the **Maintenance section**.

**Comment by gildonei** [comment]
I got a fatal error 
`Fatal error: Class 'Ubiquity\controllers\admin\UbiquityMyAdminBaseController' not found in C:\wamp64\www\ubiquity\html\app\controllers\Admin.php on line 5` after run _composer require_

Do i forgot to do something? I ran it on a almost blank project (it has only a model)

**Comment by jcheron** [comment]
you must explicitly include webtools:
``composer require phpmv/ubiquity-webtools:dev-master``

**Comment by gildonei** [comment]
`Fatal error: Declaration of Ubiquity\controllers\admin\traits\ModelsTrait::showSimpleMessage($content, $type, $title = NULL, $icon = 'info', $timeout = NULL, $staticName = NULL): Ajax\semantic\html\collections\HtmlMessage must be compatible with Ubiquity\controllers\semantic\MessagesTrait::showSimpleMessage($content, $type, $title = NULL, $icon = 'info', $timeout = NULL, $staticName = NULL, $closeAction = NULL): Ajax\semantic\html\collections\HtmlMessage in C:\wamp64\www\ubiquity\html\vendor\phpmv\ubiquity-webtools\src\Ubiquity\controllers\admin\UbiquityMyAdminBaseController.php on line 67`

**Comment by jcheron** [comment]
maybe the devtools are not up to date...
``composer global update``
and then recreates a new project:
``Ubiquity new testMaintenance -a``
in which you go to 2.2.0 (or 2.1.5)
``compose require phpmv/ubiquity:dev-master``

**Comment by gildonei** [comment]
2.1.5
```
C:\wamp64\www\ubiquity\html> composer global update
Changed current directory to C:/Users/Gildonei/AppData/Roaming/Composer
Loading composer repositories with package information

Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

C:\wamp64\www\ubiquity\html>ubiquity version


    · The project folder is C:\wamp64\www\ubiquity\html

    · PHP 7.1.9
    · Ubiquity devtools (1.2.6)
    · Ubiquity 2.1.5
```

**Comment by jcheron** [comment]
devtools would be **1.2.7**
![image](https://user-images.githubusercontent.com/2511052/60263535-307be400-98e1-11e9-9c13-72ea69699eb9.png)

**Comment by gildonei** [comment]
Tried to follow steps above but in the end got same errors

![image](https://user-images.githubusercontent.com/1370979/60264594-f0edd180-98b9-11e9-8c67-8f9ddf1e86f3.png)

**Comment by gildonei** [comment]
I will update everything to dev-master (ubiquity, devtools, webtools) see what happens

**Comment by gildonei** [comment]
**Update**

```
C:\wamp64\www\ubiquity>composer global require phpmv/ubiquity:dev-master
Changed current directory to C:/Users/Gildonei/AppData/Roaming/Composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 0 updates, 0 removals
Generating autoload files

C:\wamp64\www\ubiquity>composer global require phpmv/ubiquity-devtools:dev-master
Changed current directory to C:/Users/Gildonei/AppData/Roaming/Composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 0 updates, 0 removals
Generating autoload files

C:\wamp64\www\ubiquity>composer global require phpmv/ubiquity-webtools:dev-master
Changed current directory to C:/Users/Gildonei/AppData/Roaming/Composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 0 updates, 0 removals
Generating autoload files

C:\wamp64\www\ubiquity>

```

**After update**

```
C:\wamp64\www\ubiquity>ubiquity new html -a -b=dsv_ubiquity -s=192.168.0.70 -u=teste -w=teste -h=semantic -i=https://ubiquity.local -e=/

    · Files copy...

    · Config files creation...

     ╭────────────────────────────────────────────────╮
     │      ■ info : Command line arguments           │
     │      · projectName='html'                      │
     │      · cssFiles=''                             │
     │      · jsFiles=''                              │
     │      · injections=''                           │
     │      · dbName='dsv_ubiquity'                   │
     │      · dbType='mysql'                          │
     │      · serverName='192.168.0.70'               │
     │      · port='3306'                             │
     │      · user='teste'                             │
     │      · password='teste'                 │
     │      · all-models=''                           │
     │      · admin='1'                               │
     │      · themes='semantic'                       │
     │      · siteUrl='https://ubiquity.local'        │
     │      · rewriteBase='/'                         │
     │      · use-cdn=''                              │
     ╰────────────────────────────────────────────────╯

Fatal error: Declaration of Ubiquity\controllers\admin\traits\ModelsTrait::showSimpleMessage($content, $type, $title = NULL, $icon = 'info', $timeout = NULL, $staticName = NULL): Ajax\semantic\html\collections\HtmlMessage must be compatible with Ubiquity\controllers\semantic\MessagesTrait::showSimpleMessage($content, $type, $title = NULL, $icon = 'info', $timeout = NULL, $staticName = NULL, $closeAction = NULL): Ajax\semantic\html\collections\HtmlMessage in C:\Users\Gildonei\AppData\Roaming\Composer\vendor\phpmv\ubiquity-webtools\src\Ubiquity\controllers\admin\UbiquityMyAdminBaseController.php on line 67

```

**Fetching version**

```
C:\wamp64\www\ubiquity>ubiquity version

Fatal error: Declaration of Ubiquity\controllers\admin\traits\ModelsTrait::showSimpleMessage($content, $type, $title = NULL, $icon = 'info', $timeout = NULL, $staticName = NULL): Ajax\semantic\html\collections\HtmlMessage must be compatible with Ubiquity\controllers\semantic\MessagesTrait::showSimpleMessage($content, $type, $title = NULL, $icon = 'info', $timeout = NULL, $staticName = NULL, $closeAction = NULL): Ajax\semantic\html\collections\HtmlMessage in C:\Users\Gildonei\AppData\Roaming\Composer\vendor\phpmv\ubiquity-webtools\src\Ubiquity\controllers\admin\UbiquityMyAdminBaseController.php on line 67

```

**Comment by gildonei** [comment]
**Step 1:** downgraded **global** _ubiquity_ and _webtools_ - **OK**
```
composer global require phpmv/ubiquity-webtools
composer global require phpmv/ubiquity
```

**Step 2:** Create a new project
`ubiquity new html -a -b="dsv_ubiquity" -s="192.168.0.70" -u="teste" -w="teste" -h="semantic" -i="http://ubiquity.local" -e="/"` - **OK**

**Step 3:** tried to check `ubiquity version` - **ERROR**
```
C:\wamp64\www\ubiquity\html>Ubiquity version

    · The project folder is C:\wamp64\www\ubiquity\html
     ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
     │      ■ error                                                                                                │
     │                                                                                                             │
     │      · Message : Undefined class constant 'version'                                                         │
     │      · File : C:\Users\Gildonei\AppData\Roaming\Composer\vendor\phpmv\ubiquity-devtools\src\Ubiquity        │
     │      · Line : 423                                                                                           │
     ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

```
**Step 4:** Inside project folder, switch all to dev-master: **OK**
```
composer require phpmv/ubiquity:dev-master
composer require phpmv/ubiquity-webtools:dev-master
```

**Step 5:** Tried to get ubiquity version again and got same fatal error before - **ERROR**
```
C:\wamp64\www\ubiquity\html>ubiquity version

    · The project folder is C:\wamp64\www\ubiquity\html

Fatal error: Declaration of Ubiquity\controllers\admin\traits\ModelsTrait::showSimpleMessage($content, $type, $title = NULL, $icon = 'info', $timeout = NULL, $staticName = NULL): Ajax\semantic\html\collections\HtmlMessage must be compatible with Ubiquity\controllers\semantic\MessagesTrait::showSimpleMessage($content, $type, $title = NULL, $icon = 'info', $timeout = NULL, $staticName = NULL, $closeAction = NULL): Ajax\semantic\html\collections\HtmlMessage in C:\wamp64\www\ubiquity\html\vendor\phpmv\ubiquity-webtools\src\Ubiquity\controllers\admin\UbiquityMyAdminBaseController.php on line 67

```

**Comment by jcheron** [comment]
Edit manually your global ``composer.json`` to remove all unused packages:
in ``C:\Users\Gildonei\AppData\Roaming\Composer``
Then:
``composer global update``
It seems you have an old version of Ubiquity classes in the global composer file

Then restart the procedure:

> only the update of the devtools is global

``composer global require phpmv/ubiquity-devtools:dev-master``
and ``Ubiquity version`` should display:
**Ubiquity devtools (1.2.7)**
Then you can create a new project:
``Ubiquity new test -a``
In the new project folder, you can switch all to dev-master:
``composer require phpmv/ubiquity:dev-master``
``composer require phpmv/ubiquity-webtools:dev-master``

**Comment by gildonei** [comment]
**Step 1:** Remove unused packages - **OK**
<blockquote>
Edit manually your global composer.json to remove all unused packages:
in C:\Users\Gildonei\AppData\Roaming\Composer
Then:
composer global update
It seems you have an old version of Ubiquity classes in the global composer file
</blockquote>
**Result composer.json file**
```
{
    "require": {
        "phpmv/ubiquity-devtools": "dev-master"
    }
}
```
**Step 2:** - Check version - **OK**
```
C:\wamp64\www\ubiquity>ubiquity version

    · PHP 7.1.9
    · Ubiquity devtools (1.2.7)
```
**Step 1:** - **OK**

**Comment by jcheron** [comment]
Yes, for the moment it's normal,
the error comes from the old webtools integrated in Ubiquity 2.1.4 which did not have a constant ``version``

**Comment by gildonei** [comment]
Continuing

**Step 6:** Update ubiquity to dev-master - **OK**
`composer require phpmv/ubiquity:dev-master`

**Step 7:** Run in browser http://ubiquity.local - **ERROR**

```
Fatal error: Declaration of Ubiquity\controllers\admin\traits\ModelsTrait::showSimpleMessage($content, $type, $title = NULL, $icon = 'info', $timeout = NULL, $staticName = NULL): Ajax\semantic\html\collections\HtmlMessage must be compatible with Ubiquity\controllers\semantic\MessagesTrait::showSimpleMessage($content, $type, $title = NULL, $icon = 'info', $timeout = NULL, $staticName = NULL, $closeAction = NULL): Ajax\semantic\html\collections\HtmlMessage in C:\wamp64\www\ubiquity\html\vendor\phpmv\ubiquity-webtools\src\Ubiquity\controllers\admin\UbiquityMyAdminBaseController.php on line 67
```

**Step 8:** Update webtools to dev-master - **OK**
`composer require phpmv/ubiquity-webtools:dev-master`

**Step 9:** Run in browser http://ubiquity.local - **ERROR**

```
Fatal error: Declaration of Ubiquity\controllers\admin\traits\ModelsTrait::showSimpleMessage($content, $type, $title = NULL, $icon = 'info', $timeout = NULL, $staticName = NULL): Ajax\semantic\html\collections\HtmlMessage must be compatible with Ubiquity\controllers\semantic\MessagesTrait::showSimpleMessage($content, $type, $title = NULL, $icon = 'info', $timeout = NULL, $staticName = NULL, $closeAction = NULL): Ajax\semantic\html\collections\HtmlMessage in C:\wamp64\www\ubiquity\html\vendor\phpmv\ubiquity-webtools\src\Ubiquity\controllers\admin\UbiquityMyAdminBaseController.php on line 67
```

**End of steps**

**Comment by jcheron** [comment]
Can you try again in the same project:
``composer require phpmv/ubiquity-webtools:dev-master#52a5478f7e94f09cf7bc3caaf1eca4cced69f6ef``
It's an update to the last commit

**Comment by gildonei** [comment]
Now It works

**Comment by jcheron** [comment]
@gildonei No negative (or positive) feedback on the maintenance part?
Have you tried **comingSoon** mode as well?

**Comment by gildonei** [comment]
Hi @jcheron. I didn't had time enought to test this feature until now.
I really enjoyd this feature.
- Simply to activate/deactivate
- Schedule for auto deactivate  
- Be able to configure ports, hosts and others URLs.
- All animations and default text/icon were well choosed. 

A great job as always. 

Thank you again for all your work.

**Comment by jcheron** [comment]
Thank you for this feedback @gildonei 
I will leave this issue open to give others the opportunity to react.
A few acceptance tests, some documentation, and we can integrate this into version **2.2.0**

A small correction about deactivation: it is not automatic.
The countdown is only an indication to users.
![image](https://user-images.githubusercontent.com/2511052/60438305-adc09500-9c10-11e9-904d-fa70f1f39f74.png)

**Comment by gildonei** [comment]
Deactiovation: understood, anyway is a good resource for visitors to have an estimated time.
