### ISSUE TITLE
[break] Ubiquity 2.1.5 will be 2.2.0

### ISSUE THREAD

**Issue by jcheron** [phpMv/ubiquity#50]
The next version of ubiquity will introduce some breaking changes.

Some classes have been relocated.
- ``CodeUtils``->``Ubiquity\utils\base\CodeUtils``
- ``HasModelViewerInterface``->``Ubiquity\controllers\crud\interfaces\HasModelViewerInterface``
- ``ModelViewer``->``Ubiquity\controllers\crud\viewers\ModelViewer``

The webtools will no longer be part of the main repository but will be in their own repository:
[phpmv/ubiquity-webtools](https://github.com/phpMv/ubiquity-webtools)

The purpose of this separation is to optimize Composer autoloading. In production, webtools are not necessarily useful.

This version will therefore be a minor version ``2.2.0`` and not a patch version ``2.1.5``.

**Comment by gildonei** [comment]
Error after composer require
`Fatal error: Declaration of Ubiquity\controllers\admin\traits\ModelsTrait::showSimpleMessage($content, $type, $title = NULL, $icon = 'info', $timeout = NULL, $staticName = NULL): Ajax\semantic\html\collections\HtmlMessage must be compatible with Ubiquity\controllers\semantic\MessagesTrait::showSimpleMessage($content, $type, $title = NULL, $icon = 'info', $timeout = NULL, $staticName = NULL, $closeAction = NULL): Ajax\semantic\html\collections\HtmlMessage in C:\wamp64\www\ubiquity\html\vendor\phpmv\ubiquity-webtools\src\Ubiquity\controllers\admin\UbiquityMyAdminBaseController.php on line 67`

**Comment by jcheron** [comment]
Version ``2.2.0`` is released, including the **Maintenance** section (see https://github.com/phpMv/ubiquity/issues/49).
Consider updating the devtools to migrate:
If they are installed globally:
``composer global update``

See the [CHANGLOG](https://github.com/phpMv/ubiquity/blob/master/CHANGELOG.md) file for changes
