### ISSUE TITLE
[RFC] Migrations

### ISSUE THREAD

**Issue by gildonei** [phpMv/ubiquity#51]
## Summary

Create a native integration with PHP Phinx to generate database sync and throught developement, tests and production servers

## Motivation

Almost all developers have to maintain code and database up-to-date and it includes deploy databases fixes and new features through those different servers.

## Compatibility with Ubiquity's philosophy 

Indicate compatibility or improvements in:
- ease of use
- code standardization
- framework resources
- agility on database maintenance

## Expected results

A easy way to deploy database modifications through different servers 

## Additional context

Project on Github - https://github.com/cakephp/phinx
Docs - https://book.cakephp.org/3.0/en/phinx.html

**Comment by jcheron** [comment]
Ubiquity does not currently have a migration system, and it is a good thing to talk about it :)
I don't know Phinx, but after looking at the documentation, I find that the developer has a lot to do.

I imagined for Ubiquity something more automated.

- If the database has been modified => generation of the class update code.
- If the models have been modified => generation of the database update code.
- These code generations could be modified by the developer, and can be executed on demand

**Comment by gildonei** [comment]
- If the database has been modified => generation of the class update code.
    - How do you imagine Ubiquity will check for modifications? Something like `ubiquity migrate dbcheck` in devtools?
- If the models have been modified => generation of the database update code.
    - How do you imagine Ubiquity will check for modifications? Something like `ubiquity migrate modelcheck` in devtools?
- These code generations could be modified by the developer, and can be executed on demand
    - By code generated you mean the result code generated and read to execute deploy

Also, i think it could have some Callbacks like _beforeDeploy_ and _afterDeploy_ where users could run some sql or script to execute something

**Comment by jcheron** [comment]
ping @suresh- who had already covered this subject in [the tchat room](https://gitter.im/ubiquity-framework/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

@gildonei Yes for ``devtools``, and for ``before`` and ``after`` methods,
they're good ideas.
Also to be integrated in the Models part of the ``webtools``

**Comment by UlasSAYGINIM** [comment]
What will be done for this issue? what is the plan? how migration will work and the beforeDeploy and afterDeploy how it will work? I wonder could you mention here more?

**Comment by jcheron** [comment]
It took a while, but better late than never.
The `2.4.8` version of Ubiquity integrates a migration system.
But it is not a migration system comparable to other frameworks, by choice:
No php code generation, or code to write, but a simple database update system, from existing models.

## Example : After adding the age and email members in the User model:

```php
class User {
	...
	
	#[Column(name: "age",dbType: "int(11)")]
	private $age;
	
	#[Column(name: "email",dbType: "varchar(255)")]
	#[Validator(type: "email",constraints: ["notNull"=>true])]
	#[Validator(type: "length",constraints: ["max"=>255])]
	private $email;
	...
}
```

Note that devtools now have a command to generate or modify models from scratch:
```bash
Ubiquity model
```
![image](https://user-images.githubusercontent.com/2511052/144327201-67008740-bcb3-426b-8574-f48448c326a8.png)

### Migration from the devtools :
```bash
Ubiquity info-migrations
```
to retrieve the list of modifications to do on the DB:
![image](https://user-images.githubusercontent.com/2511052/144325198-c6441a24-333f-4ce5-af4b-6478cc23eecb.png)

```bash
Ubiquity migrations
```
to implement these modifications:
![image](https://user-images.githubusercontent.com/2511052/144325352-fcde924a-0607-40f2-a5fc-7630eaa0656c.png)


### Or from the Webtools
In the `Models` part, choose `Reverse engineering`, then `Database migrations`:

![image](https://user-images.githubusercontent.com/2511052/144326231-060ae40c-72b4-4ccf-961e-34b40e3376f6.png)

## Update of models from the database
It is possible to generate the classes again, if the database has been restructured.
```bash
Ubiquity all-models
```
Note that the generation preserves the methods of the models that have been implemented/customized.

**Comment by gildonei** [comment]
Fantastic samples and implementation. I would like just to add a note about Integer Types in MySQL 8.0.17, that length attributes are now deprecated and will be removed

```
* https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html

As of MySQL 8.0.17, the display width attribute is deprecated for integer data types; you should expect support for it to be removed in a future version of MySQL.

If you specify ZEROFILL for a numeric column, MySQL automatically adds the UNSIGNED attribute to the column.

As of MySQL 8.0.17, the ZEROFILL attribute is deprecated for numeric data types; you should expect support for it to be removed in a future version of MySQL. Consider
```

**Comment by jcheron** [comment]
> I would like just to add a note about Integer Types in MySQL 8.0.17, that length attributes are now deprecated and will be removed

I left unchanged for the moment. Mysql supports well the `int` at the declaration, but when we require the type, the returned value is for the moment `int(11)` with `SHOW COLUMNS`:

![image](https://user-images.githubusercontent.com/2511052/147885164-6f34a907-7f2e-4d9d-8dc3-19f7f195b533.png)
