### ISSUE TITLE
[RFC] E-mail module

### ISSUE THREAD

**Issue by gildonei** [phpMv/ubiquity#56]
## Summary

Module to send authenticated e-mail using SMTP

## Motivation

Almost all if not all websites or web systems have at least one contact form or a feature that needs to send an e-mail to someone.

## Compatibility with Ubiquity's philosophy 

Indicate compatibility or improvements in:
- performances
- ease of use
- code standartization

## Expected results

Be possible to configure (maybe in config.php) e-mail accounts (sender name, sender e-mail, smtp, port, host, encryption method, encoding, other info) and use it to send authenticated e-mails, trying to avoid span and server errors.

## Additional context

Framework could use PHPMailer (https://github.com/PHPMailer/PHPMailer) or have a list of Mailer sender pre-built were developers could choose on framework installation just like they can choose theme and jslib to install on framework

**Comment by jcheron** [comment]
see https://github.com/phpMv/ubiquity-mailer

**Comment by gildonei** [comment]
I will start test this new feature.

**Comment by gildonei** [comment]
Hi @jcheron does this package need an specific version of Ubiquity?

```
C:\wamp64\www\ubiquity\html>ubiquity version

    · The project folder is C:\wamp64\www\ubiquity\html

    · PHP 7.3.12
    · Ubiquity devtools (1.2.12)
    · Ubiquity Webtools (2.1.5)
    · Ubiquity 2.3.3
```
It doesn't display the mail functionalities. I got this version running ubiquity self-update and updating the global and local file project

**Comment by jcheron** [comment]
Hi @gildonei 
The latest version of the devtools requires php 7.4
And only then you can make a `composer update`.

If you create a new project, it puts you an earlier version of Ubiquity (as you are in php 7.3).

Without going through version 7.4, you can test by passing devtools on the `dev-test-mailer` branch:
```
composer global require phpmv/ubiquity-devtools:dev-test-mailer
```

**Comment by gildonei** [comment]
```
C:\wamp64\www\ubiquity>ubiquity project mailer -b=dsv_ubiquity -s=192.168.0.70 -u=root -w=pswd -a -i="http://ubiquity.local" -e="/"

    · Files copy...

    · Config files creation...

     ╭──────────────────────────────────────────╮
     │      ■ info : Command line arguments     │
     │      · projectName='mailer'              │
     │      · cssFiles=''                       │
     │      · jsFiles=''                        │
     │      · injections=''                     │
     │      · dbName='dsv_ubiquity'             │
     │      · dbType='1'                        │
     │      · serverName='192.168.0.70'         │
     │      · port='1'                          │
     │      · user='root'                       │
     │      · password='pswd'            │
     │      · all-models=''                     │
     │      · admin='1'                         │
     │      · themes='1'                        │
     │      · siteUrl='1'                       │
     │      · rewriteBase='/'                   │
     ╰──────────────────────────────────────────╯
     ╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
     │      ■ error                                                                                                                                                  │
     │                                                                                                                                                               │
     │      · Message : Class 'Ubiquity\controllers\Controller' not found                                                                                            │
     │      · File : C:\Users\Junior\AppData\Roaming\Composer\vendor\phpmv\ubiquity-webtools\src\Ubiquity\controllers\admin\UbiquityMyAdminBaseController.php        │
     │      · Line :  69                                                                                                                                             │
     ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by jcheron** [comment]
it seems that you have installed (probably by accident) ubiquity-webtools globally...
They need to be removed.
```
composer global remove phpmv/ubiquity-webtools
```

**Comment by gildonei** [comment]
An odd thing happend. My console is getting stucked 

```
C:\wamp64\www\ubiquity>ubiquity project mailer -b=dsv_ubiquity -s=192.168.0.70 -u=root -w=pswd -a -i="http://ubiquity.local" -e="/"

    · The mailer folder already exists !

Would you like to continue ? (y/n)
```
Any ideia? Alread removed "mailer" dir and continue freezed.

```
C:\wamp64\www\ubiquity>ubiquity project mailer -b=dsv_ubiquity -s=192.168.0.70 -u=root -w=pswd -a -i="http://ubiquity.local" -e="/"

    · Files copy...

    · Config files creation...

     ╭───────────────────────────────────────────────╮
     │      ■ info : Command line arguments          │
     │      · projectName='mailer'                   │
     │      · cssFiles=''                            │
     │      · jsFiles=''                             │
     │      · injections=''                          │
     │      · dbName='dsv_ubiquity'                  │
     │      · dbType='mysql'                         │
     │      · serverName='192.168.0.70'              │
     │      · port='3306'                            │
     │      · user='root'                            │
     │      · password='pswd'                        │
     │      · all-models=''                          │
     │      · admin='1'                              │
     │      · themes=''                              │
     │      · siteUrl='http://ubiquity.local'        │
     │      · rewriteBase='/'                        │
     ╰───────────────────────────────────────────────╯

    · Creating the Controller Admin at the location app/controllers/Admin.php


    · Composer file creation...

Do you want to run composer install ? (y/n)

```
I can't type "y" or any other key, It simply stop responding.

**Comment by jcheron** [comment]
Try reinstalling the devtools by first deleting the `C:\Users\Junior\AppData\Roaming\Composer\vendor\phpmv` folder...
Maybe in another console than the one that got stuck, and using a different project name.

**Comment by gildonei** [comment]
Same problem.
Removed all folders and files with ubiquity and the console problem continues.
Plus tried in another PC with Wamp too (Win10 + Updates + Wamp 3.2.2.2 x64)

**Comment by jcheron** [comment]
you seem to have a problem with dealing with composer...
Can you create a project with the **create-project** command (without the devtools) ?
`composer create-project phpmv/ubiquity-project mailerTest`

**Comment by gildonei** [comment]
Project created.
I guess it has something how Console::question read capture from stdin

**Comment by jcheron** [comment]
Strange, nothing has changed in this area recently
It's just a ` fgets(STDIN)`

**Comment by gildonei** [comment]
Tried Copy/Paste answer ( Y ) to console, but it also don't paste anything.
Tried PowerShell and nothing too.

**Comment by gildonei** [comment]
I think I found the problem. It appears to be in the loop to read stdin. I echoed a string in method readline and It was in infinite loop and didn't allowed me to type anything in console.

For tests purpose I removed the loop and changed readline function;
```
#Line 6
- return rtrim(fgets($input));
+ return readline();

#Line 24
- do{

#Line 26
- }while(array_search($answer, $propositions)===false);
```

**Comment by gildonei** [comment]
Getting back to this module:

- Add a button to test config to send a default email, just like Outlook do to validate email settings

**Comment by gildonei** [comment]
A little bug:

1. Add mailer class
2. Fill a name with space
3. Result: OK and Error (image 1)
4. Will get an error when try to access mailer module again (image 2)

![image](https://user-images.githubusercontent.com/1370979/73446535-b8c0dc80-433b-11ea-8ad9-897e254d3c12.png)

![image](https://user-images.githubusercontent.com/1370979/73446628-d7bf6e80-433b-11ea-85f6-b4e25ad04faf.png)

**Comment by gildonei** [comment]
Bug 2: Editing a mailer class, doesn't save data:

1. Click on "eye" button on created Mailer Class (step before)
2. Click on "edit button"
3. Fill the new data
4. Doesn't exist a save / update button, close button just close and cancel, send button just send, but don't save data
5. Attachments dir, can't be filled

![image](https://user-images.githubusercontent.com/1370979/73448952-d3e21b00-4340-11ea-95dc-d31c22923852.png)

**Comment by gildonei** [comment]
Bug 3: Editing mailer config options (blank list and default unsecure)

1. Access Mailer module
2. Click on Mailer Configuration button (here also there are a blank list menu next to Cancel deletions button in the end of form fields)
3. Click on Add default config
4. Select SMTP options (secure) -> SSL fields will be displayed
5. Select SMTP options (unsecure!) --> SSL fields keep being displayed

![image](https://user-images.githubusercontent.com/1370979/73449646-6931df00-4342-11ea-9ba2-5cdd3cf50209.png)

**Comment by gildonei** [comment]
Doubt about saved config

After try to send an email, with saved config, got an error

![image](https://user-images.githubusercontent.com/1370979/73449993-2c1a1c80-4343-11ea-9a05-12189285de0d.png)

```
array(
	"host"=>"smtp.domain.com.br", (also tried withou smtp on protocol)
	"port"=>587, (it's OK)
	"auth"=>true,
	"user"=>"email@domain.com.br", (filled with a valid e-mail)
	"password"=>"my-email-pswd", (same here)
	"protocol"=>"smtp", (it's ok)
	"ns"=>"smtp" (tried with smtp, mail, blank)
	)
```
All config results in error on send

**Comment by jcheron** [comment]
> All config results in error on send
Try adding the SMTP Unsecure options (since your http server is local)

**Comment by gildonei** [comment]
I made tests using both Secure and Unsecure settings. Also triyed removing and re-creating project from scratch. Got same errors.

**Comment by jcheron** [comment]
When I test with Google mail, I use this configuration:
```
array(
	"host"=>"smtp.gmail.com",
	"port"=>587,
	"auth"=>true,
	"user"=>"*********@gmail.com",
	"password"=>"********",
	"protocol"=>"smtp",
	"ns"=>"mail",
	"from"=>array(
			"address"=>"*********@gmail.com",
			"name"=>"me"
			),
	"SMTPOptions"=>array(
			"ssl"=>array(
					"verify_peer"=>false,
					"verify_peer_name"=>false,
					"allow_self_signed"=>true
					)
			)
	)
```
The parameter **ns** corresponds to the php namespace of the created mail classes.

I don't know what the characteristics of your mail server are...
I don't know what's in your created mail class either.

**Comment by gildonei** [comment]
I will try with something like your config above. Will use a gmail account. If it works, will try again with my email account. About my mail server, I use it with PHPMailer with no problems, setting default config, smtp, auth, from, login, pswd, etc. I will run more tests

**Comment by gildonei** [comment]
Hi @jcheron,

I try to describe all the steps and please, if possilble, specify the corrections, so this way I also be able to create a step-by-step tutorial for documentation

1. On webtools (admin)
2. Access Mailer option
3. Add mailer class 
4. Created "Mailer" (left created associated view unchecked - i don't know where to use it)
5. Save
6. Access Mailer Configuration
7. Fill the form and save.
8. Create a controller named TestController
9. Create an action index in TestController
10. In TestController, included mail\Mailer and MailerManager
```
use mail\Mailer;
use Ubiquity\mailer\MailerManager;
```
11. In `index` action, did the following
```
$mail = new Mailer();
$mail->from('junior@lupainformatica.com.br', 'Junior');
$mail->replyTo('desenvolvimento@lupainformatica.com.br', 'Desenvolvimento');
$mail->body('<h2>Mensagen de Teste em Html</h2>');
$mail->bodyText('Mensagen de Teste em Html');
$mail->to('gildonei.mendes@gmail.com', 'Junior');
$mail->subject = 'Mail Subject'; // Why not exist a setSubject?

MailerManager::start();
$sender = MailerManager::getMailer();
$sender->SMTPAutoTLS = 0;
$sender->SMTPSecure = '';
$sender->CharSet = 'utf-8'; 

var_dump(MailerManager::send($mail)); // Result TRUE - mail Received
```

**PS:**
```
Note 1: Message body didn't work. Received text was "Message body" not "Mensagem de Teste..."

Note 2: Even I filled Unsecure SMTP option, PHPMailer keep with SMTPAutoTLS as true and SMTPSecure as true
```

**Comment by jcheron** [comment]
I'll do a quick sample...

**Comment by jcheron** [comment]
Logically, after your step 5, you will modify your created mail class, keeping in mind that a mail class is a bit like a controller.

### Example : An email sent to all users in the database :
```php
namespace mail;

use Ubiquity\mailer\AbstractMail;
use Ubiquity\orm\DAO;
use models\User;

class AllUsers extends AbstractMail {

	protected function initialize() {
		$this->subject = 'Message test';
		$this->from("myaddressmail@gmail.com", 'jcheron');
		$this->to(DAO::getAll(User::class, '', false));
		$this->attachFile('afile.pdf');
	}

	public function body() {
		$date = (new \DateTime())->format('c');
		$user = DAO::getOne(User::class, 1);
		$body = '<h2>Message</h2><div>Message content</div>';
		$content = $this->loadView('mailer/AllUsers.html', \compact('date', 'user', 'body'));
		return $content;
	}

	public function bodyText() {
		return 'This message has a text version';
	}
}
```

- **initialize()** is automatically invoked during construction and allows to define the attributes of the mail (recipients, subject...).
- **body()** and **bodyText()** are used to build the body. These methods must return a string, and they can load views.

This message will be visible in the Mailer section of the webtools:
![image](https://user-images.githubusercontent.com/2511052/73702310-abfe0900-46ec-11ea-839d-a89e3861c785.png)

Preview:
![image](https://user-images.githubusercontent.com/2511052/73702390-f1223b00-46ec-11ea-89a0-64cc252a576b.png)
### Config
For the configuration, you can now put everything in the config file:

```php
<?php
return array(
	"host" => "host.com",
	"port" => 587,
	"auth" => true,
	"user" => "**********@gmail.com",
	"password" => "*******",
	"protocol" => "smtp",
	"ns" => "mail",
	"from" => array(
		"address" => "admin@dev.local",
		"name" => "admin"
	),
	"CharSet" => "utf-8",
	"SMTPAutoTLS"=>0,
	"SMTPSecure"=>''
);
```
The webtools interface for configuration allows you to modify the existing configuration, but without being able to add keys.

### Send
You can now:
- Send the mail with the webtools
- Send from a controller
```php
namespace controllers;

use Ubiquity\mailer\MailerManager;
use mail\AllUsers;

/**
 * Controller TestSendMail
 */
class TestSendMail extends ControllerBase {

	public function initialize() {
		MailerManager::start();
	}

	public function index() {
		$mail = new AllUsers();
		if (MailerManager::send($mail)) {
			echo 'Message sent to all users!';
		} else {
			echo 'Error sending the message';
		}
	}
}
```
- Add the message to the queue:

```php
	public function addToQueue() {
		if (MailerManager::addToQueue(AllUsers::class)) {
			echo 'Message added to queue';
			MailerManager::saveQueue(true, false);
		} else {
			echo 'Error when sending to queue';
		}
	}
```

- Send message in 1 day:
```php
	public function sendAt() {
		$date = new \DateTime();
		$date->modify('+1 day');
		MailerManager::sendAt(AllUsers::class, $date);
		MailerManager::saveQueue(true, false);
		echo 'Message will be send at ' . $date->format('c');
	}
```
![image](https://user-images.githubusercontent.com/2511052/73703892-cb4b6500-46f1-11ea-8b8d-ae6b5a45a29e.png)

- Send all messages ready in the queue:
```php
	public function sendAll() {
		$nb = MailerManager::sendQueue();
		echo "$nb sent message(s)";
	}
```
- Or a specific message
```php
	public function sendOne($index) {
		if (MailerManager::sendQueuedMail(0)) {
			echo 'The first message from the queue was sent';
		}
	}
```
### Webtools
You can do all that with webtools, too.
**Editing** (Edit button) in webtools (of messages already sent) allows you to statically modify a dynamically created message, to change its content, or the recipients before resending it.

### Devtools
It is also possible to use devtools on the command line, which allows you to create a cron for sending messages in the queue.

```
■ mailer [part] =>
        · Displays mailer classes, mailer queue or mailer dequeue.
        × Samples :
                Display mailer classes
                  · Ubiquity mailer classes
                Display mailer messages in queue(To send)
                  · Ubiquity mailer queue
                Display mailer messages in dequeue(sent)
                  · Ubiquity mailer dequeue

■ new-mail [name] =>
        · Creates a new mailer class.
        · Aliases : newMail,new:mail
        × Samples :
                Creates a new mailer class
                  · Ubiquity newMail InformationMail

■ sendMail [] =>
        · Send message(s) from queue.
        · Aliases : sendMails
        · Parameters :
                -n      shortcut of --num
                        If specified, Send the mail at the position n in queue.

        × Samples :
                Send all messages to send from queue
                  · Ubiquity semdmails
                Send the first message in queue
                  · Ubiquity sendmail 1
```

**Comment by gildonei** [comment]
I will do new tests and post results later.
