### ISSUE TITLE
Next version will be 2.3.0

### ISSUE THREAD

**Issue by jcheron** [phpMv/ubiquity#62]
### Release date
tomorrow August 1

### multi db
Version 2.3.0 will support connection to multiple databases, in a transparent way (thanks @gildonei  for its [RFC](https://github.com/phpMv/ubiquity/issues/60))

#### functioning
No more need to start the database in the `app/config/services.php` file with `DAO::startDatabase($config)`.

```php
//The connection is automatically made at the first request to the database.
$user=DAO::getById(User::class,1);
```
With several databases, the `services.php` file must include the instruction `DAO::start()`, to allow the framework to determine which base is requested for each model.

A model is defined for a database, using the `@database` annotation:

```php
namespace models\accounting;

/**
 * @database('accounting')
*/
class Products{
}
```
>You don't have to do it manually since models can be generated automatically, from webtools or devtools, for a specific connection to a database

Database connections are defined in `app/config/config.php`:
```php
return array(
	"siteUrl"=>"http://127.0.0.1:8090/",
	"database"=>array(
			"default"=>array(
					"type"=>"mysql",
					"dbName"=>"uguide",
					"serverName"=>"127.0.0.1",
					"port"=>3306,
					"user"=>"root",
					"password"=>"",
					"options"=>array(),
					"cache"=>false
					),
			"accounting"=>array(
					"type"=>"mysql",
					"dbName"=>"accounts",
					"serverName"=>"127.0.0.1",
					"port"=>3306,
					"options"=>array(),
					"user"=>"root",
					"password"=>"",
					"cache"=>false
					)
			),
```
>Connections can be managed from webtools, without having to directly modify the configuration file:

![image](https://user-images.githubusercontent.com/2511052/62219632-f786d180-b3ae-11e9-9b39-ad63e44d140b.png)

It is then possible to request the models, without worrying about the connections to the database:

In `app/config/services.php`:
```php
DAO::start();
```
In controllers:

```php
//The connection is automatically made at the first request to the default database.
$user=DAO::getById(User::class,1);
...
//The connection is automatically made at the first request to the accounting database.
$products=DAO::getAll(Products::class);
```

#### Autoloader optimization
Classes used only in development (and not in production), such as **webtools** and **devtools**, have been moved to the new [phpmv/ubiquity-dev](https://github.com/phpMv/ubiquity-dev) repository.

This moving is transparent for the developer.

Attention, in case of optimization of the autoloader for production:
```
composer install --optimize-autoloader --classmap-authoritative --no-dev
```
the removal of packages declared in `-dev` (of which ubiquity-dev is a part) then prohibits the use of webtools or devtools.

#### Startup optimization
The efficiency of the framework startup has been improved (especially in the `Startup` class)

#### Results
The benchmarks achieved (bench used: Techempower multiple queries x20) show the improvements:
![image](https://user-images.githubusercontent.com/2511052/62221709-6285d780-b3b2-11e9-943d-3dce9221bc34.png)

**Comment by gildonei** [comment]
@jcheron Congratulations for this new release and all your hard work.
