### ISSUE TITLE
cannot set database

### ISSUE THREAD

**Issue by Khairulfajeri** [phpMv/ubiquity#74]
![DeepinScreenshot_select-area_20190922212704](https://user-images.githubusercontent.com/18585608/65388616-091da180-dd80-11e9-9819-0d1ca693e92a.png)
error while set database

**Comment by jcheron** [comment]
Hi @Khairulfajeri 
Thanks for reporting!
Can you try with [this update](https://github.com/phpMv/ubiquity-devtools/commit/ce0a29fd97be714e909414b92effed86888d70f7), and tell me if the problem is solved for you?

**Comment by Khairulfajeri** [comment]
Its works

Pada tanggal Min, 22 Sep 2019 21.43, jcheron <notifications@github.com>
menulis:

**Comment by jcheron** [comment]
Thanks!
This will be available in next release (devtools 1.2.9)
