### ISSUE TITLE
[RFC] Feature request HMVC

### ISSUE THREAD

**Issue by w3yyb** [phpMv/ubiquity#84]
HMVC

multi-module applications surpoot is a very nice feature. I hope will have.
example:

`
multiple/

     apps/

       frontend/

          controllers/

          models/

          views/

          Module.php

       backend/

          controllers/

          models/

          views/

          Module.php

       public/

       ../`

**Comment by jcheron** [comment]
Thank you for this proposal @w3yyb 
We have to think about it, yes.
For the moment, I don't see how to do it without degrading the performances.

**Comment by w3yyb** [comment]
thanks .

**Comment by jcheron** [comment]
This functionality would inevitably have a negative impact on performance. If you add to this that it would probably be used at the margin, I don't see the point.
It is quite possible to create several different projects, and to share the common code between these projects via a packagist repository.

**Comment by jcheron** [comment]
For performance reasons, prefer:
- the use of domains (see https://github.com/phpMv/ubiquity/issues/169)
or
- The creation of several small Ubiquity projects (possibly linked by a common packagist library)
