### ISSUE TITLE
SQLSTATE[HY000] [2002] Cannot assign requested address

### ISSUE THREAD

**Issue by w3yyb** [phpMv/ubiquity#85]
when I benchmark this framework, some times will get the not-200 response,
and will report in the PHP  :
SQLSTATE[HY000] [2002] Cannot assign requested address

I benchmark other framework,like laravel,symfony,thinkphp etc.  No  errors will be reported.

Is some problem there?

add the $options[\PDO::ATTR_PERSISTENT]=true; will  solve this problem.

**Comment by w3yyb** [comment]
and add the $options[\PDO::ATTR_PERSISTENT]=true; will  Improve performance too.

**Comment by w3yyb** [comment]
Perhaps this framework is too performing and has too many connections, resulting in it.

**Comment by jcheron** [comment]
Could you give me your entire test procedure, and the project that goes with it, that I can reproduce?

**Comment by jcheron** [comment]
It should be sufficient to increase or set `max_connections` in the Mysql configuration

**Comment by w3yyb** [comment]
you can use : ab -n 10000 -c 100 -k http://ubiquity/  to test.
my project is use  Ubiquity new firstProject -a  created.
