### ISSUE TITLE
[RFC] mongodb database Support

### ISSUE THREAD

**Issue by w3yyb** [phpMv/ubiquity#86]
## Summary

mongodb is a very widely used nosql database with very good performance.

## Motivation

 Because it can completely replace mysql, and the performance is better and easier to use

## Compatibility with Ubiquity's philosophy 

Indicate compatibility or improvements in:
- impove performances
- ease of use

## Expected results

Provide users with a good alternative database option

**Comment by UlasSAYGINIM** [comment]
mongodb has unlimited document types and how we can manage multiple document types in mongodb? any ideas? I think mongodb can not replace mysql because mongodb is completely different. but for performance need yes mongodb seems good.

**Comment by jcheron** [comment]
The performances of **ubiquity-mongo** are good, although the Techempower benchmarks are not to the advantage of no-sql databases (multiple queries on a small volume of data).
see https://www.techempower.com/benchmarks/#section=test&runid=abfe7e62-3de0-4406-b9fb-bebda0474593&hw=ph&test=fortune&d=1k&a=2
