### ISSUE TITLE
[REST]  with POST method  returns 500 error,  and 'controllers/rest' class not found.

### ISSUE THREAD

**Issue by ghosttk** [phpMv/ubiquity#89]
Following the user's guide , I generated a rest controller from user model, and tested those GET methods , they all passed. But calling POST method like 'add' action always returns 500 error.

### Expected Result
POST methods should return 401 or 200.

### Actual Result

[Fri Dec 13 03:36:24 2019] PHP Fatal error:  Uncaught Error: Class 'controllers\rest' not found in /home/ww/projects/php/Ubiquity/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php:38
Stack trace:
#0 /home/ww/projects/php/Ubiquity/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php(142): Ubiquity\controllers\Startup::getControllerInstance('controllers\\res...')
#1 /home/ww/projects/php/Ubiquity/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php(111): Ubiquity\controllers\Startup::runAction(Array, true, true)
#2 /home/ww/projects/php/Ubiquity/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php(72): Ubiquity\controllers\Startup::forward('rest/orgas/add')
#3 /home/ww/projects/php/Ubiquity/.ubiquity/_index.php(18): Ubiquity\controllers\Startup::run(Array)
#4 /home/ww/projects/php/Ubiquity/.ubiquity/.htrouter.php(5): include_once('/home/ww/projec...')
#5 {main}
  thrown in /home/ww/projects/php/Ubiquity/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php on line 38

### Versions
· PHP 7.4.0
    · Ubiquity devtools (1.2.11)
    · Ubiquity Webtools (2.3.2)
    · Ubiquity 2.3.2

- OS
    manjaro

**Comment by jcheron** [comment]
Hi @ghosttk 
It seems that the router doesn't recognize the route `/rest` you created.
Can you do the usual checks:
- You must do a prior connection with `rest/connect` to obtain a valid token:
![image](https://user-images.githubusercontent.com/2511052/70717002-c23fa800-1ced-11ea-8419-e4f3630af2e1.png)
- Then use the `post` method
![image](https://user-images.githubusercontent.com/2511052/70716892-899fce80-1ced-11ea-93dd-1f311249f68c.png)

#### The result;
![image](https://user-images.githubusercontent.com/2511052/70717222-32e6c480-1cee-11ea-8690-c08c8aa50b33.png)

**Comment by ghosttk** [comment]
Actually I did do a prior connection with rest/connect  before POST rest/add,  but still got 500 error

**Comment by jcheron** [comment]
The message indicates a routing problem.
You had selected the `post` method well?

**Comment by ghosttk** [comment]
This time it works， it is because I forgot to change the method from GET to POST. 
I was thinking the default method is set to POST when testing the rest/add route.
Thanks a lot. By the way, Ubiquity is the best php framework I knew!!!

**Comment by jcheron** [comment]
Thank you!
With the last commit, if you use the wrong HTTP method, a 404 error is returned (instead of 500)
