### ISSUE TITLE
strpos usage deprecation warning

### ISSUE THREAD

**Issue by ekscrypto** [phpMv/ubiquity#9]
### strpos usage deprecation warning

PHP Deprecated:  strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /Users/ekscrypto/dev/ubiquityProject/vendor/phpmv/php-mv-ui/Ajax/service/JString.php on line 6

### Steps
`Ubiquity serve` a new project
Use any of the UbiquityMyAdmin pages, check the console logs

### Expected Result
No deprecation warning visible

### Actual Result
strpos warning shown, see above

### Versions
- Ubiquity framework dev-master (2019-02-26)
- Ubiquity devtools 1.1.5
- php 7.3.2

**Comment by jcheron** [comment]
This is probably a [phpMv-UI](https://github.com/phpMv/phpMv-UI) issue,
I'll see at first if Ubiquity can do without these calls

**Comment by jcheron** [comment]
For me, fixed in last https://github.com/phpMv/phpMv-UI/commit/07e2746ebaab9ac7103a0af797599515a948a038 commit ,
to confirm...

**Comment by ekscrypto** [comment]
Deprecation warning replaced with empty warning:

[Wed Feb 27 13:52:38 2019] PHP Warning:  strpos(): Empty needle in /Users/ekscrypto/dev/ubiquityProject/vendor/phpmv/php-mv-ui/Ajax/service/JString.php on line 6

**Comment by jcheron** [comment]
Bizarre,
you're sure to have the last commit phpMv-UI?
Non-empty string checking is performed

**Comment by ekscrypto** [comment]
I updated the two files by hand but apparently I missed a change somewhere, refreshing the repo using `composer update` properly updated me to your latest code and the issue is resolved.  Thanks!
