### ISSUE TITLE
SqLite doesn't work

### ISSUE THREAD

**Issue by Andrew-Sirius** [phpMv/ubiquity#90]
How possible to connect to the sqlite database?
Now Ubiquity has only one way to connect:
```
public function getDSN(string $serverName, string $port, string $dbName, string $dbType = 'mysql') {
    $charsetString = [ 'mysql' => 'charset=UTF8','pgsql' => 'options=\'--client_encoding=UTF8\'','sqlite' => '' ] [$dbType] ?? 'charset=UTF8';
    return $dbType . ":dbname={$dbName};host={$serverName};{$charsetString};port=" . $port;
}
```
And it is not working.
```
sqlite://root:root@127.0.0.1:3006//absolute/path/to/project/app/config/db/database.sqlite
```
---
The correct connect string should look like this:
```
sqlite:/absolute/path/to/project/app/config/db/database.sqlite
```

**Comment by ghosttk** [comment]
I put a 'database.sqlite'  file into the project's root directory and set dbname to database.sqlite in the app/config/config.php using relative path, it seems to successfully connect, but got a PDOException.

[Sun Dec 15 00:50:31 2019] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 near "SHOW": syntax error in /home/ww/projects/php/Ubiquity/vendor/phpmv/ubiquity/src/Ubiquity/db/providers/pdo/PDOWrapper.php:114
Stack trace:
#0 /home/ww/projects/php/Ubiquity/vendor/phpmv/ubiquity/src/Ubiquity/db/providers/pdo/PDOWrapper.php(114): PDO->query('SHOW TABLES')
#1 /home/ww/projects/php/Ubiquity/vendor/phpmv/ubiquity/src/Ubiquity/db/traits/DatabaseMetadatas.php(19): Ubiquity\db\providers\pdo\PDOWrapper->getTablesName()
#2 /home/ww/projects/php/Ubiquity/vendor/phpmv/ubiquity-webtools/src/Ubiquity/controllers/admin/traits/CheckTrait.php(179): Ubiquity\db\Database->getTablesName()
#3 /home/ww/projects/php/Ubiquity/vendor/phpmv/ubiquity-webtools/src/Ubiquity/controllers/admin/traits/CheckTrait.php(101): Ubiquity\controllers\admin\UbiquityMyAdminBaseController->getModelsWithoutTable(Array, 'default')
#4 /home/ww/projects/php/Ubiquity/vendor/phpmv/ubiquity-webtools/src/Ubiquity/controllers/admin/traits/CheckTrait.php(74): Ubiquity\controllers\ad in /home/ww/projects/php/Ubiquity/vendor/phpmv/ubiquity/src/Ubiquity/db/providers/pdo/PDOWrapper.php on line 114
[Sun Dec 15 00:50:31 2019] 127.0.0.1:44678 Closing

**Comment by Andrew-Sirius** [comment]
> I put a 'database.sqlite' file into the project's root directory and set dbname to database.sqlite in the app/config/config.php using relative path, it seems to successfully connect, but got a PDOException.
> 
> **_
> 
> ```
> > [Sun Dec 15 00:50:31 2019] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 near "SHOW": syntax error in /home/ww/projects/php/Ubiquity/vendor/phpmv/ubiquity/src/Ubiquity/db/providers/pdo/PDOWrapper.php:114
> > Stack trace:
> > #0 /home/ww/projects/php/Ubiquity/vendor/phpmv/ubiquity/src/Ubiquity/db/providers/pdo/PDOWrapper.php(114): PDO->query('SHOW TABLES')
> > #1 /home/ww/projects/php/Ubiquity/vendor/phpmv/ubiquity/src/Ubiquity/db/traits/DatabaseMetadatas.php(19): Ubiquity\db\providers\pdo\PDOWrapper->getTablesName()
> > #2 /home/ww/projects/php/Ubiquity/vendor/phpmv/ubiquity-webtools/src/Ubiquity/controllers/admin/traits/CheckTrait.php(179): Ubiquity\db\Database->getTablesName()
> > #3 /home/ww/projects/php/Ubiquity/vendor/phpmv/ubiquity-webtools/src/Ubiquity/controllers/admin/traits/CheckTrait.php(101): Ubiquity\controllers\admin\UbiquityMyAdminBaseController->getModelsWithoutTable(Array, 'default')
> > #4 /home/ww/projects/php/Ubiquity/vendor/phpmv/ubiquity-webtools/src/Ubiquity/controllers/admin/traits/CheckTrait.php(74): Ubiquity\controllers\ad in /home/ww/projects/php/Ubiquity/vendor/phpmv/ubiquity/src/Ubiquity/db/providers/pdo/PDOWrapper.php on line 114
> > [Sun Dec 15 00:50:31 2019] 127.0.0.1:44678 Closing
> ```
> 
> _**

Yes! Because the connection string is wrong

**Comment by jcheron** [comment]
Sorry, it seems that Ubiquity is not ready for SQLite.
The connection string is not valid, and some SQLite SQL specificities are not currently managed.

While waiting for an update, if you are looking for an embedded and high-performance solution tested with Ubiquity, I recommend Tarantool.

**Comment by jcheron** [comment]
I made an update temporarily fixing the sqlite DSN problem.
I'm talking about a temporary update since:
- **Sqlite** is not fully implemented (no possible generation of classes and some webtools features are not operational)
- The next version of **Ubiquity** should include a Db configuration with DSN (it will no longer be generated at runtime)

**Comment by UlasSAYGIN** [comment]
waiting for pr request review.
