### ISSUE TITLE
help as default in Ubiquity 

### ISSUE THREAD

**Issue by a1git** [phpMv/ubiquity#91]
when just the binary Ubiquity is called, the output is confusing: 
     ╭─────────────────────────────────────────────╮
     │      ■ warning                              │
     │      · The command does not exists!         │
     ╰─────────────────────────────────────────────╯

Please change it such that "help" is the default parameter if nothing exists.  This will also be in line with how other command line tools behave.

**Comment by jcheron** [comment]
Fixed in [Ubiquity-devtools 1.2.12](https://github.com/phpMv/ubiquity-devtools/releases/tag/1.2.12)
