### ISSUE TITLE
[class PDOWrapper ] can not get list of tables from postgresql database

### ISSUE THREAD

**Issue by UlasSAYGINIM** [phpMv/ubiquity#98]
### Steps

just change config for database connection on UbiquityMyadmin and test it.
it will connect but when you click models on Myadmin, you will get error.

 [PDOWrapper] gives error on UbiquityMyadmin > models section  when you want to use 

PDOWrapper does not have necessary query to get tables from postgresql database
like this 
$query = $this->dbInstance->query ( 'SELECT * FROM pg_catalog.pg_tables WHERE schemaname != \'pg_catalog\' AND schemaname != \'information_schema\';'  ); // instead of 'SHOW TABLES'

on line 117

quick-start\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\PDOWrapper.php:117

### Expected Result
show models page.
### Actual Result
Message : Uncaught PDOException: SQLSTATE[42704]: Undefined object: 7 Error: "tables" unknown configuration parameters in C:\PHP_Examples\quick-start\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\PDOWrapper.php:117 Stack trace: #0 C:\PHP_Examples\quick-start\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\PDOWrapper.php(117): PDO->query('SHOW TABLES') #1 C:\PHP_Examples\quick-start\vendor\phpmv\ubiquity\src\Ubiquity\db\traits\DatabaseMetadatas.php(19): Ubiquity\db\providers\pdo\PDOWrapper->getTablesName() #2 C:\PHP_Examples\quick-start\vendor\phpmv\ubiquity-webtools\src\Ubiquity\controllers\admin\traits\CheckTrait.php(179): Ubiquity\db\Database->getTablesName() #3 C:\PHP_Examples\quick-start\vendor\phpmv\ubiquity-webtools\src\Ubiquity\controllers\admin\traits\CheckTrait.php(101): Ubiquity\controllers\admin\UbiquityMyAdminBaseController->getModelsWithoutTable(Array, 'default') #4 C:\PHP_Examples\
    File : C:\PHP_Examples\quick-start\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\PDOWrapper.php
    Line : 117
### Versions
· PHP 7.4.1
· Ubiquity devtools (1.2.12)
· Ubiquity Webtools (2.3.3)
· Ubiquity 2.3.3
- windows 10

**Comment by UlasSAYGINIM** [comment]
I think it also does not see all tables and not creating models from database.
I couldnt do it. maybe need another code update.

**Comment by jcheron** [comment]
Thank you for this report @UlasSAYGINIM 
Indeed, the implementation of the `PDOWrapper` class is incomplete. It currently only manages the meta-data extraction for **Mysql**.

I will first relocate the concerned methods, to prepare the implementation for the other drivers.

**Comment by UlasSAYGINIM** [comment]
Models generation

    Database is well configured
    Attempt to connect to the database postgres ...
    Models namespace models is ok.
    The directory for models namespace C:\PHP_Examples\quick-start\.ubiquity\..\app\models\ exists.

Models generation

    No file found in C:\PHP_Examples\quick-start\.ubiquity\..\app\models\ folder.

**Comment by UlasSAYGINIM** [comment]
@jcheron  thank you for update and i think model creation is not possible for the same reason you said.
can we get all models created from database after this PDOwrapper update? or you need to add new codes to do it? is there any other incomplete places?

**Comment by jcheron** [comment]
A `PgsqlDriverMetas` class inheriting from `AbstractDriverMetaDatas` is already missing...

**Comment by UlasSAYGINIM** [comment]
why not, if  i can , i will.

**Comment by jcheron** [comment]
We're working on the https://github.com/phpMv/ubiquity/tree/add-pdo-driver-metas branch.
The priority may be to the `PgsqlDriverMetas` class, to be implemented on the model of the equivalent [Mysql](https://github.com/phpMv/ubiquity/blob/add-pdo-driver-metas/src/Ubiquity/db/providers/pdo/drivers/MysqlDriverMetas.php) class.

**Comment by UlasSAYGINIM** [comment]
I noticed the branch from your commit , thank you for it.
I will also look sqllite ,redis and mongodb. but for redis and mongo, which class to edit or wrapper to do? did you create them? i havent look them yet on branch , i am asking firstly. I am also new for project not knowing all things. you may speed me up.

**Comment by jcheron** [comment]
Postgres and SQLite are the easiest to implement. It's better to start with this.
For Redis and MongoDb, there is none existing.
And for MongoDb, it seems impossible for the moment, since ORM has an exclusively SQL approach.

**Comment by UlasSAYGINIM** [comment]
can you do me favor? can you create empty classes ? I can fill them.
It will take more time to look framework to decide. instead of deciding, i can fill.
I know postgres and sql lite easy and because of this , i want to look redis and mongodb later.

**Comment by UlasSAYGINIM** [comment]
I will go to buy coffee , it is run out. I will come in 1 hour. see you.

**Comment by jcheron** [comment]
You have to look at the [MysqlDriverMeta](https://github.com/phpMv/ubiquity/blob/add-pdo-driver-metas/src/Ubiquity/db/providers/pdo/drivers/MysqlDriverMetas.php) class for the output format of the php arrays

**Comment by UlasSAYGINIM** [comment]
I was thinking redis and mongodb for empty classes and i forgot to say. sorry about that.
I will add SQL lite and postgresql when i fnished tests.
then i will look redis and mongodb. because i didnt use it before, i have to learn.

**Comment by UlasSAYGINIM** [comment]
I think models for mongodb, will be more different than RDMS because collections has different data types for each record which is completely different than postgresql,mysql.

**Comment by jcheron** [comment]
For **Redis**, it will be in a new **ubiquity-redis** repository, which doesn't exist yet...
Yes, for Mongo, I also have big doubts about the feasibility given the existing SQL-oriented implementation

**Comment by UlasSAYGINIM** [comment]
i think both must be seperated from RDMS, for mongodb we may consider new repository too.
ubiquity-mongodb :)

**Comment by UlasSAYGINIM** [comment]
@jcheron hi, pgsql driver is ok but i have another problem.
it creates models and when i want to see data for model.
it creates this query : SELECT connection.id,connection.dateCo,connection.url,connection.idUser FROM connection WHERE 1=1 LIMIT 6 OFFSET 0

but for postgresql , there is an error, it can not find column names unless you get them in connection."dateCo"

In fact , it seems all filed names are safe with double quote. where i can change this behaviour?
I couldnt find statement prepare point.

**Comment by jcheron** [comment]
PDO drivers quoted chars are defined in **PDOWrapper** class:
https://github.com/phpMv/ubiquity/blob/3a8d703b17ca49ef1f2b9863444daffd704448c9/src/Ubiquity/db/providers/pdo/PDOWrapper.php#L18

**Comment by UlasSAYGINIM** [comment]
Thank you for help.
I looked and i couldnt find how can i make column names double quoted if field name has any upper case otherwise  if they are all lowercase , it is not needed. 
for example , if field name is dateCo it must be double quoted.
if field name dateco , no need.

postgresql has lower and upper case issue for column names,tables, etc.
i dont know how it will affect orm ,but in order to try i need to solve double quote issue.
src/Ubiquity/db/SqlUtils.php how it can help i am not sure.

**Comment by jcheron** [comment]
In **PDOWrapper** class:
https://github.com/phpMv/ubiquity/blob/3a8d703b17ca49ef1f2b9863444daffd704448c9/src/Ubiquity/db/providers/pdo/PDOWrapper.php#L18

You can set `'pgsql'=>'"'`, like for **sqlite**

**Comment by UlasSAYGINIM** [comment]
it is making the all fields double qouted. for example , select * from table1 where "id"= 12
and this query gives error like below.

I mean , we need to examine field data types and if type is integer, we will NOT use double quote for field name. 
the another thing is if fieldname has any upper case , we will ADD double quote for field name does not matter it is integer or not.
SQLutils only looks fieldnames but we need field data types.

if you have quick solution for me as advice to code, i will be happy.

thank you.

Error

    Message : Uncaught PDOException: SQLSTATE[22P02]: Invalid text representation: 7 HATA: integer için geçersiz sözdizimi:"" in C:\Php_Examples\postgresql_test\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\PDOWrapper.php:200 Stack trace: #0 C:\Php_Examples\postgresql_test\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\PDOWrapper.php(200): PDOStatement->execute(Array) #1 C:\Php_Examples\postgresql_test\vendor\phpmv\ubiquity\src\Ubiquity\db\traits\DatabaseOperationsTrait.php(68): Ubiquity\db\providers\pdo\PDOWrapper->_optPrepareAndExecute('SELECT "connect...', Array) #2 C:\Php_Examples\postgresql_test\vendor\phpmv\ubiquity\src\Ubiquity\orm\traits\DAOCoreTrait.php(87): Ubiquity\db\Database->prepareAndExecute('connection', ' WHERE "id" = ?...', '"connection".id...', Array, NULL) #3 C:\Php_Examples\postgresql_test\vendor\phpmv\ubiquity\src\Ubiquity\orm\DAO.php(138): Ubiquity\orm\DAO::_getOne(Object(Ubiquity\db\Database), 'models\\Connecti...', Object(Ubiquity\orm\parser\ConditionParser), false, NULL) #4 C:\Php_E
    File : C:\Php_Examples\postgresql_test\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\PDOWrapper.php
    Line : 200

**Comment by jcheron** [comment]
There is no connection between the type of data and the protection of names with quotes.

**Comment by UlasSAYGINIM** [comment]
yes you are right. i am creating new projext to test it again.

may i ask you how can i understand reason of this error.

I cant see full sql query to get idea. how i can see full sql query to which part is wrong?

Error

    Message : Uncaught PDOException: SQLSTATE[22P02]: Invalid text representation: 7 HATA: integer için geçersiz sözdizimi:"" in C:\Php_Examples\postgresql_test\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\PDOWrapper.php:200 Stack trace: #0 C:\Php_Examples\postgresql_test\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\PDOWrapper.php(200): PDOStatement->execute(Array) #1 C:\Php_Examples\postgresql_test\vendor\phpmv\ubiquity\src\Ubiquity\db\traits\DatabaseOperationsTrait.php(68): Ubiquity\db\providers\pdo\PDOWrapper->_optPrepareAndExecute('SELECT "connect...', Array) #2 C:\Php_Examples\postgresql_test\vendor\phpmv\ubiquity\src\Ubiquity\orm\traits\DAOCoreTrait.php(87): Ubiquity\db\Database->prepareAndExecute('connection', ' WHERE "id" = ?...', '"connection".id...', Array, NULL) #3 C:\Php_Examples\postgresql_test\vendor\phpmv\ubiquity\src\Ubiquity\orm\DAO.php(138): Ubiquity\orm\DAO::_getOne(Object(Ubiquity\db\Database), 'models\\Connecti...', Object(Ubiquity\orm\parser\ConditionParser), false, NULL) #4 C:\Php_E
    File : C:\Php_Examples\postgresql_test\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\PDOWrapper.php
    Line : 200

**Comment by UlasSAYGINIM** [comment]
or this one?

Error

    Message : Uncaught PDOException: SQLSTATE[22P02]: Invalid text representation: 7 HATA: integer için geçersiz sözdizimi:"" in C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\PDOWrapper.php:195 Stack trace: #0 C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\PDOWrapper.php(195): PDOStatement->execute(Array) #1 C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\db\traits\DatabaseOperationsTrait.php(68): Ubiquity\db\providers\pdo\PDOWrapper->_optPrepareAndExecute('SELECT "connect...', Array) #2 C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\orm\traits\DAOCoreTrait.php(87): Ubiquity\db\Database->prepareAndExecute('connection', ' WHERE "id" = ?...', '"connection"."i...', Array, NULL) #3 C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\orm\DAO.php(138): Ubiquity\orm\DAO::_getOne(Object(Ubiquity\db\Database), 'models\\Connecti...', Object(Ubiquity\orm\parser\ConditionParser), false, NULL) #4 C:\
    File : C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\PDOWrapper.php
    Line : 195

**Comment by jcheron** [comment]
you can activate the logging:
with
```bash
composer require monolog/monolog
```
In config file:
`'debug'=>true`

or alternatively, you can use xDebug

**Comment by UlasSAYGINIM** [comment]
thank you very much for you help.

**Comment by UlasSAYGINIM** [comment]
Using version ^2.0 for monolog/monolog
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating monolog/monolog (1.25.3 => 2.0.2): Loading from cache
Writing lock file
Generating autoload files


after that web tools log screens gives notice and error like this :
on page top 
Notice: in C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\log\libraries\UMonolog.php on line 72

Notice: in C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\log\libraries\UMonolog.php on line 72

Notice: in C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\log\libraries\UMonolog.php on line 72

Notice: in C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\log\libraries\UMonolog.php on line 72

Notice: in C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\log\libraries\UMonolog.php on line 72

Notice: in C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\log\libraries\UMonolog.php on line 72

Notice: in C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\log\libraries\UMonolog.php on line 72


on page bottom
Error

    Message : Trying to get property 'date' of non-object
    File : C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\log\libraries\UMonolog.php
    Line : 72

**Comment by jcheron** [comment]
with `Monolog 2.0`,
you need to use the `dev-master` version of ubiquity.
see https://github.com/phpMv/ubiquity/commit/212393be865a314873950d550192cdc105def86f

**Comment by jcheron** [comment]
I think it's the **UbiquityMyAdmin** interface that should emit the PDO error messages, not what you did .
Some queries in the interface are not parameterized... 

Such:
```sql
SELECT fields FROM table where id='1';
```
And **pgsql** dislike single quotes when the id is an integer.
I'm going to check this and switch everything to parameterized queries.

**Comment by UlasSAYGINIM** [comment]
Thank you. I was trying to find the issue , I couldnt correctly find reason , i guessed but not correct one. I was confused.

for dev master, can i download it with composer or ubiquity command on windows?
or i have to use git clone?

additionally, is there any way to see full messages on web interface?

**Comment by UlasSAYGINIM** [comment]
there are errors on admin interface. if you can tell me how to open full error messages without omit.
I can find the reasons. because driver is working but admin interface has errors even there is no record if you click nothing to see section. it gives error.

**Comment by UlasSAYGINIM** [comment]
like this ,

  Message : Uncaught ArgumentCountError: Too few arguments to function Ubiquity\controllers\admin\UbiquityMyAdminBaseController::showDetail(), 0 passed in C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\controllers\Startup.php on line 148 and exactly 1 expected in C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity-webtools\src\Ubiquity\controllers\admin\traits\ModelsTrait.php:352 Stack trace: #0 C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\controllers\Startup.php(148): Ubiquity\controllers\admin\UbiquityMyAdminBaseController->showDetail() #1 C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\controllers\Startup.php(109): Ubiquity\controllers\Startup::runAction(Array, true, true) #2 C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\controllers\Startup.php(69): Ubiquity\controllers\Startup::forward('Admin/showDetai...') #3 C:\Php_Examples\postgresql_test2\.ubiquity\_index.php(18): Ubiquity\controllers\Startup::run(Array) #4 C:\Php_Examples\po
    File : C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity-webtools\src\Ubiquity\controllers\admin\traits\ModelsTrait.php
    Line : 352

**Comment by UlasSAYGINIM** [comment]
the another thing is ,mysql specific rownumber issue i think.
it seems it is diffrent in pgsql. the error below.

and for admin interface i can say ,i cant see pagination works for some tables.

Message : Uncaught PDOException: SQLSTATE[42601]: Syntax error: 7 HATA: ":=" yerinde söz dizim hatası LINE 1: SELECT num FROM (SELECT *, @rownum:=@rownum + 1 AS num FROM ... ^ in C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\PDOWrapper.php:129 Stack trace: #0 C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\PDOWrapper.php(129): PDO->query('SELECT num FROM...') #1 C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\db\traits\DatabaseOperationsTrait.php(180): Ubiquity\db\providers\pdo\PDOWrapper->queryColumn('SELECT num FROM...', NULL) #2 C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\orm\DAO.php(83): Ubiquity\db\Database->queryColumn('SELECT num FROM...') #3 C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity-webtools\src\Ubiquity\controllers\admin\traits\ModelsTrait.php(141): Ubiquity\orm\DAO::getRownum('models\\User', '"id"='6'') #4 C:\Php_Examples\postgresql
    File : C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\PDOWrapper.php
    Line : 129

**Comment by UlasSAYGINIM** [comment]
I will fork project after you are sure about admin interface and then i will upload drivers.
if i can see omitted error messages , i am willing to fix things.

**Comment by UlasSAYGINIM** [comment]
I think i got dev-master by composer require phpmv/ubiquity:"dev-master"

**Comment by UlasSAYGINIM** [comment]
I installed monolog latest version too.
I still get same errors related to monolog and this time , php notice logs are different.
like this : 

! ) Notice:  in C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\log\libraries\UMonolog.php on line 72
--


1 | 0.1945 | 402224 | {main}(  ) | ...\.htrouter.php:0
2 | 0.1953 | 409912 | include_once( 'C:\Php_Examples\postgresql_test2\.ubiquity\_index.php' ) | ...\.htrouter.php:5
3 | 0.2375 | 1767640 | Ubiquity\controllers\Startup::run(  ) | ...\_index.php:18
4 | 0.2576 | 2478864 | Ubiquity\controllers\Startup::forward(  ) | ...\Startup.php:69
5 | 0.2590 | 2485416 | Ubiquity\controllers\Startup::runAction(  ) | ...\Startup.php:109
6 | 0.3054 | 5217560 | controllers\Admin->logs(  ) | ...\Startup.php:148
7 | 0.3422 | 7006048 | Ubiquity\controllers\admin\UbiquityMyAdminViewer->getLogsDataTable(  ) | ...\UbiquityMyAdminBaseController.php:739
8 | 0.3422 | 7006048 | Ubiquity\log\Logger::asObjects(  ) | ...\UbiquityMyAdminViewer.php:1730
9 | 0.3422 | 7006048 | Ubiquity\log\libraries\UMonolog->_asObjects(  ) | ...\Logger.php:84
10 | 0.3437 | 7114632 | Ubiquity\utils\base\UFileSystem::getLines(  ) | ...\UMonolog.php:75
11 | 0.3593 | 7123960 | Ubiquity\log\libraries\UMonolog->Ubiquity\log\libraries\{closure:C:\Php_Examples\postgresql_test2\vendor\phpmv\ubiquity\src\Ubiquity\log\libraries\UMonolog.php:68-75}(   ) | ...\UFileSystem.php:190

**Comment by jcheron** [comment]
I'm having trouble understanding this message...

**Comment by jcheron** [comment]
Stop everything for now,
until I deliver a verified version of the Admin section (tomorrow probably).
In the meantime, do a PR of what you've done, it'll be better to work on it than to talk without seeing any code...

**Comment by UlasSAYGINIM** [comment]
tomorrow i will continue. just i need full error messages. if you can provide a way to get it on web interface, it is good.
Tomorrow i will create my fork and pull request.
see you tomorrow.

**Comment by jcheron** [comment]
A priori, it should work with this `composer.json` file:
```json
{
	"require" : {
		"php" : "^7.4",
		"twig/twig" : "^2.0",
		"phpmv/ubiquity" : "dev-add-pdo-driver-metas",
		"phpmv/php-mv-ui" : "dev-master"
	},
	"require-dev" : {
		"phpmv/ubiquity-dev" : "^0.0",
		"phpmv/ubiquity-webtools" : "dev-master",
		"mindplay\/annotations": "^1.3",
		"monolog/monolog": "^2.0"
	},
	"autoload" : {
		"psr-4" : {
			"" : "app/"
		}
	},
	"minimum-stability": "dev",
	"prefer-stable": true
}
```

There should be at least 2 more exceptions to deal with:
- in the `DAO::getRowNum` method (mysql's @rownum problem like you said)
- The `PDOWrapper::lastInsertId` method, which needs the sequence name (`tableName_idName_seq`) for pgsql .
These specifics will be integrated into your work.

**Comment by UlasSAYGINIM** [comment]
hi,
can you create ubiquity-redis and ubiquity-mongodb repositories?
if you can create empty classes for skeleton. we may think how to do? does it work for you?
or any another idea?

**Comment by UlasSAYGINIM** [comment]
I will leave  2 more exceptions to you because i am not fully understand other parts like DAO.
When i review and read the code more. i will be more available.
Dont forget the web interface issue about  ' single quote for values which has integer fields causes problem.

**Comment by UlasSAYGINIM** [comment]
Is there any way to execute stored procedures in postgresql with our framework?

**Comment by jcheron** [comment]
> Is there any way to execute stored procedures in postgresql with our framework?

I haven't tried, but there are PDO methods required.
prepareStatement, bindValue, execute...

After integration of your PR, I corrected the few errors found (lastInsertId, rownum...) and the problems of the administration interface.

I haven't tried the pgsql generation yet with a complete DB (all relationships), but on something simple, for now, everything works.

**Comment by UlasSAYGINIM** [comment]
can you create empty functions? or existing functions must be updated?

I created message.sql postgresql version. i tried it creates models but i will try again after your web interface update because web interface gave error for rownum,etc.

**Comment by jcheron** [comment]
Update your version...
```composer update``` in your project
In any case, there is no longer this error (fixed in https://github.com/phpMv/ubiquity/commit/ec9ce72e8d2ceef2b25aaedeac429a0a1db2136f)...

**Comment by UlasSAYGINIM** [comment]
I havent tried updated version. I was saying that. I will try and say it. and I will send Message SQL postgreSQL version.

**Comment by UlasSAYGINIM** [comment]
after update , i got this.

Error

    Message : Class Ubiquity\db\providers\pdo\drivers\SqliteDriverMetas contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Ubiquity\db\providers\pdo\drivers\AbstractDriverMetaDatas::getRowNum)
    File : C:\Php_Examples\postgresql_test\vendor\phpmv\ubiquity\src\Ubiquity\db\providers\pdo\drivers\SqliteDriverMetas.php
    Line : 13

**Comment by UlasSAYGINIM** [comment]
i comes from Web interface Models Section. 
I can connect postgresql via config without problem.

**Comment by UlasSAYGINIM** [comment]
I set sqlite db before. because of this, i had to add sqlite update to this update in order to get work.
and problem solved but getrownum required to implemented for sqlite.
It seems you added the rownum for pgsql. thanks.

**Comment by UlasSAYGINIM** [comment]
![user](https://user-images.githubusercontent.com/20348882/74534125-21b37180-4f44-11ea-88a3-efb2b8e0bfad.png)
![connection](https://user-images.githubusercontent.com/20348882/74534127-224c0800-4f44-11ea-9115-1937a55f0a35.png)
![connection2](https://user-images.githubusercontent.com/20348882/74534129-22e49e80-4f44-11ea-9552-77c54e559187.png)
![connection2_nothingto_display](https://user-images.githubusercontent.com/20348882/74534131-237d3500-4f44-11ea-85e6-0cd6402bd9f7.png)
![groupe](https://user-images.githubusercontent.com/20348882/74534132-237d3500-4f44-11ea-9146-9586313a2a1c.png)
![Groupeusers](https://user-images.githubusercontent.com/20348882/74534134-2415cb80-4f44-11ea-8194-f57528dbd9d5.png)
![Groupeusers_error](https://user-images.githubusercontent.com/20348882/74534135-2415cb80-4f44-11ea-9333-1b527d92fefa.png)
![organization](https://user-images.githubusercontent.com/20348882/74534136-24ae6200-4f44-11ea-90e6-8c4055e314bf.png)
![pqsql_models_created](https://user-images.githubusercontent.com/20348882/74534138-2546f880-4f44-11ea-8c62-892ab9162976.png)

Model creation is ok without problem.
Table name : Connection, when you click on record, details action gives error.
Table name : Connection2, when you click on nothing to display place, and details action gives error.
Table name : Groupe seems nice.
Table name : Groupeusers, shows only 1 record for each page. kind of weird.
Table name : Groupeusers, when you click on record, it gives error.
Table name : organization seems ok just gui is not popup. maybe it is normal.
Table name :user , when you click on record, it gives error.

**Comment by UlasSAYGINIM** [comment]
I cant see the problem , i think i am not able to see full SQL and i am not also sure about is it all SQL related or other things.

**Comment by jcheron** [comment]
There's a problem with this method:
https://github.com/phpMv/ubiquity/blob/22662c91090dd90b5e7b81778b19ca7227611d21/src/Ubiquity/db/providers/pdo/drivers/PgsqlDriverMetas.php#L16

If you look at the generated classes, the `@manyToOne`, `@oneToMany` and `@manyToMany` relationships are not good.

**Comment by UlasSAYGINIM** [comment]
[pgsql_messages.txt](https://github.com/phpMv/ubiquity/files/4204607/pgsql_messages.txt)

it is postgresql creation. it needs ubiphp user for database access.

**Comment by UlasSAYGINIM** [comment]
I found the problem and updated on my fork.
but there is another problem. web interface says.
Models generation

    The table groupeusers does not exists for the model models\Groupeusers.

**Comment by jcheron** [comment]
see fix https://github.com/phpMv/ubiquity/commit/57a5760099b74aa017f89a321eadc37beeb5fbc7

The `@manyToOne` and `@oneToMany` relations are well generated now
![image](https://user-images.githubusercontent.com/2511052/74537017-8917f400-4f39-11ea-8abd-893195bb3232.png)

I still have to test the `@manyToMany`

**Comment by UlasSAYGINIM** [comment]
which tables have manytomany?

**Comment by jcheron** [comment]
> which tables have manytomany?

`user` and `group` => `groupeusers`
`organization` and `settings` => `organizationsettings`

**Comment by jcheron** [comment]
It's okay for all types of relationships
![image](https://user-images.githubusercontent.com/2511052/74550326-82957680-4f51-11ea-9e54-231cb9111521.png)

There is still a bug on the search (in the admin interface)

**Comment by UlasSAYGINIM** [comment]
yes but i gives error. I have deleted table than created empty one , this time i can be able to create models.
it is weird for me because , I couldnt understand why it couldnt recognize manytomany.
tomorrow i will look at. see you tomorrow. 

and i am still not able to get Full error log on web interface.
xdebug is very different than actual logs thanks for advice.
I will look this log issue to later. because you can see the which part is problem. I cant see.
Thank you for your help and patience.

**Comment by UlasSAYGINIM** [comment]
now i saw your comment lately. github refreshed my old page after i submit new comment. 
as I understand that PDO driver is not an issue because it seems all the other things had been changed.
I was thinking that this kind of thing because after my last fix, it was identical like mysql at query result.
as I understand PDO PostgreSQL driver gets everything right and no problem, correct me if i am missing something.

I will focus on Stored procedure for postgresql and the issue 83.
but i couldnt understand what is it. which parts needs to use in order to do.
can you explain it. because i havent read whole documentation because of Postgresql pdo driver issue , i stoped at Connecting to the database :)

https://github.com/phpMv/ubiquity/issues/83

**Comment by UlasSAYGINIM** [comment]
admin interface has some other bugs, for example. 
When I clicked another Database section like SQLite , the model page must be changed and show me the SQLite database models. but to see the model after i selected database, i have to click models section next to cache section not up side menu.

Tomorrow i will test and read  everyting again.
see you.

**Comment by jcheron** [comment]
A priori, the generation of classes, and the Admin interface are ok for me with **pgsql** (it's ok for the search area).
You have to be careful to be on the latest versions of each repositories branch.

```bash
composer clearcache
composer require phpmv/ubiquity:dev-add-pdo-driver-metas
composer require phpmv/ubiquity-webtools:dev-master
```

**Comment by jcheron** [comment]
In your **messages** database, you lack this constraint...
```sql
ALTER TABLE public.organizationsettings
 ADD CONSTRAINT organizationsettings_pkey PRIMARY KEY ("idOrganization","idSettings");
```

**Comment by jcheron** [comment]
@UlasSAYGINIM 
no more problems with pgsql?
can we move on?

**Comment by UlasSAYGINIM** [comment]
I was sick, i couldnt test it. sorry about that. i am planing to test on monday. waiting to get better.

**Comment by jcheron** [comment]
Okay, get well soon!
